Repository opendatahub-io/opendatahub-operator, pull requests merged in 2020-11, with the labels that each got.

#72 enable thoth-bot kebechet to handle release changelogs
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
  .thoth.yaml
  version.py
Labels: approved, lgtm

#77 Add lavlas to thoth maintainers
  .thoth.yaml
Labels: approved, lgtm

#79 Release of version 0.9.0
  CHANGELOG.md
  version.py
Labels: approved, bot, lgtm

#74 ODH 0.9.0 Release
  deploy/olm-catalog/opendatahub/0.9.0/kfdef.apps.kubeflow.org.crd.yaml
  deploy/olm-catalog/opendatahub/0.9.0/opendatahub-operator.v0.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/opendatahub/opendatahub-operator.package.yaml
Labels: approved
