Repository opendatahub-io/opendatahub-operator, pull requests merged in 2023-09, with the labels that each got.

#514 Adding docs on setting up a linux dev environment
  CONTRIBUTING.md
Labels: lgtm, approved

#487 fix: reworks reconcilation resource check
  controllers/datasciencecluster/datasciencecluster_controller.go
Labels: lgtm, approved, rhods-1.33

#509 Fix: downstream codeflare has a different operator name than upstream
  components/codeflare/codeflare.go
  components/dashboard/dashboard.go
  components/workbenches/workbenches.go
Labels: lgtm, approved, rhods-1.33

#506 Docs: add new troublshooting page + fix markdown format
  README.md
  docs/DESIGN.md
  docs/Dev-Preview.md
  docs/troubleshooting.md
Labels: lgtm, approved

#417 Change downstream odh-dashboard ISV new path
  components/dashboard/dashboard.go
Labels: lgtm, approved, rhods-1.33

#521 Add path for managed version of Workbenches
  components/workbenches/workbenches.go
  controllers/dscinitialization/dscinitialization_controller.go
Labels: lgtm, approved

#518 Add: use --no-cache to prevent not pulling down to new layer
  Makefile
Labels: lgtm, approved, rhods-1.33

#523 Fix: in e2e or dev test should not apply addon manifests
  components/workbenches/workbenches.go
Labels: lgtm, approved, rhods-1.33

#524 Fix: downstream workbranch to get imageparams
  components/workbenches/workbenches.go
Labels: lgtm, approved

#504 Fix and Cleanup: applyimageparams on kserve
  components/codeflare/codeflare.go
  components/kserve/kserve.go
  controllers/datasciencecluster/datasciencecluster_controller.go
Labels: lgtm, approved, rhods-1.33

#497 Add check on dependent operators on KServe
  Makefile
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  components/codeflare/codeflare.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/ray/ray.go
  config/rbac/role.yaml
  controllers/datasciencecluster/kubebuilder_rbac.go
  main.go
  pkg/deploy/deploy.go
  tests/e2e/dsc_creation_test.go
  tests/e2e/helper_test.go
Labels: lgtm, approved, rhods-1.33

#511 Fix: MCAD and InstaScale CR not deleted when components are Removed
  components/codeflare/codeflare.go
  go.mod
  go.sum
  main.go
Labels: lgtm, approved, rhods-1.33

#526 Fix issues introduced in dashboard and code flare
  components/codeflare/codeflare.go
  components/dashboard/dashboard.go
  config/rbac/role.yaml
  controllers/datasciencecluster/kubebuilder_rbac.go
Labels: lgtm

#528 Update path for downstream dashboard image to use
  components/dashboard/dashboard.go
Labels: lgtm, approved, rhods-1.33

#529 Fix: missing permission is needed when DSP is disabled, to keep same behavior as for v1
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/datasciencecluster/kubebuilder_rbac.go
Labels: lgtm, approved, rhods-1.33

#489 chore: simplifies reconcile functions
  components/README.md
  components/codeflare/codeflare.go
  components/component.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/modelmeshserving/modelmeshserving.go
  components/ray/ray.go
  components/workbenches/workbenches.go
  controllers/datasciencecluster/datasciencecluster_controller.go
Labels: rhods-1.34

#535 Fix: missing odh-admins group
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/utils.go
Labels: lgtm, approved, rhods-1.34

#527 Update: networkpolicy for ODH created namespace
  controllers/dscinitialization/utils.go
Labels: lgtm, approved, rhods-1.34

#536 chore: minor clean-ups
  .gitignore
  README.md
  apis/datasciencecluster/v1/datasciencecluster_types.go
  components/README.md
  components/codeflare/codeflare.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/modelmeshserving/modelmeshserving.go
  components/ray/ray.go
  components/workbenches/workbenches.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/monitoring.go
  controllers/dscinitialization/utils.go
  controllers/secretgenerator/secret.go
  controllers/secretgenerator/secretgenerator_controller.go
  controllers/status/status.go
  docs/DESIGN.md
  go.mod
  go.sum
  main.go
  pkg/common/common.go
  pkg/deploy/deploy.go
  pkg/deploy/setup.go
  tests/e2e/controller_setup_test.go
  tests/e2e/dsc_creation_test.go
  tests/e2e/dsc_deletion_test.go
Labels: lgtm, approved

#431 Update Dockerfile to pull manifests from different component repo
  Dockerfiles/Dockerfile
  Makefile
  README.md
  components/kserve/kserve.go
  get_all_manifests.sh
  odh-manifests/.gitkeep
Labels: lgtm, approved, rhods-1.34

#537 chore: simplifies deployment funcs
  components/codeflare/codeflare.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/modelmeshserving/modelmeshserving.go
  components/ray/ray.go
  components/workbenches/workbenches.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/monitoring.go
  pkg/deploy/deploy.go
  pkg/plugins/addLabelsplugin.go
  pkg/plugins/namespacePlugin.go
Labels: lgtm, approved, rhods-1.34

#554 Revert: change to delete CF resource is not required
  components/codeflare/codeflare.go
Labels: lgtm, approved, odh-1.10

#552 Update: change apigroup for codeflare and dsp
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/rbac/role.yaml
  controllers/datasciencecluster/kubebuilder_rbac.go
Labels: lgtm, approved, odh-1.10

#544 Update v1 operator to use component repo for manifests not odh-manifests
  Dockerfile
  Makefile
  README.md
  get_all_manifests.sh
Labels: lgtm, approved, v1, odh-1.10

#561 Update dashboard default branch
  get_all_manifests.sh
Labels: lgtm, approved, odh-1.10

#559 Trustyai manifests and dashboard branch
  get_all_manifests.sh
Labels: lgtm, approved

#533 Add dashboard crds using manifests
  bundle/manifests/console.openshift.io_odhquickstarts.yaml
  bundle/manifests/dashboard.opendatahub.io_odhapplications.yaml
  bundle/manifests/dashboard.opendatahub.io_odhdocuments.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  bundle/manifests/opendatahub.io_odhdashboardconfigs.yaml
  components/dashboard/dashboard.go
  config/crd/bases/odhapplications.dashboard.opendatahub.io_odhapplications.yaml
  config/crd/bases/odhdashboardconfigs.opendatahub.io_odhdashboardconfigs.yaml
  config/crd/bases/odhdocuments.dashboard.opendatahub.io_odhdocuments.yaml
  config/crd/bases/odhquickstarts.console.openshift.io_odhquickstarts.yaml
  config/crd/kustomization.yaml
  tests/e2e/odh_manager_test.go
Labels: approved, rhods-1.34

#562 Fix: wrong image for odh-model-controller when enable kserve
  components/kserve/kserve.go
Labels: lgtm, approved, rhods-1.33

#538 Implement DevFlags for DSC API
  Makefile
  apis/datasciencecluster/v1/zz_generated.deepcopy.go
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  components/codeflare/codeflare.go
  components/component.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/modelmeshserving/modelmeshserving.go
  components/ray/ray.go
  components/workbenches/workbenches.go
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/datasciencecluster/kubebuilder_rbac.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/utils.go
  get_all_manifests.sh
  pkg/deploy/deploy.go
Labels: lgtm, approved, rhods-1.34

#570 [odh-2.2.0] Add acceleratorprofiles from dashboard as new CRD
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/datasciencecluster/kubebuilder_rbac.go
Labels: lgtm, odh-1.10

#566 ODH Release 1.10 for operator v2.2.0
  Makefile
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  get_all_manifests.sh
Labels: lgtm

#569 Add acceleratorprofiles from dashboard as new CRD
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/datasciencecluster/kubebuilder_rbac.go
Labels: lgtm, approved, rhods-1.34

#565 ODH Release 1.10 for operator v1.10.0
  bundle/manifests/dashboard.opendatahub.io_acceleratorprofiles.yaml
  bundle/manifests/dashboard.opendatahub.io_odhapplications.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  bundle/manifests/opendatahub.io_odhdashboardconfigs.yaml
  config/crd/dashboard-crds/acceleratorprofiles.opendatahub.io.crd.yaml
  config/crd/dashboard-crds/odhdashboardconfigs.opendatahub.io.crd.yaml
  config/crd/kustomization.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  get_all_manifests.sh
Labels: lgtm

#541 Add feature/functional tests in DSCInitialization
  Makefile
  README.md
  config/crd/external/operators.coreos.com_clusterserviceversions.yaml
  controllers/dscinitialization/dscinitialization_test.go
  controllers/dscinitialization/suite_test.go
  controllers/test/envtest_setup.go
Labels: lgtm, approved
