Repository opendatahub-io/opendatahub-operator, pull requests merged in 2023-08, with the labels that each got.

#397 Add Authentication overlay for dashboard
  components/dashboard/dashboard.go
  pkg/plugins/addLabelsplugin.go
Labels: lgtm

#402 Allow multiple component names for Dashboard
  components/dashboard/dashboard.go
Labels: lgtm, approved

#406 DSCInit force update instances
  main.go
Labels: lgtm, approved

#409 Update installation instructions
  README.md
Labels: lgtm, approved

#408 Revert changes to dashboard CRD
  bundle/manifests/dashboard.opendatahub.io_odhapplications.yaml
  config/crd/bases/odhapplications.dashboard.opendatahub.io_odhapplications.yaml
Labels: lgtm, approved

#411 Expand namespace plugin to add MutatingWebhookConfiguration
  pkg/plugins/namespacePlugin.go
Labels: lgtm, approved

#410 Fix consolelink
  components/dashboard/dashboard.go
  controllers/dscinitialization/utils.go
Labels: lgtm, approved

#412 Fixes #324 . Showing all components in YAML CR, even if disabled.
  controllers/datasciencecluster/datasciencecluster_controller.go
Labels: lgtm, approved

#414 Uncommenting Ray component after fix to the ray manifests. fixes #369
  controllers/datasciencecluster/datasciencecluster_controller.go
Labels: lgtm, approved

#413 Add support for anaconda resources
  components/dashboard/dashboard.go
  pkg/common/common.go
Labels: lgtm, approved

#420 Fix: wrong consolelink url missing "."
  components/dashboard/dashboard.go
Labels: lgtm, approved

#421 Update fixes for managed platform
  components/dashboard/dashboard.go
  controllers/dscinitialization/dscinitialization_controller.go
  pkg/common/common.go
  pkg/deploy/deploy.go
Labels: lgtm, approved

#419 Add order in marker to reorder CSV + remove context which is not in use + remove logger for secretgen
  apis/datasciencecluster/v1alpha1/datasciencecluster_types.go
  apis/dscinitialization/v1alpha1/dscinitialization_types.go
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/secretgenerator/secretgenerator_controller.go
Labels: lgtm, approved

#429 Feature rearchitecture
  README.md
  apis/datasciencecluster/v1alpha1/datasciencecluster_types.go
  apis/dscinitialization/v1alpha1/dscinitialization_types.go
  bundle/manifests/dashboard.opendatahub.io_odhapplications.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  components/dashboard/dashboard.go
  config/crd/bases/odhapplications.dashboard.opendatahub.io_odhapplications.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/utils.go
  controllers/secretgenerator/secretgenerator_controller.go
  main.go
  pkg/common/common.go
  pkg/deploy/deploy.go
  pkg/plugins/namespacePlugin.go
Labels: lgtm

#433 Update: segment-io CM namespace from monitoring to application's
  controllers/dscinitialization/monitoring.go
Labels: lgtm, approved

#435 Update kserve configs
  components/kserve/kserve.go
  pkg/plugins/namespacePlugin.go
Labels: lgtm, approved

#438 add odh-model-controller with kserve
  components/kserve/kserve.go
Labels: lgtm, approved

#446 Add support for custom subscription config
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  main.go
Labels: lgtm, approved

#451 Move creation of notebooks namespace to workbenches
  components/workbenches/workbenches.go
  controllers/dscinitialization/dscinitialization_controller.go
Labels: lgtm, approved

#449 Fix: sample to use namespace opendatahub than opendatahub-system
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/samples/dscinitialization_v1alpha1_dscinitialization.yaml
Labels: lgtm, approved

#385 Before applying CodeFlare manifests, check for the codeflare-operator
  components/codeflare/codeflare.go
  pkg/deploy/deploy.go
Labels: lgtm, approved

#452 Removed cfchase from OWNERS
  OWNERS
Labels: lgtm, approved

#447 Update permission on operator level
  Makefile
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/datasciencecluster_datasciencecluster_editor_role.yaml
  config/rbac/datasciencecluster_datasciencecluster_viewer_role.yaml
  config/rbac/dscinitialization_dscinitialization_editor_role.yaml
  config/rbac/dscinitialization_dscinitialization_viewer_role.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/role.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/secretgenerator/secretgenerator_controller.go
Labels: lgtm, approved

#453 Add more permission for modelmesh
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
Labels: lgtm, approved

#457 Add pre config only when component is enabled
  components/codeflare/codeflare.go
  components/dashboard/dashboard.go
  components/kserve/kserve.go
  components/modelmeshserving/modelmeshserving.go
  components/ray/ray.go
  components/workbenches/workbenches.go
Labels: lgtm, approved

#459 Fix: move deploy manifests only for non-ODH to block
  components/dashboard/dashboard.go
Labels: lgtm, approved

#437 Update e2e test: timeout + ray + logging
  Makefile
  tests/e2e/controller_setup_test.go
  tests/e2e/dsc_creation_test.go
  tests/e2e/dsc_deletion_test.go
  tests/e2e/helper_test.go
  tests/e2e/odh_manager_test.go
Labels: lgtm, approved

#430 Update metrics host IP
  bundle/manifests/opendatahub-operator-manager-config_v1_configmap.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/controller_manager_config.yaml
Labels: lgtm, approved

#416 Revert: do not set imageParamMap for CF
  components/codeflare/codeflare.go
Labels: lgtm, approved, rhods-1.32

#465 ODH Release 1.9 for operator v2.1.0
  Dockerfiles/Dockerfile
  Makefile
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/description-patch.yml
  config/samples/datasciencecluster_v1alpha1_datasciencecluster.yaml
Labels: lgtm, approved

#469 ODH Release 1.9 for operator v1.9.0
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#483 fix(rbac): adds list role for configmaps and namespaces
  config/rbac/role.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
Labels: lgtm, approved

#491 Removing DSC version v1alpha1 from the CSV
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#399 Fix wrong monitoring and add logger
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  controllers/dscinitialization/monitoring.go
Labels: lgtm, approved, rhods-1.33

#467 Add support for consolelink section title for different cluster type
  components/dashboard/dashboard.go
Labels: lgtm, approved, rhods-1.33

#486 Fix: explictly check platform is selfmanaged or managed
  README.md
  components/dashboard/dashboard.go
  components/workbenches/workbenches.go
  pkg/deploy/setup.go
Labels: lgtm, approved

#488 Docs: update godocs for synopsis and add function comments
  apis/datasciencecluster/v1/datasciencecluster_types.go
  apis/datasciencecluster/v1/groupversion_info.go
  apis/dscinitialization/v1/dscinitialization_types.go
  apis/dscinitialization/v1/groupversion_info.go
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  components/codeflare/codeflare.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/modelmeshserving/modelmeshserving.go
  components/ray/ray.go
  components/workbenches/workbenches.go
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/secretgenerator/secretgenerator_controller.go
  controllers/status/status.go
  pkg/common/common.go
  pkg/deploy/deploy.go
Labels: lgtm, approved

#474 [Cherry-pick]: Update GH action to filter out words when sync from dashboard CRD from v1.x
  .github/workflows/sync_dashboard_crds.yaml
Labels: lgtm, approved

#494 Cleanup v1alpha1 of DSIC
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  main.go
Labels: lgtm, approved

#495 Fix typo in groupname
  apis/dscinitialization/v1/groupversion_info.go
Labels: lgtm, approved

#463 Add support for manifestUri to overwrite params.env images
  README.md
  components/README.md
  components/codeflare/codeflare.go
  components/component.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/modelmeshserving/modelmeshserving.go
  components/ray/ray.go
  components/workbenches/workbenches.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  pkg/deploy/deploy.go
Labels: lgtm, approved
