Repository opendatahub-io/opendatahub-operator, pull requests merged in 2023-12, with the labels that each got.

#774 chore: keeps repositories in the tmp dir
  get_all_manifests.sh
Labels: lgtm

#782 update(kserve): add monitoring logic
  components/component.go
  components/kserve/kserve.go
Labels: lgtm, approved

#767 chore(mesh): Use third party service account tokens
  pkg/feature/templates/servicemesh/base/smcp.tmpl
Labels: lgtm, incubating

#787 chore: change log info for monitoring patch namespace
  controllers/dscinitialization/utils.go
Labels: lgtm, approved

#659 fix devflags empty object
  apis/dscinitialization/v1/dscinitialization_types.go
  apis/dscinitialization/v1/zz_generated.deepcopy.go
  components/codeflare/codeflare.go
  components/component.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/modelmeshserving/modelmeshserving.go
  components/ray/ray.go
  components/trustyai/trustyai.go
  components/workbenches/workbenches.go
  components/zz_generated.deepcopy.go
Labels: lgtm

#781 feature: add support for unmanaged and remove for servicemesh and serverless
  components/kserve/kserve.go
  controllers/dscinitialization/servicemesh_setup.go
Labels: rhods-2.6

#789 fix(rbac): missing get verbs on MWC and Secret
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/datasciencecluster/kubebuilder_rbac.go
Labels: lgtm, approved, rhods-2.6

#756 fix(nilpointer): when more than one DSCI CR in cluster
  controllers/dscinitialization/dscinitialization_controller.go
Labels: lgtm, odh-2.5

#790 chore: change label name for networkpolicy
  controllers/dscinitialization/utils.go
Labels: lgtm
