Repository opendatahub-io/opendatahub-operator, pull requests merged in 2023-07, with the labels that each got.

#272 Fix: mismatch role binding and missing clusterrole permission in CSV
  Makefile
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/manager/kustomization.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  controllers/dscinitialization/dscinitialization_controller.go
Labels: lgtm, approved

#271 Update OLM bundle for ODH 1.7 Release
  bundle.Dockerfile
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  bundle/manifests/opendatahub.io_odhdashboardconfigs.yaml
  bundle/metadata/annotations.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#274 Add imagepullpolicy for kube-rbac-proxy
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
Labels: lgtm, approved

#275 Update logger for dscinitialzation start time
  controllers/dscinitialization/dscinitialization_controller.go
Labels: lgtm, approved

#264 Determine install environment for operator
  Makefile
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  controllers/dscinitialization/dscinitialization_controller.go
  go.mod
  go.sum
  pkg/deploy/setup.go
Labels: approved

#267 Implement DSC controller
  Dockerfile
  apis/datasciencecluster/v1alpha1/datasciencecluster_types.go
  apis/datasciencecluster/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  components/README.md
  components/component.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/modelmeshserving/modelmeshserving.go
  components/profiles/profiles.go
  components/workbenches/workbenches.go
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/monitoring.go
  controllers/dscinitialization/utils.go
  controllers/secretgenerator/README.md
  controllers/secretgenerator/secret.go
  controllers/secretgenerator/secret_test.go
  controllers/secretgenerator/secretgenerator_controller.go
  main.go
  pkg/common/common.go
  pkg/deploy/deploy.go
Labels: lgtm, approved

#282 Add preview updates
  Makefile
  README.md
  apis/datasciencecluster/v1alpha1/datasciencecluster_types.go
  bundle.Dockerfile
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  components/profiles/profiles.go
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  docs/Dev-Preview.md
Labels: lgtm, approved

#284 Add "none" component profile
  apis/datasciencecluster/v1alpha1/datasciencecluster_types.go
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  components/profiles/profiles.go
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/description-patch.yml
  config/manifests/kustomization.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
Labels: lgtm, approved, needs-ok-to-test

#287 Update: correct channel name
  docs/Dev-Preview.md
Labels: lgtm, approved

#270 Add SMTP sender and receiver email secrets
  controllers/dscinitialization/monitoring.go
Labels: lgtm, approved

#277 Add logging to show cluster type and if monitoring enabled by user
  Dockerfile
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/monitoring.go
  pkg/deploy/setup.go
Labels: lgtm, approved

#285 Change Namespaces from string[] to string
  Dockerfile
  apis/dscinitialization/v1alpha1/dscinitialization_types.go
  apis/dscinitialization/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/rbac/role.yaml
  controllers/dscinitialization/dscinitialization_controller.go
  main.go
Labels: lgtm, approved

#280 Remove rbac container from Pod
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
  controllers/dscinitialization/monitoring.go
Labels: lgtm, approved

#281 Update Dockerfile, Makefile and Kustomzation
  Dockerfiles/Dockerfile
  Dockerfiles/bundle.Dockerfile
  Dockerfiles/toolbox.Dockerfile
  Makefile
  README.md
  config/crd/kustomization.yaml
  config/default/kustomization.yaml
  config/manifests/kustomization.yaml
  config/scorecard/kustomization.yaml
Labels: lgtm

#276 Update dscinitiazation spec for monitoring
  apis/dscinitialization/v1alpha1/dscinitialization_types.go
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  config/samples/console_v1_odhquickstarts.yaml
  config/samples/dashboard_v1_odhapplications.yaml
  config/samples/dashboard_v1_odhdocuments.yaml
  config/samples/datasciencecluster_v1alpha1_datasciencecluster.yaml
  config/samples/dscinitialization_v1alpha1_dscinitialization.yaml
  config/samples/kustomization.yaml
  config/samples/opendatahub_v1alpha1_odhdashboardconfigs.yaml
Labels: lgtm, approved

#290 Add OauthClient resource to scheme
  main.go
Labels: lgtm, approved

#291 Update Operator Dev preview to v0.0.2
  Makefile
  apis/dscinitialization/v1alpha1/dscinitialization_types.go
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/manager/kustomization.yaml
  config/rbac/role.yaml
  controllers/dscinitialization/monitoring.go
  docs/Dev-Preview.md
Labels: lgtm, approved

#295 Fix sample from string array to string
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/samples/dscinitialization_v1alpha1_dscinitialization.yaml
Labels: lgtm, approved

#294 Update to /opt/manifests from /opt/odh-manifests
  Dockerfiles/Dockerfile
  Makefile
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/modelmeshserving/modelmeshserving.go
  components/workbenches/workbenches.go
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/rbac/role.yaml
  controllers/dscinitialization/monitoring.go
  pkg/deploy/deploy.go
Labels: lgtm, approved

#298 Update sample config
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/samples/datasciencecluster_v1alpha1_datasciencecluster.yaml
Labels: lgtm, approved

#303 Add odh-common-config Configmap
  controllers/dscinitialization/utils.go
Labels: lgtm, approved

#292 Improving logging and eventing. #254
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/monitoring.go
  main.go
Labels: lgtm, approved

#304 Create new Dev preview version v0.0.3
  Dockerfiles/Dockerfile
  Makefile
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  docs/Dev-Preview.md
Labels: lgtm, approved

#310 Create new Dev preview version v0.0.4
  Makefile
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: lgtm

#317 Add Modelmesh monitoring
  components/modelmeshserving/modelmeshserving.go
Labels: lgtm, approved

#315 Add Kserve to components
  apis/datasciencecluster/v1alpha1/datasciencecluster_types.go
  apis/datasciencecluster/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  components/kserve/kserve.go
  components/profiles/profiles.go
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  go.mod
Labels: lgtm, approved

#312 Implement logic for Updating from Legacy Operator
  PROJECT
  apis/datasciencecluster/v1alpha1/datasciencecluster_types.go
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/modelmeshserving/modelmeshserving.go
  components/profiles/profiles.go
  components/workbenches/workbenches.go
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/datasciencecluster/suite_test.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/monitoring.go
  controllers/dscinitialization/suite_test.go
  controllers/dscinitialization/utils.go
  go.mod
  go.sum
  main.go
  pkg/deploy/deploy.go
Labels: lgtm, approved

#321 Update sample for new operator, default applicationNamespace and deprecated kustomize field
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/default/kustomization.yaml
  config/manifests/kustomization.yaml
  config/prometheus/kustomization.yaml
  config/rbac/kustomization.yaml
  config/samples/datasciencecluster_v1alpha1_datasciencecluster.yaml
  config/samples/dscinitialization_v1alpha1_dscinitialization.yaml
  config/samples/kustomization.yaml
  config/scorecard/kustomization.yaml
Labels: lgtm, approved

#286 Add kfdef CRD back
  bundle/manifests/kfdef.apps.kubeflow.org_kfdefs.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/crd/additionals/kfdef.apps.kubeflow.org_kfdefs.yaml
  config/crd/kustomization.yaml
  config/samples/dashboard_v1_odhapplications.yaml
Labels: lgtm, approved

#320 Removing the support for profiles from the code. Fixes #319
  apis/datasciencecluster/v1alpha1/datasciencecluster_types.go
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  components/component.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/modelmeshserving/modelmeshserving.go
  components/profiles/profiles.go
  components/workbenches/workbenches.go
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/utils.go
  docs/Dev-Preview.md
Labels: lgtm, approved

#323 Update networkpolicy to allow all traffic access applicationNamespace
  controllers/dscinitialization/utils.go
Labels: lgtm, approved

#325 Switching component's enabled property default value to false. Fixes #324
  controllers/datasciencecluster/datasciencecluster_controller.go
  docs/Dev-Preview.md
Labels: lgtm, approved

#326 Fix Reconcile Errors, manifests
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/additional/kfdef.apps.kubeflow.org_kfdefs.yaml
  config/additional/kustomization.yaml
  config/crd/kustomization.yaml
  config/default/kustomization.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/description-patch.yml
  config/manifests/kustomization.yaml
  config/samples/datasciencecluster_v1alpha1_datasciencecluster.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/utils.go
Labels: lgtm, approved

#327 Prepare for Dev Preview v0.0.5
  Makefile
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/utils.go
  docs/Dev-Preview.md
Labels: lgtm, approved

#337 Do not allow components to own applications Namespace
  pkg/deploy/deploy.go
Labels: lgtm, approved

#334 Adding refresh and retry logic in the DSCInitialization reconciliation loop #331
  controllers/dscinitialization/dscinitialization_controller.go
Labels: lgtm, approved

#348 Integrate Distributed Workloads
  apis/datasciencecluster/v1alpha1/datasciencecluster_types.go
  apis/datasciencecluster/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  components/distributedworkloads/distributedworkloads.go
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  pkg/deploy/deploy.go
Labels: lgtm, approved

#345 Switching default value for component's enabled property to false #324
  components/component.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/distributedworkloads/distributedworkloads.go
  components/kserve/kserve.go
  components/modelmeshserving/modelmeshserving.go
  components/workbenches/workbenches.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/utils.go
Labels: lgtm, approved

#329 Add samples back and remove kfdef from "owned" in CSV
  Makefile
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/kustomization.yaml
  config/samples/datasciencecluster_v1alpha1_datasciencecluster.yaml
  docs/Dev-Preview.md
Labels: lgtm, approved

#352 Add e2e test for operator
  Makefile
  README.md
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  components/component.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/distributedworkloads/distributedworkloads.go
  components/kserve/kserve.go
  components/modelmeshserving/modelmeshserving.go
  components/workbenches/workbenches.go
  config/manager/kustomization.yaml
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/monitoring.go
  go.mod
  pkg/deploy/deploy.go
  pkg/plugins/addLabelsplugin.go
  tests/e2e/controller_setup_test.go
  tests/e2e/dsc_creation_test.go
  tests/e2e/dsc_deletion_test.go
  tests/e2e/helper_test.go
  tests/e2e/odh_manager_test.go
Labels: lgtm

#354 Doc: remove $ from copy section
  docs/Dev-Preview.md
Labels: lgtm, approved

#330 Update description when create/config dsci and dsc
  apis/datasciencecluster/v1alpha1/datasciencecluster_types.go
  apis/dscinitialization/v1alpha1/dscinitialization_types.go
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  components/component.go
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#355 Update CSV description and design doc
  Dockerfiles/Dockerfile
  Makefile
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/description-patch.yml
  docs/DESIGN.md
Labels: lgtm, approved

#356 ODH Release bundle for v2.0.0
  Dockerfiles/Dockerfile
  Makefile
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#358 Update for ODH 1.8 Release
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#359 Improving conditions management. Fixes #351
  apis/dscinitialization/v1alpha1/dscinitialization_types.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/status/status.go
Labels: lgtm, approved

#367 Cherry-pick fix from odh-deployer
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  bundle/manifests/opendatahub.io_odhdashboardconfigs.yaml
  config/crd/bases/odhdashboardconfigs.opendatahub.io_odhdashboardconfigs.yaml
  config/samples/opendatahub_v1alpha1_odhdashboardconfigs.yaml
Labels: lgtm, approved

#361 Update: rbac group, kubebuilder, Owns order and add recorder
  apis/dscinitialization/v1alpha1/dscinitialization_types.go
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  components/kserve/kserve.go
  components/modelmeshserving/modelmeshserving.go
  components/workbenches/workbenches.go
  config/crd/bases/kfdef.apps.kubeflow.org_kfdefs.yaml
  config/rbac/role.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  main.go
Labels: approved, do-not-merge/hold

#346 Add apply manifests for dashboard ISV
  components/dashboard/dashboard.go
Labels: lgtm, approved

#375 Add support for image params for disconnected
  components/component.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/distributedworkloads/distributedworkloads.go
  components/kserve/kserve.go
  components/modelmeshserving/modelmeshserving.go
  components/workbenches/workbenches.go
  pkg/deploy/deploy.go
Labels: lgtm, approved

#344 Add creation for monitoring namespace when it is not the same as applications'
  controllers/dscinitialization/utils.go
Labels: lgtm, approved

#378 Fix isv deployments
  components/dashboard/dashboard.go
Labels: lgtm, approved

#382 Apply OVMS as part of dashboard manifests
  components/dashboard/dashboard.go
Labels: lgtm, approved

#377 Splitting distributed workflows component into codeflare and ray. Fixes #369
  README.md
  apis/datasciencecluster/v1alpha1/datasciencecluster_types.go
  apis/datasciencecluster/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  components/codeflare/codeflare.go
  components/distributedworkloads/distributedworkloads.go
  components/ray/ray.go
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/samples/datasciencecluster_v1alpha1_datasciencecluster.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  docs/DESIGN.md
  docs/Dev-Preview.md
  pkg/deploy/deploy.go
  tests/e2e/dsc_creation_test.go
  tests/e2e/dsc_deletion_test.go
  tests/e2e/helper_test.go
Labels: lgtm, approved

#390 Add ODHDashboardconfig in dasboard component
  components/dashboard/dashboard.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/monitoring.go
  controllers/dscinitialization/utils.go
  main.go
  pkg/common/common.go
  pkg/deploy/deploy.go
Labels: lgtm

#388 Fix: version number and add description
  apis/datasciencecluster/v1alpha1/datasciencecluster_types.go
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
Labels: lgtm, approved

#387 Remove dependency of deployment manifests on other components
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/status/status.go
Labels: lgtm, approved

#394 Fix: typo
  components/dashboard/dashboard.go
Labels: lgtm, approved

#395 Fix shared resources error
  go.mod
  go.sum
  pkg/deploy/deploy.go
  pkg/plugins/addLabelsplugin.go
Labels: lgtm, approved

#391 Add Kserve ImageParams Map
  components/kserve/kserve.go
Labels: lgtm, approved

#392 [Cherry-pick]: Deploy modelmesh in monitoring namespace
  components/modelmeshserving/modelmeshserving.go
Labels: lgtm, approved

#389 Add ImageParams for kuberay and codeflare
  components/codeflare/codeflare.go
  components/ray/ray.go
Labels: lgtm, approved
