Repository opendatahub-io/opendatahub-operator, pull requests merged in 2023-06, with the labels that each got.

#242 Initializing the DSCInitialization api.
  Dockerfile
  PROJECT
  apis/dscinitialization/v1alpha1/dscinitialization_types.go
  apis/dscinitialization/v1alpha1/groupversion_info.go
  apis/dscinitialization/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/crd/patches/cainjection_in_dscinitialization_dscinitializations.yaml
  config/crd/patches/webhook_in_dscinitialization_dscinitializations.yaml
  config/rbac/dscinitialization_dscinitialization_editor_role.yaml
  config/rbac/dscinitialization_dscinitialization_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/dscinitialization_v1alpha1_dscinitialization.yaml
  config/samples/kustomization.yaml
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/status.go
  controllers/dscinitialization/suite_test.go
  go.mod
  go.sum
  main.go
Labels: lgtm, approved, ok-to-test

#248 Adding DataScienceCluster API.
  PROJECT
  apis/datasciencecluster/v1alpha1/datasciencecluster_types.go
  apis/datasciencecluster/v1alpha1/groupversion_info.go
  apis/datasciencecluster/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_datasciencecluster_datascienceclusters.yaml
  config/crd/patches/webhook_in_datasciencecluster_datascienceclusters.yaml
  config/rbac/datasciencecluster_datasciencecluster_editor_role.yaml
  config/rbac/datasciencecluster_datasciencecluster_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/datasciencecluster_v1alpha1_datasciencecluster.yaml
  config/samples/kustomization.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/datasciencecluster/suite_test.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/status/status.go
  main.go
Labels: lgtm, approved, needs-ok-to-test

#262 Update: Dockerfile and Makefile
  Dockerfile
  Makefile
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  controllers/dscinitialization/dscinitialization_controller.go
Labels: lgtm, approved, needs-ok-to-test

#241 Update: GitHub Action for sync CRD from odh-dashboard
  .github/workflows/sync_dashboard_crds.yaml
Labels: lgtm, approved, ok-to-test

#202 Add local bundle for odh manifests
  .gitignore
  Dockerfile
  Makefile
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  tests/e2e/helper.go
Labels: lgtm, approved

#269 Updates for the ODH v1.7 release
  Dockerfile
  Makefile
Labels: lgtm, approved
