Repository opendatahub-io/opendatahub-operator, pull requests merged in 2023-10, with the labels that each got.

#584 fix: adds missing CRDs for k8s EnvTest
  Makefile
  config/crd/external/route.openshift.io_routes.yaml
  config/crd/external/user.openshift.io_groups.yaml
  config/crd/external/user.openshift.io_identities.yaml
  config/crd/external/user.openshift.io_useridentitymappings.yaml
  config/crd/external/user.openshift.io_users.yaml
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/dscinitialization_test.go
  controllers/dscinitialization/suite_test.go
  controllers/dscinitialization/utils.go
Labels: lgtm, approved, odh-1.11

#540 Linter: add golangci-linter and fix issues
  .github/workflows/linter.yaml
  .golangci.yml
  Makefile
  apis/datasciencecluster/v1/datasciencecluster_types.go
  apis/datasciencecluster/v1/groupversion_info.go
  apis/dscinitialization/v1/dscinitialization_types.go
  apis/dscinitialization/v1/groupversion_info.go
  components/codeflare/codeflare.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/modelmeshserving/modelmeshserving.go
  components/ray/ray.go
  components/workbenches/workbenches.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/datasciencecluster/suite_test.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/dscinitialization_test.go
  controllers/dscinitialization/monitoring.go
  controllers/dscinitialization/utils.go
  controllers/secretgenerator/secret.go
  controllers/secretgenerator/secretgenerator_controller.go
  controllers/status/status.go
  go.mod
  go.sum
  main.go
  pkg/common/common.go
  pkg/deploy/deploy.go
  pkg/deploy/setup.go
  pkg/plugins/addLabelsplugin.go
  pkg/plugins/namespacePlugin.go
  tests/e2e/controller_setup_test.go
  tests/e2e/dsc_creation_test.go
  tests/e2e/dsc_deletion_test.go
  tests/e2e/helper_test.go
Labels: rhods-1.35

#585 feat(manifests): allows configuring manifest repositories using flags
  Dockerfiles/Dockerfile
  README.md
  get_all_manifests.sh
Labels: lgtm, odh-1.11

#590 Feature: add networkpolicy in dsci
  controllers/dscinitialization/utils.go
Labels: lgtm, odh-1.11

#594 fix(crds): updates docs after godoc fixes
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
Labels: lgtm

#592 Enable test case after networkpolicy is added
  controllers/dscinitialization/dscinitialization_test.go
Labels: lgtm

#595 fix(make): removes duplicated e2e flag declaration
  Makefile
Labels: lgtm

#598 Update Dashboard branch in incubation
  get_all_manifests.sh
Labels: lgtm

#599 Remove gh action for sync dashboard CRD
  .github/workflows/sync_dashboard_crds.yaml
Labels: odh-1.11

#601 Auto Add Issues to Tracking boards
  .github/workflows/auto_add_issues.yaml
Labels: lgtm, approved

#583 Add check on components devFlags to overwrite applyimageparams
  components/codeflare/codeflare.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/modelmeshserving/modelmeshserving.go
  components/ray/ray.go
  components/workbenches/workbenches.go
Labels: approved

#596 feat: Add TrustyAI component
  apis/datasciencecluster/v1/datasciencecluster_types.go
  apis/datasciencecluster/v1/zz_generated.deepcopy.go
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  components/README.md
  components/trustyai/trustyai.go
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  config/samples/datasciencecluster_v1_datasciencecluster.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/datasciencecluster/kubebuilder_rbac.go
  get_all_manifests.sh
  tests/e2e/dsc_creation_test.go
  tests/e2e/dsc_deletion_test.go
  tests/e2e/helper_test.go
Labels: lgtm

#620 fix(bundle): trustyai is missing in bundle and syntax error in manifests
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#564 Add github workflows
  .github/workflows/unit-tests.yaml
  Makefile
Labels: lgtm, approved

#621 ODH Release 1.10.1
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  get_all_manifests.sh
Labels: lgtm

#627 Use catalogsource to identify managed Platform
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/datasciencecluster/kubebuilder_rbac.go
  pkg/deploy/setup.go
Labels: lgtm

#626 Sync main without incubating features
  .github/workflows/auto_add_issues.yaml
  .github/workflows/linter.yaml
  .github/workflows/sync_dashboard_crds.yaml
  .github/workflows/unit-tests.yaml
  .golangci.yml
  Dockerfiles/Dockerfile
  Makefile
  README.md
  apis/datasciencecluster/v1/datasciencecluster_types.go
  apis/datasciencecluster/v1/groupversion_info.go
  apis/dscinitialization/v1/dscinitialization_types.go
  apis/dscinitialization/v1/groupversion_info.go
  components/codeflare/codeflare.go
  components/component.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/modelmeshserving/modelmeshserving.go
  components/ray/ray.go
  components/workbenches/workbenches.go
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/crd/external/route.openshift.io_routes.yaml
  config/crd/external/user.openshift.io_groups.yaml
  config/crd/external/user.openshift.io_identities.yaml
  config/crd/external/user.openshift.io_useridentitymappings.yaml
  config/crd/external/user.openshift.io_users.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/datasciencecluster/suite_test.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/dscinitialization_test.go
  controllers/dscinitialization/monitoring.go
  controllers/dscinitialization/suite_test.go
  controllers/dscinitialization/utils.go
  controllers/secretgenerator/secret.go
  controllers/secretgenerator/secretgenerator_controller.go
  controllers/status/status.go
  get_all_manifests.sh
  go.mod
  go.sum
  main.go
  pkg/common/common.go
  pkg/deploy/deploy.go
  pkg/deploy/setup.go
  pkg/plugins/addLabelsplugin.go
  pkg/plugins/namespacePlugin.go
  tests/e2e/controller_setup_test.go
  tests/e2e/dsc_creation_test.go
  tests/e2e/dsc_deletion_test.go
  tests/e2e/helper_test.go
Labels: lgtm, approved

#619 feat(ray): pass down applicationNamespace to ray and codeflare in manifests
  components/codeflare/codeflare.go
  components/component.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/modelmeshserving/modelmeshserving.go
  components/ray/ray.go
  components/trustyai/trustyai.go
  components/workbenches/workbenches.go
  pkg/deploy/deploy.go
Labels: lgtm

#628 upgrade: go version from 18 to 19, net package to 0.17.0 to match new secrutiry requirement
  Dockerfiles/Dockerfile
  Dockerfiles/toolbox.Dockerfile
  Makefile
  go.mod
  go.sum
Labels: lgtm, approved, rhods-1.35, rhods-2.4

#651 Remove redundant TrustyAI reconciliation
  controllers/datasciencecluster/datasciencecluster_controller.go
Labels: lgtm

#649 fix(dashboard): consistant component name
  components/dashboard/dashboard.go
  get_all_manifests.sh
Labels: lgtm, approved

#650 add(api): shortname for CRD
  apis/datasciencecluster/v1/datasciencecluster_types.go
  apis/dscinitialization/v1/dscinitialization_types.go
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
Labels: lgtm, approved

#636 Add: test target depend on unit-test
  Makefile
Labels: lgtm, approved

#640 update(ray): new path to manifests
  components/ray/ray.go
  get_all_manifests.sh
Labels: lgtm, approved, odh-1.11

#652 update(cf): new path of manifests
  components/codeflare/codeflare.go
  get_all_manifests.sh
Labels: lgtm, approved, odh-1.11, rhods-2.4

#639 add manifests for odh-model-controller and model-mesh
  components/kserve/kserve.go
  components/modelmeshserving/modelmeshserving.go
  get_all_manifests.sh
Labels: lgtm, approved

#661 feat: adds finalizers to DSC and DSCI
  components/README.md
  components/component.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
Labels: lgtm

#665 Update TrustyAI Operator Variable
  components/trustyai/trustyai.go
Labels: lgtm, approved

#664 add: check for if KfDef CRD already in the cluster
  pkg/upgrade/upgrade.go
Labels: lgtm, approved

#547 Update reconcile interval to half minute
  controllers/datasciencecluster/datasciencecluster_controller.go
Labels: lgtm, approved

#674 fix: ensures cluster-wide resources are removed during test cleanup
  controllers/dscinitialization/dscinitialization_test.go
Labels: approved

#657 update(kserve): manifests path from in-repo
  components/kserve/kserve.go
  get_all_manifests.sh
Labels: odh-1.11

#679 backport(2.4): add permission related to monitoring and missing label on namespaces
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/datasciencecluster/kubebuilder_rbac.go
  controllers/dscinitialization/utils.go
Labels: lgtm

#683 chore(script): removes unused vars
  README.md
  get_all_manifests.sh
Labels: lgtm
