Repository opendatahub-io/opendatahub-operator, pull requests merged in 2023-11, with the labels that each got.

#690 [main] cherrypick: TrustyAI from incubation
  apis/datasciencecluster/v1/datasciencecluster_types.go
  apis/datasciencecluster/v1/zz_generated.deepcopy.go
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  components/README.md
  components/codeflare/codeflare.go
  components/component.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/modelmeshserving/modelmeshserving.go
  components/ray/ray.go
  components/trustyai/trustyai.go
  components/workbenches/workbenches.go
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  config/samples/datasciencecluster_v1_datasciencecluster.yaml
  controllers/datasciencecluster/kubebuilder_rbac.go
  get_all_manifests.sh
  pkg/deploy/deploy.go
  tests/e2e/dsc_creation_test.go
  tests/e2e/dsc_deletion_test.go
  tests/e2e/helper_test.go
Labels: lgtm

#660 remove: req.namespace is not used for DSC and DSCI
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
Labels: lgtm, odh-2.4

#676 feat(linter): introduces gci to streamline import rules
  .golangci.yml
  apis/datasciencecluster/v1/datasciencecluster_types.go
  components/codeflare/codeflare.go
  components/component.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/modelmeshserving/modelmeshserving.go
  components/ray/ray.go
  components/trustyai/trustyai.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/datasciencecluster/suite_test.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/dscinitialization_test.go
  controllers/dscinitialization/monitoring.go
  controllers/dscinitialization/suite_test.go
  controllers/dscinitialization/utils.go
  main.go
  pkg/cluster/operations.go
  pkg/common/k8s_naming_test.go
  pkg/deploy/deploy.go
  pkg/feature/builder.go
  pkg/feature/cert.go
  pkg/feature/conditions.go
  pkg/feature/feature.go
  pkg/feature/initializer.go
  pkg/feature/manifest.go
  pkg/feature/raw_resources.go
  pkg/feature/resources.go
  pkg/feature/types.go
  pkg/upgrade/upgrade.go
  tests/e2e/controller_setup_test.go
  tests/e2e/dsc_creation_test.go
  tests/e2e/dsc_deletion_test.go
  tests/e2e/helper_test.go
  tests/integration/features/features_int_test.go
  tests/integration/features/features_suite_int_test.go
  tools.go
Labels: lgtm

#689 chore(gh): ensures unit-test action uses go.mod for Go version
  .github/workflows/unit-tests.yaml
Labels: odh-2.4

#663 backport(workbench): support images in two path for downstream
  components/workbenches/workbenches.go
Labels: rhods-2.4, odh-2.4

#695 fix(make): ensures projects version of operator-sdk is used
  Dockerfiles/bundle.Dockerfile
  Makefile
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
Labels: lgtm, odh-2.4

#687 Report error in status if more than one DataScienceCluster installed
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/status/status.go
Labels: lgtm, odh-2.4

#703 cleanup: modelmesh monitoring logic
  components/modelmeshserving/modelmeshserving.go
  controllers/dscinitialization/utils.go
  get_all_manifests.sh
Labels: lgtm, approved

#704 release: uplift from alpha to stable and set 2.4 version
  Makefile
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#618 [cherry-pick] Add logic for applying monitoring stack
  apis/dscinitialization/v1/dscinitialization_types.go
  bundle/manifests/opendatahub-operator-controller-manager-metrics-service_v1_service.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  components/codeflare/codeflare.go
  components/component.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/modelmeshserving/modelmeshserving.go
  components/ray/ray.go
  components/trustyai/trustyai.go
  components/workbenches/workbenches.go
  config/manager/manager.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/role.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/datasciencecluster/kubebuilder_rbac.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/dscinitialization_test.go
  controllers/dscinitialization/monitoring.go
  controllers/dscinitialization/suite_test.go
  controllers/dscinitialization/utils.go
  controllers/secretgenerator/secretgenerator_controller.go
  go.mod
  go.sum
  main.go
  pkg/cluster/operations.go
  pkg/common/common.go
  pkg/deploy/deploy.go
  pkg/deploy/setup.go
  pkg/feature/conditions.go
  pkg/feature/feature.go
  pkg/feature/manifest.go
  pkg/feature/raw_resources.go
  pkg/upgrade/upgrade.go
  tests/e2e/controller_setup_test.go
  tests/e2e/dsc_creation_test.go
  tests/e2e/dsc_deletion_test.go
  tests/e2e/helper_test.go
  tests/envtestutil/cleaner.go
  tests/envtestutil/name_gen.go
  tests/integration/features/features_int_test.go
  tests/integration/features/features_suite_int_test.go
Labels: odh-2.5

#715 chore: fixes typos in func names
  controllers/dscinitialization/dscinitialization_controller.go
Labels: lgtm

#708 Unset Tech Preview components by default
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/samples/console_v1_odhquickstarts.yaml
  config/samples/dashboard_v1_odhapplications.yaml
  config/samples/dashboard_v1_odhdocuments.yaml
  config/samples/datasciencecluster_v1_datasciencecluster.yaml
  config/samples/dscinitialization_v1_dscinitialization.yaml
  config/samples/kustomization.yaml
  config/samples/opendatahub_v1alpha1_odhdashboardconfigs.yaml
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/dscinitialization_test.go
  main.go
  pkg/upgrade/upgrade.go
  tests/e2e/controller_setup_test.go
Labels: lgtm, approved, rhods-2.4, odh-2.4

#721 Update README.md
  README.md
Labels: lgtm

#722 chore(log): accurate message
  pkg/feature/feature.go
Labels: lgtm, approved

#725 fix(crd): do not set ownerreference on CRD
  pkg/deploy/deploy.go
Labels: lgtm, approved

#716 Recreate stale OauthClient resource
  components/codeflare/codeflare.go
  components/component.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/modelmeshserving/modelmeshserving.go
  components/ray/ray.go
  components/trustyai/trustyai.go
  components/workbenches/workbenches.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/secretgenerator/secretgenerator_controller.go
  main.go
  pkg/upgrade/upgrade.go
Labels: rhods-2.4

#669 Add missing resources to manage in DSC controller
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/datasciencecluster/kubebuilder_rbac.go
  go.mod
  go.sum
  main.go
Labels: approved, rhods-2.5

#738 fix(ossm): disables service mesh routes generation
  pkg/feature/templates/servicemesh/base/smcp.tmpl
Labels: lgtm, rhods-2.5

#740 fix(codegen): ensures structs used in CRDs have deepcopy funcs
  apis/datasciencecluster/v1/zz_generated.deepcopy.go
  apis/dscinitialization/v1/zz_generated.deepcopy.go
  apis/features/v1/zz_generated.deepcopy.go
  components/codeflare/codeflare.go
  components/codeflare/zz_generated.deepcopy.go
  components/component.go
  components/dashboard/dashboard.go
  components/dashboard/zz_generated.deepcopy.go
  components/datasciencepipelines/datasciencepipelines.go
  components/datasciencepipelines/zz_generated.deepcopy.go
  components/kserve/kserve.go
  components/kserve/zz_generated.deepcopy.go
  components/modelmeshserving/modelmeshserving.go
  components/modelmeshserving/zz_generated.deepcopy.go
  components/ray/ray.go
  components/ray/zz_generated.deepcopy.go
  components/trustyai/trustyai.go
  components/trustyai/zz_generated.deepcopy.go
  components/workbenches/workbenches.go
  components/workbenches/zz_generated.deepcopy.go
  components/zz_generated.deepcopy.go
  infrastructure/v1/doc.go
  infrastructure/v1/zz_generated.deepcopy.go
Labels: lgtm

#742 Update codeflare component description
  apis/datasciencecluster/v1/datasciencecluster_types.go
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/samples/featuretracker_v1_features.yaml
Labels: lgtm, needs-ok-to-test

#743 fix(ns): do not set owner ref for infra namespaces
  components/kserve/serverless_setup.go
  components/workbenches/workbenches.go
  controllers/dscinitialization/servicemesh_setup.go
  controllers/dscinitialization/utils.go
  pkg/cluster/operations.go
  pkg/feature/resources.go
  pkg/upgrade/upgrade.go
  tests/integration/cluster_operations/cluster_operations_int_test.go
  tests/integration/cluster_operations/cluster_operations_suite_int_test.go
  tests/integration/features/features_int_test.go
Labels: lgtm

#744 fix(kserve): check on multiple depends operators if all pre-installed
  components/kserve/kserve.go
  pkg/feature/feature.go
  pkg/feature/initializer.go
Labels: rhods-2.5

#748 fix(cleanup): cleans up dependant resources
  controllers/datasciencecluster/datasciencecluster_controller.go
  pkg/upgrade/upgrade.go
  tests/e2e/controller_setup_test.go
  tests/e2e/dsc_cfmap_deletion_test.go
  tests/e2e/dsc_deletion_test.go
Labels: lgtm

#762 chore: removes log repetitions for conditions
  pkg/feature/conditions.go
Labels: lgtm, rhods-2.5

#761 update(knative): enable GPU node tolerations for kserve
  pkg/feature/templates/serverless/serving-install/knative-serving.tmpl
Labels: lgtm, approved, rhods-2.5

#760 fix(features): makes rest config loader more flexible
  pkg/feature/builder.go
Labels: lgtm, approved
