Repository opendatahub-io/opendatahub-operator, pull requests merged in 2024-12, with the labels that each got.

#1410 Make it possible to define predicates along with a dynamic watcher
  pkg/controller/reconciler/component_reconciler_actions.go
  pkg/controller/reconciler/component_reconciler_actions_test.go
  pkg/controller/reconciler/component_reconciler_support.go
Labels: lgtm, approved, feature-operator-refactor

#1407 Add special handling for Aggregatin ClusterRole
  pkg/controller/actions/deploy/action_deploy.go
  pkg/controller/actions/deploy/action_deploy_test.go
Labels: lgtm, approved, feature-operator-refactor

#1405 [Sync]: incubation to rhoai
  Dockerfiles/Dockerfile
  Makefile
  OWNERS_ALIASES
  README.md
Labels: lgtm, approved, rhoai

#1408 doc: remove -e from make invocation examples
  README.md
Labels: lgtm, approved

#1414 Add an option to set the deployment action cache TTL
  pkg/controller/actions/deploy/action_deploy.go
  pkg/controller/actions/deploy/action_deploy_cache.go
  pkg/controller/actions/deploy/action_deploy_cache_test.go
Labels: lgtm, approved, feature-operator-refactor

#1415 fix: RHOAIENG-16229 - Renaming Alerts
  config/monitoring/prometheus/apps/prometheus-configs.yaml
Labels: lgtm, approved

#1417 (fix): Avoid using pull_request_target event trigger.
  .github/workflows/check-file-updates.yaml
  .github/workflows/comment-on-pr.yaml
Labels: lgtm

#1420 feat: add NIM flag in Operator
  README.md
  apis/components/v1alpha1/kserve_types.go
  apis/components/v1alpha1/modelcontroller_types.go
  apis/components/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/components.platform.opendatahub.io_kserves.yaml
  bundle/manifests/components.platform.opendatahub.io_modelcontrollers.yaml
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/crd/bases/components.platform.opendatahub.io_kserves.yaml
  config/crd/bases/components.platform.opendatahub.io_modelcontrollers.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/samples/datasciencecluster_v1_datasciencecluster.yaml
  controllers/components/kserve/kserve.go
  controllers/components/modelcontroller/modelcontroller.go
  controllers/components/modelcontroller/modelcontroller_actions.go
  docs/api-overview.md
  get_all_manifests.sh
Labels: lgtm, feature-operator-refactor

#1418 Add custom CRD deployment logic
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/components/codeflare/codeflare_controller.go
  controllers/components/dashboard/dashboard_controller.go
  controllers/components/datasciencepipelines/datasciencepipelines.go
  controllers/components/datasciencepipelines/datasciencepipelines_controller.go
  controllers/components/kserve/kserve_controller.go
  controllers/components/kueue/kueue_controller.go
  controllers/components/modelregistry/modelregistry_controller.go
  controllers/components/ray/ray_controller.go
  controllers/components/trainingoperator/trainingoperator_controller.go
  controllers/components/trustyai/trustyai_controller.go
  controllers/components/workbenches/workbenches_controller.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/datasciencecluster/kubebuilder_rbac.go
  pkg/controller/actions/deploy/action_deploy.go
  pkg/controller/actions/deploy/action_deploy_cache.go
  pkg/controller/actions/deploy/action_deploy_test.go
  pkg/controller/predicates/component/component.go
  pkg/metadata/labels/types.go
  pkg/resources/resources.go
  pkg/resources/resources_test.go
  tests/e2e/controller_test.go
  tests/e2e/dashboard_test.go
  tests/e2e/modelregistry_test.go
Labels: lgtm, approved, feature-operator-refactor

#1426 update: remove cache for deployment in modelreg namespace
  main.go
Labels: approved

#1432 Fix linters
  .github/workflows/linter.yaml
  Makefile
  controllers/dscinitialization/suite_test.go
  controllers/webhook/webhook_suite_test.go
Labels: lgtm, approved, feature-operator-refactor

#1429 A reconciler should not require the DSCI to perform cleanup action to avoid deadlock
  controllers/dscinitialization/suite_test.go
  controllers/webhook/webhook_suite_test.go
  pkg/controller/reconciler/reconciler.go
Labels: lgtm, approved, feature-operator-refactor

#1435 Refactor modelcontroller DevFlags handling
  apis/components/v1alpha1/modelcontroller_types.go
  bundle/manifests/components.platform.opendatahub.io_modelcontrollers.yaml
  config/crd/bases/components.platform.opendatahub.io_modelcontrollers.yaml
  controllers/components/modelcontroller/modelcontroller_actions.go
  docs/api-overview.md
  pkg/resources/resources.go
Labels: lgtm, approved, feature-operator-refactor, odh-2.22

#1433 Remove old component interface
  Dockerfiles/Dockerfile
  apis/datasciencecluster/v1/datasciencecluster_types.go
  components/zz_generated.deepcopy.go
  docs/api-overview.md
  pkg/services/monitoring/prometheus.go
Labels: lgtm, approved, feature-operator-refactor, odh-2.22

#1424 Update Dockerfiles to Go 1.22 (Go 1.22: 1/3)
  Dockerfiles/Dockerfile
  Dockerfiles/toolbox.Dockerfile
  Makefile
Labels: lgtm, approved

#1442 Specify full x.y.z version of Go in go.mod
  go.mod
Labels: lgtm, approved

#1436 Refactor DownloadManifests in deploy for clarity and modularity
  .golangci.yml
  pkg/deploy/deploy.go
Labels: lgtm, approved

#1444 Removed IMAGE_OWNER from README.md.
  README.md
Labels: lgtm, approved

#1449 Fix manifests paths across components
  controllers/components/codeflare/codeflare.go
  controllers/components/codeflare/codeflare_controller_actions.go
  controllers/components/codeflare/codeflare_support.go
  controllers/components/datasciencepipelines/datasciencepipelines.go
  controllers/components/datasciencepipelines/datasciencepipelines_controller.go
  controllers/components/datasciencepipelines/datasciencepipelines_controller_actions.go
  controllers/components/datasciencepipelines/datasciencepipelines_support.go
  controllers/components/kserve/kserve.go
  controllers/components/kserve/kserve_controller.go
  controllers/components/kserve/kserve_support.go
  controllers/components/kueue/kueue.go
  controllers/components/kueue/kueue_controller_actions.go
  controllers/components/kueue/kueue_support.go
  controllers/components/modelcontroller/modelcontroller.go
  controllers/components/modelcontroller/modelcontroller_actions.go
  controllers/components/modelcontroller/modelcontroller_support.go
  controllers/components/modelmeshserving/modelmeshserving.go
  controllers/components/modelmeshserving/modelmeshserving_actions.go
  controllers/components/modelmeshserving/modelmeshserving_support.go
  controllers/components/ray/ray.go
  controllers/components/ray/ray_controller_actions.go
  controllers/components/ray/ray_support.go
  controllers/components/trainingoperator/trainingoperator.go
  controllers/components/trainingoperator/trainingoperator_controller_actions.go
  controllers/components/trainingoperator/trainingoperator_support.go
  controllers/components/trustyai/trustyai.go
  controllers/components/trustyai/trustyai_controller_actions.go
  controllers/components/trustyai/trustyai_support.go
  pkg/controller/types/types.go
Labels: lgtm, approved, feature-operator-refactor

#1454 chore: fixed typo in the logs
  pkg/upgrade/upgrade.go
Labels: lgtm, approved, ok-to-test

#1453 Remove WithDevFlags interface from PlatformObject since not every entity supports dev flags
  apis/common/types.go
  pkg/controller/actions/render/kustomize/action_render_manifests.go
  pkg/controller/actions/render/template/action_render_templates.go
Labels: lgtm, approved, feature-operator-refactor

#1438 Migration uninstall configmap from DSC to setup controller
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/datasciencecluster/kubebuilder_rbac.go
  controllers/setupcontroller/setup_controller.go
  main.go
  pkg/upgrade/uninstallation.go
Labels: lgtm, approved

#1457 fix: bug not filling params.env with default cert value in model registry operator
  controllers/components/modelregistry/modelregistry.go
Labels: lgtm, approved

#1448 (fix): change gha to target main
  .github/workflows/pre-release.yaml
Labels: lgtm, approved

#1461 Use both current and legacy component name to filter out DevFlags
  controllers/components/kserve/kserve_controller_actions.go
  controllers/components/modelcontroller/modelcontroller_actions.go
  controllers/components/modelmeshserving/modelmeshserving_actions.go
Labels: lgtm, approved, feature-operator-refactor

#1451 Make DSC's component conditions user friendly
  controllers/components/codeflare/codeflare.go
  controllers/components/codeflare/codeflare_support.go
  controllers/components/dashboard/dashboard.go
  controllers/components/dashboard/dashboard_support.go
  controllers/components/datasciencepipelines/datasciencepipelines.go
  controllers/components/datasciencepipelines/datasciencepipelines_support.go
  controllers/components/kserve/kserve.go
  controllers/components/kueue/kueue.go
  controllers/components/kueue/kueue_support.go
  controllers/components/modelcontroller/modelcontroller.go
  controllers/components/modelcontroller/modelcontroller_support.go
  controllers/components/modelmeshserving/modelmeshserving.go
  controllers/components/modelmeshserving/modelmeshserving_support.go
  controllers/components/modelregistry/modelregistry.go
  controllers/components/modelregistry/modelregistry_support.go
  controllers/components/ray/ray.go
  controllers/components/ray/ray_support.go
  controllers/components/trainingoperator/trainingoperator.go
  controllers/components/trainingoperator/trainingoperator_support.go
  controllers/components/trustyai/trustyai.go
  controllers/components/trustyai/trustyai_support.go
  controllers/components/workbenches/workbenches.go
  controllers/components/workbenches/workbenches_support.go
  pkg/cluster/gvk/gvk.go
  tests/e2e/codeflare_test.go
  tests/e2e/dashboard_test.go
  tests/e2e/datasciencepipelines_test.go
  tests/e2e/kserve_test.go
  tests/e2e/kueue_test.go
  tests/e2e/modelcontroller_test.go
  tests/e2e/modelmeshserving_test.go
  tests/e2e/modelregistry_test.go
  tests/e2e/ray_test.go
  tests/e2e/trainingoperator_test.go
  tests/e2e/trustyai_test.go
  tests/e2e/workbenches_test.go
Labels: lgtm, approved, feature-operator-refactor

#1463 Update golang.org/x/net to v0.33.0
  go.mod
  go.sum
Labels: lgtm, approved

#1464 Remove useless e2e sleep time
  tests/e2e/codeflare_test.go
  tests/e2e/datasciencepipelines_test.go
  tests/e2e/helper_test.go
  tests/e2e/kueue_test.go
  tests/e2e/ray_test.go
  tests/e2e/trainingoperator_test.go
  tests/e2e/trustyai_test.go
  tests/e2e/workbenches_test.go
Labels: lgtm, approved
