Repository opendatahub-io/opendatahub-operator, pull requests merged in 2024-03, with the labels that each got.

#858 chore: follow up review comments from previous PR
  pkg/deploy/deploy.go
  pkg/deploy/setup.go
  pkg/upgrade/upgrade.go
  tests/e2e/dsc_cfmap_deletion_test.go
Labels: lgtm

#892 fix(authz): Fix broken external auth configuration
  pkg/feature/templates/servicemesh/authorino/mesh-authz-ext-provider.patch.tmpl
  pkg/feature/templates/servicemesh/kserve/z-fix-jira-4192/kserve-predictor-authorizationpolicy.patch.tmpl
Labels: lgtm, approved, odh-2.9

#897 chore: removes SetImageParamsMap from ComponentInterface
  components/README.md
  components/codeflare/codeflare.go
  components/component.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/kueue/kueue.go
  components/modelmeshserving/modelmeshserving.go
  components/modelregistry/modelregistry.go
  components/ray/ray.go
  components/trustyai/trustyai.go
  components/workbenches/workbenches.go
Labels: lgtm, approved, odh-2.9

#902 fix: cleans up conditions of FeatureTracker
  apis/features/v1/features_types.go
  pkg/feature/feature.go
Labels: lgtm, approved

#871 feat(cleanup): remove jupyterhub CR from previous release
  main.go
  pkg/upgrade/upgrade.go
Labels: lgtm, approved, odh-2.9

#893 [backport](dashboard): to work with new struct from dashboard
  components/dashboard/dashboard.go
Labels: lgtm, approved, odh-2.9

#886 DSC: make a method from getAllComponents
  apis/datasciencecluster/v1/datasciencecluster_types.go
  controllers/datasciencecluster/datasciencecluster_controller.go
Labels: lgtm, approved, odh-2.9

#884 feat(dashboard): add consolelink for ODH
  components/dashboard/dashboard.go
Labels: approved, odh-2.9

#898 chore: simpliflies handling of k8s not-found errors
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  controllers/dscinitialization/utils.go
  controllers/secretgenerator/secretgenerator_controller.go
  pkg/deploy/setup.go
  pkg/trustedcabundle/trustedcabundle.go
Labels: lgtm, approved, odh-2.9

#891 feat(dspv2): update manifests path for new overlay struct
  components/datasciencepipelines/datasciencepipelines.go
Labels: lgtm, approved, odh-2.9

#904 feat: add additional auth_refs for global config
  pkg/feature/servicemesh/resources.go
Labels: lgtm, approved, odh-2.9

#900 fix(trustbundle): do not use namespace which is in termination status
  pkg/trustedcabundle/trustedcabundle.go
Labels: lgtm, approved, odh-2.9

#903 chore(feature): passes component name instead of whole struct
  components/kserve/kserve_config_handler.go
  components/kserve/servicemesh_setup.go
  pkg/feature/handler.go
  tests/integration/features/serverless_feature_test.go
Labels: lgtm, approved, odh-2.9

#905 fix(authz): ensures extauthz provider is removed from control plane during cleanup
  components/kserve/servicemesh_setup.go
  pkg/feature/servicemesh/cleanup.go
  pkg/feature/templates/servicemesh/kserve/z-migrations/kserve-predictor-authorizationpolicy.patch.tmpl
  tests/integration/features/features_suite_int_test.go
  tests/integration/features/servicemesh_feature_test.go
Labels: approved, odh-2.9

#910 chore: renames base manifest type
  pkg/feature/feature.go
  pkg/feature/manifest.go
  pkg/feature/manifest_test.go
Labels: lgtm, approved

#889 feat(dspv2): add new images holder in DSPipeline
  components/datasciencepipelines/datasciencepipelines.go
Labels: lgtm, approved

#907 fix(make): adds entire pkg/... to run tests
  Makefile
Labels: lgtm, approved

#911 ODH Release 2.9: Version Update
  Makefile
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#888 manifests: add grpconly label to apply global EnvoyFilter
  components/kserve/servicemesh_setup.go
  pkg/feature/templates/servicemesh/kserve/grpc-envoyfilter-temp-fix.tmpl
Labels: lgtm, approved, odh-2.9

#913 chore: trustcabundle
  controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  pkg/trustedcabundle/trustedcabundle.go
Labels: lgtm, approved

#914 Fix cleanup of ODHApplications
  pkg/upgrade/upgrade.go
Labels: lgtm, approved

#909 chore: moves config map creation logic from Feature pkg
  controllers/dscinitialization/servicemesh_setup.go
  pkg/cluster/cluster_operations_int_test.go
  pkg/cluster/cluster_operations_suite_int_test.go
  pkg/cluster/meta.go
  pkg/cluster/resources.go
  pkg/feature/feature.go
  pkg/feature/servicemesh/resources.go
Labels: lgtm

#916 feat(tmpl): fails when key does not exist
  pkg/feature/manifest.go
  pkg/feature/manifest_test.go
Labels: lgtm

#920 fix(gen): upgrades to crd-ref-doc generator to latest version
  .github/workflows/check-file-updates.yaml
  Makefile
  docs/api-overview.md
Labels: lgtm, approved

#906 chore: move testing fixtures to fixtures directory
  tests/integration/features/features_int_test.go
  tests/integration/features/features_suite_int_test.go
  tests/integration/features/fixtures/cluster_test_fixtures.go
  tests/integration/features/fixtures/crd/istio-gateway.crd.yaml
  tests/integration/features/fixtures/crd/openshift-ingresses.crd.yaml
  tests/integration/features/fixtures/crd/subscription.crd.yaml
  tests/integration/features/fixtures/crd/test-resource.crd.yaml
  tests/integration/features/fixtures/file_sys_fixtures.go
  tests/integration/features/fixtures/templates/fake-kust-dir/kustomization.yaml
  tests/integration/features/fixtures/templates/fake-kust-dir/resource.yaml
  tests/integration/features/fixtures/templates/namespace.yaml
  tests/integration/features/serverless_feature_test.go
  tests/integration/features/servicemesh_feature_test.go
Labels: lgtm, approved, refactoring

#922 fix(make): cleans linter cache on clean
  Makefile
Labels: lgtm, approved

#925 feat(build): adds gci to go fmt target
  .gitignore
  .golangci.yml
  Makefile
Labels: approved

#838 chore(Github): update issue template re-direct user for jira
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_reportv2.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/auto_add_issues.yaml
Labels: lgtm, approved, incubating

#923 fix(dashboard): do not set owner on CR
  pkg/deploy/deploy.go
  pkg/upgrade/upgrade.go
Labels: lgtm, approved, odh-2.10

#926 (fix): Description patch during make bundle
  config/manifests/kustomization.yaml
Labels: lgtm, approved, odh-2.10

#928 chore: Small Makefile fixes
  Makefile
Labels: lgtm, approved, incubating

#929 feat(DW): prepare CF,ray,kueue for GA
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/samples/datasciencecluster_v1_datasciencecluster.yaml
  pkg/upgrade/upgrade.go
  tests/e2e/helper_test.go
Labels: lgtm, approved, odh-2.10

#934 fix(test): pin version not latest which just introduced to use go 1.22
  Makefile
Labels: lgtm, approved

#937 chore: removes unused statuses
  controllers/status/status.go
Labels: lgtm, approved

#935 chore: remove kustomizationManifest + tests
  pkg/feature/manifest.go
  pkg/feature/manifest_test.go
  tests/integration/features/manifests_int_test.go
Labels: lgtm

#938 fix(dashboard): add app for ODH base to deploy
  components/dashboard/dashboard.go
Labels: lgtm, approved

#940 Changed ODH/Kuberay to point to dev branch
  get_all_manifests.sh
Labels: lgtm, approved

#901 update: set the branch of each component to match odh nightly
  get_all_manifests.sh
Labels: do-not-merge/hold, incubating, odh-2.10

#939 chore: split upgrade.go into 3 files
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/monitoring.go
  controllers/dscinitialization/utils.go
  pkg/cluster/cluster_config.go
  pkg/upgrade/uninstallation.go
  pkg/upgrade/upgrade.go
Labels: lgtm

#941 chore(labels): introduces structured types for labels
  components/kserve/kserve_config_handler.go
  components/workbenches/workbenches.go
  controllers/dscinitialization/utils.go
  pkg/cluster/cluster_operations_int_test.go
  pkg/cluster/resources.go
  pkg/deploy/deploy.go
  pkg/metadata/labels/types.go
  pkg/monitoring/monitoring.go
  pkg/plugins/addLabelsplugin.go
  pkg/trustedcabundle/trustedcabundle.go
  pkg/upgrade/uninstallation.go
  pkg/upgrade/upgrade.go
  tests/e2e/dsc_cfmap_deletion_test.go
Labels: lgtm, approved

#942 update branch of odh-model-controller for nightly build
  get_all_manifests.sh
Labels: lgtm, approved

#945 Fix update on trustedcabundle
  pkg/trustedcabundle/trustedcabundle.go
Labels: lgtm, approved, odh-2.10
