Repository opendatahub-io/opendatahub-operator, pull requests merged in 2024-06, with the labels that each got.

#953 feat(mr): add cluster roles for model registry administration, fixes RHOAIENG-5112
  components/modelregistry/modelregistry.go
Labels: lgtm, approved

#1031 feat: increase QPS and Burst for client
  main.go
Labels: lgtm, approved

#1033 chore: Open up util functions for context propagation
  components/dashboard/dashboard.go
  components/kserve/kserve.go
  components/modelmeshserving/modelmeshserving.go
  components/modelregistry/modelregistry.go
  components/workbenches/workbenches.go
  controllers/dscinitialization/monitoring.go
  pkg/cluster/cluster_operations_int_test.go
  pkg/cluster/resources.go
  pkg/feature/resources.go
  pkg/feature/servicemesh/conditions.go
  pkg/feature/servicemesh/resources.go
  tests/integration/features/manifests_int_test.go
  tests/integration/features/resources_int_test.go
Labels: lgtm, approved

#1034 Update version 2.13
  Dockerfiles/bundle.Dockerfile
  Makefile
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#1038 fix: missing label "opendatahub.io/generated-namespace" on auth namespace
  pkg/feature/servicemesh/conditions.go
Labels: lgtm

#1039 chore: append ownerRef to resources owned by Features
  pkg/cluster/cluster_operations_int_test.go
  pkg/cluster/meta.go
  pkg/feature/feature.go
  pkg/feature/servicemesh/conditions.go
  pkg/feature/servicemesh/resources.go
Labels: lgtm, approved

#1043 add: get permission on resources
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/datasciencecluster/kubebuilder_rbac.go
Labels: lgtm, approved

#1044 fix: when delete resource if no CRD in the cluster
  pkg/deploy/deploy.go
Labels: lgtm, approved

#1040 Update Owners-aliases list
  OWNERS
  OWNERS_ALIASES
Labels: lgtm, approved

#1046 deploy: refactor getResource to return NotFound for both cases
  pkg/deploy/deploy.go
Labels: lgtm, approved

#1042 RHOAIENG-5426: Updated pull request template with prerequisites
  .github/PULL_REQUEST_TEMPLATE.md
Labels: lgtm, approved

#1050 chore: renames manifests source to location
  components/kserve/feature_resources.go
  components/kserve/serverless_setup.go
  components/kserve/servicemesh_setup.go
  controllers/dscinitialization/feature_resources.go
  controllers/dscinitialization/servicemesh_setup.go
  pkg/feature/builder.go
  tests/integration/features/manifests_int_test.go
  tests/integration/features/resources_int_test.go
  tests/integration/features/servicemesh_feature_test.go
Labels: lgtm, approved

#1041 Dsc creation postpone
  main.go
  pkg/upgrade/upgrade.go
Labels: lgtm, approved

#1051 cluster: GetPlatform: replace CSV list with OperatorExists calls
  config/crd/external/operators.coreos.com_operatorconditions.yaml
  controllers/dscinitialization/suite_test.go
  pkg/cluster/cluster_config.go
Labels: lgtm, approved

#1054 cluster: platform name cleanup
  pkg/cluster/cluster_config.go
  pkg/cluster/const.go
Labels: lgtm, approved

#1055 chore: remove duplicated GetPlatform call in each component
  components/codeflare/codeflare.go
  components/component.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/kueue/kueue.go
  components/modelmeshserving/modelmeshserving.go
  components/modelregistry/modelregistry.go
  components/ray/ray.go
  components/trainingoperator/trainingoperator.go
  components/trustyai/trustyai.go
  components/workbenches/workbenches.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  go.mod
Labels: approved

#1060 chore: fix remove trailing slash from GITHUB_URL
  get_all_manifests.sh
Labels: lgtm, approved, ok-to-test

#1061 chore: update toolbox sdk version and remove duplicated AddToScheme
  Dockerfiles/toolbox.Dockerfile
  Makefile
  bundle/tests/scorecard/config.yaml
  config/scorecard/patches/basic.config.yaml
  main.go
Labels: lgtm, approved

#1062 chore: funcs to create kustomize plugins
  pkg/deploy/deploy.go
  pkg/plugins/addLabelsplugin.go
  pkg/plugins/namespacePlugin.go
Labels: lgtm, approved

#1064 feat: upgrade go from 1.20 to 1.21
  .ci-operator.yaml
  Dockerfiles/Dockerfile
  Dockerfiles/toolbox.Dockerfile
  Makefile
  README.md
  go.mod
  go.sum
Labels: lgtm, approved

#1022 Add support for default Ingress Cert
  README.md
  apis/infrastructure/v1/cert_types.go
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/rbac/role.yaml
  config/samples/datasciencecluster_v1_datasciencecluster.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/datasciencecluster/kubebuilder_rbac.go
  docs/api-overview.md
  main.go
  pkg/cluster/cert.go
  pkg/feature/cert.go
  pkg/feature/serverless/loaders.go
  pkg/feature/serverless/resources.go
  tests/e2e/controller_setup_test.go
  tests/e2e/dsc_creation_test.go
  tests/e2e/helper_test.go
  tests/integration/features/serverless_feature_test.go
Labels: lgtm, approved, rhoai-2.11

#1067 fix: makes default knative secret local for serverless
  pkg/cluster/cert.go
  pkg/feature/serverless/loaders.go
  pkg/feature/serverless/resources.go
  tests/e2e/dsc_creation_test.go
  tests/integration/features/serverless_feature_test.go
Labels: lgtm, approved

#1063 chore: improves PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: lgtm, approved

#885 fix(DSCI): change serviceMesh and trustCAbundle to pointer type
  apis/dscinitialization/v1/dscinitialization_types.go
  apis/dscinitialization/v1/zz_generated.deepcopy.go
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  components/kserve/kserve.go
  components/kserve/servicemesh_setup.go
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go
  controllers/dscinitialization/dscinitialization_test.go
  controllers/dscinitialization/servicemesh_setup.go
  controllers/webhook/webhook_suite_test.go
  docs/api-overview.md
  pkg/feature/builder.go
  pkg/trustedcabundle/trustedcabundle.go
  pkg/upgrade/upgrade.go
  tests/e2e/dsc_creation_test.go
  tests/e2e/helper_test.go
  tests/integration/features/fixtures/cluster_test_fixtures.go
  tests/integration/features/servicemesh_feature_test.go
Labels: lgtm, incubating, odh-2.13

#1071 chore: moves ArgoCD conditions to pipelines component
  components/datasciencepipelines/datasciencepipelines.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/status/status.go
Labels: lgtm, approved

#1073 chore: removes unused client parameter
  components/kserve/kserve.go
  components/kserve/kserve_config_handler.go
  components/kserve/servicemesh_setup.go
Labels: lgtm, approved

#1074 chore(lint): updates golangci-lint to latest version
  .github/workflows/linter.yaml
  .golangci.yml
  Makefile
  components/kserve/kserve_config_handler.go
  controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/secretgenerator/secret.go
  controllers/secretgenerator/secretgenerator_controller.go
  controllers/status/reporter.go
  pkg/cluster/resources.go
  pkg/deploy/deploy.go
  pkg/feature/builder.go
  pkg/feature/feature_tracker_handler.go
  pkg/feature/manifest.go
  pkg/feature/serverless/conditions.go
  tests/e2e/controller_setup_test.go
  tests/e2e/dsc_cfmap_deletion_test.go
  tests/e2e/dsc_creation_test.go
  tests/envtestutil/cleaner.go
  tests/envtestutil/utils.go
  tests/integration/features/serverless_feature_test.go
  tests/integration/features/tracker_int_test.go
Labels: lgtm, approved

#1066 chore: Improve automation logic for reading release branches
  .github/scripts/get-component-release-notes.js
  .github/scripts/get-release-branches.js
Labels: lgtm, approved

#1072 feat(meta): adds InNamespace and WithAnnotation setter funcs
  pkg/cluster/cluster_operations_int_test.go
  pkg/cluster/cluster_operations_suite_int_test.go
  pkg/cluster/meta.go
  pkg/cluster/resources.go
Labels: lgtm, approved

#1078 feat(lint): configures importas for consistent import aliases
  .golangci.yml
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/workbenches/workbenches.go
  controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/datasciencecluster/suite_test.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/dscinitialization_test.go
  controllers/dscinitialization/monitoring.go
  controllers/dscinitialization/suite_test.go
  controllers/dscinitialization/utils.go
  controllers/secretgenerator/secretgenerator_controller.go
  controllers/webhook/webhook_suite_test.go
  main.go
  pkg/cluster/cert.go
  pkg/cluster/cluster_config.go
  pkg/cluster/cluster_operations_int_test.go
  pkg/cluster/cluster_operations_suite_int_test.go
  pkg/cluster/resources.go
  pkg/deploy/deploy.go
  pkg/feature/feature_tracker_handler.go
  pkg/feature/handler.go
  pkg/trustedcabundle/trustedcabundle.go
  pkg/upgrade/uninstallation.go
  pkg/upgrade/upgrade.go
  tests/e2e/controller_setup_test.go
  tests/e2e/dsc_cfmap_deletion_test.go
  tests/e2e/dsc_creation_test.go
  tests/e2e/dsc_deletion_test.go
  tests/e2e/helper_test.go
  tests/envtestutil/cleaner.go
  tests/integration/features/features_suite_int_test.go
  tests/integration/features/fixtures/cluster_test_fixtures.go
  tests/integration/features/preconditions_int_test.go
  tests/integration/features/resources_int_test.go
Labels: lgtm, approved

#1079 fix: do not redeploy segment-io's if it has been deployed previously
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/monitoring.go
Labels: lgtm, approved

#1070 chore(lint): enable contextcheck and containedctx
  .golangci.yml
  components/codeflare/codeflare.go
  components/component.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/kserve/kserve_config_handler.go
  components/kserve/serverless_setup.go
  components/kserve/servicemesh_setup.go
  components/kueue/kueue.go
  components/modelmeshserving/modelmeshserving.go
  components/modelregistry/modelregistry.go
  components/ray/ray.go
  components/trainingoperator/trainingoperator.go
  components/trustyai/trustyai.go
  components/workbenches/workbenches.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/dscinitialization_test.go
  controllers/dscinitialization/monitoring.go
  controllers/dscinitialization/servicemesh_setup.go
  controllers/dscinitialization/suite_test.go
  controllers/dscinitialization/utils.go
  controllers/status/reporter.go
  controllers/webhook/webhook_suite_test.go
  main.go
  pkg/cluster/cluster_config.go
  pkg/cluster/cluster_operations_int_test.go
  pkg/cluster/operator.go
  pkg/deploy/deploy.go
  pkg/feature/conditions.go
  pkg/feature/feature.go
  pkg/feature/feature_tracker_handler.go
  pkg/feature/handler.go
  pkg/feature/raw_resources.go
  pkg/feature/resources.go
  pkg/feature/serverless/conditions.go
  pkg/feature/serverless/loaders.go
  pkg/feature/serverless/resources.go
  pkg/feature/servicemesh/cleanup.go
  pkg/feature/servicemesh/conditions.go
  pkg/feature/servicemesh/loaders.go
  pkg/feature/servicemesh/resources.go
  pkg/upgrade/uninstallation.go
  pkg/upgrade/upgrade.go
  tests/e2e/controller_setup_test.go
  tests/e2e/dsc_cfmap_deletion_test.go
  tests/e2e/dsc_creation_test.go
  tests/e2e/helper_test.go
  tests/envtestutil/cleaner.go
  tests/integration/features/cleanup_int_test.go
  tests/integration/features/features_suite_int_test.go
  tests/integration/features/fixtures/cluster_test_fixtures.go
  tests/integration/features/manifests_int_test.go
  tests/integration/features/preconditions_int_test.go
  tests/integration/features/resources_int_test.go
  tests/integration/features/serverless_feature_test.go
  tests/integration/features/servicemesh_feature_test.go
  tests/integration/features/tracker_int_test.go
Labels: lgtm, approved, ok-to-test

#1084 chore: exclude file which auto-gen by "make" checkin
  .gitignore
Labels: lgtm, approved

#1080 chore: remove duplicated logic by function call
  pkg/cluster/cert.go
Labels: lgtm, approved

#1085 fix(lint): explicitly configures ireturn exceptions
  .golangci.yml
  controllers/status/reporter.go
  pkg/plugins/addLabelsplugin.go
  pkg/plugins/namespacePlugin.go
Labels: lgtm, approved

#1082 Update version to 2.14.0
  Makefile
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#1076 webhook: refactor with switch and helpers
  controllers/webhook/webhook.go
Labels: lgtm, approved

#1087 fix: add odh-modle-controller NWP to whitelist
  controllers/datasciencecluster/datasciencecluster_controller.go
Labels: lgtm, approved, rhoai-2.11
