Repository opendatahub-io/opendatahub-operator, pull requests merged in 2024-10, with the labels that each got.

#1269 feat: add support for upgrade to force disableModelRegistry to false
  pkg/upgrade/upgrade.go
Labels: lgtm, approved

#1272 controllers, monitoring: use local variable for logger
  controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/monitoring.go
  controllers/dscinitialization/servicemesh_setup.go
  controllers/dscinitialization/utils.go
  controllers/secretgenerator/secretgenerator_controller.go
Labels: lgtm, approved

#1271 DSCI CRD: allow default as a value for logmode
  apis/dscinitialization/v1/dscinitialization_types.go
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  docs/api-overview.md
Labels: lgtm, approved

#1273 Fixed typo for jackdelahunt owner
  OWNERS_ALIASES
Labels: lgtm, approved

#1059 cluster_config: init cluster variables on startup
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  main.go
  pkg/cluster/cluster_config.go
Labels: lgtm, approved, needs-rebase

#1191 components: move params.env image updating to Init stage
  components/codeflare/codeflare.go
  components/component.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/kueue/kueue.go
  components/modelmeshserving/modelmeshserving.go
  components/modelregistry/modelregistry.go
  components/ray/ray.go
  components/trainingoperator/trainingoperator.go
  components/trustyai/trustyai.go
  components/workbenches/workbenches.go
  main.go
Labels: lgtm, approved

#1275 update: remove webhook service from bundle
  Makefile
  bundle/manifests/opendatahub-operator-webhook-service_v1_service.yaml
Labels: lgtm, approved, rhoai-2.14

#1263 update: add validation on application and monitoring namespace in DSCI
  apis/dscinitialization/v1/dscinitialization_types.go
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  docs/api-overview.md
Labels: lgtm, approved, needs-review

#1280 logger: add zap command line switches
  main.go
  pkg/logger/logger.go
Labels: lgtm, approved

#1279 Modify Unit Tests GitHub Actions workflow to get code coverage test reports
  .github/workflows/unit-tests.yaml
Labels: lgtm, approved

#1284 webhook: move initialization inside of the module
  controllers/webhook/webhook.go
  main.go
Labels: lgtm, approved

#1252 feat: pass platform from env variable or fall back to use old logic
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  pkg/cluster/cluster_config.go
Labels: lgtm, approved

#1287 fix: update release version in DSCI and DSC for upgrade case
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
Labels: lgtm, approved

#1286 Makefile, webhook: add run-nowebhook
  Makefile
  controllers/webhook/nowebhook.go
  controllers/webhook/webhook.go
Labels: lgtm, approved

#1298 update: use namespace dyniamically from operator env than hardcode value
  controllers/dscinitialization/utils.go
  main.go
  pkg/cluster/cluster_config.go
Labels: lgtm, approved

#1295 webhook: switch to contextual logger
  controllers/webhook/webhook.go
Labels: approved

#1301 chore: use client.OjectKeyFromObject in client.Get() and add k8serr as alias
  controllers/dscinitialization/monitoring.go
  controllers/dscinitialization/utils.go
  pkg/cluster/resources.go
  pkg/cluster/roles.go
  pkg/trustedcabundle/trustedcabundle.go
  tests/e2e/deletion_test.go
  tests/e2e/helper_test.go
  tests/integration/features/cleanup_int_test.go
  tests/integration/features/servicemesh_feature_test.go
Labels: lgtm, approved

#1296 (fix): Change on trigger to pull_request_target in the "check-file-updates.yaml" action
  .github/workflows/check-file-updates.yaml
Labels: lgtm, approved

#1297 feat: Operator disable create usergroup if detect user enabled external auth
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/crd/external/config.openshift.io_authentications.yaml
  config/rbac/role.yaml
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/dscinitialization_test.go
  controllers/dscinitialization/suite_test.go
  main.go
  pkg/cluster/cluster_config.go
  pkg/cluster/const.go
Labels: lgtm, approved, rhoai-2.13.1

#1253 components, logger: use contextual logging approach
  components/codeflare/codeflare.go
  components/component.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/kueue/kueue.go
  components/modelmeshserving/modelmeshserving.go
  components/modelregistry/modelregistry.go
  components/ray/ray.go
  components/trainingoperator/trainingoperator.go
  components/trustyai/trustyai.go
  components/workbenches/workbenches.go
  controllers/datasciencecluster/datasciencecluster_controller.go
Labels: lgtm, approved

#1306 fix: to make the unset env variable in CSV work with fallback
  pkg/cluster/cluster_config.go
Labels: lgtm, approved, rhoai-2.15

#1308 controllers: switch to k8s contextual logger
  components/kserve/servicemesh_setup.go
  controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/monitoring.go
  controllers/dscinitialization/servicemesh_setup.go
  controllers/dscinitialization/suite_test.go
  controllers/dscinitialization/utils.go
  controllers/secretgenerator/secretgenerator_controller.go
  main.go
  pkg/cluster/resources.go
  pkg/upgrade/uninstallation.go
  pkg/upgrade/upgrade.go
Labels: lgtm, approved

#1310 Tidy up run-nowebhook recipe & make clean PHONY
  Makefile
Labels: lgtm, approved

#1311 Refactor secret generator controller
  controllers/secretgenerator/secretgenerator_controller.go
  controllers/secretgenerator/secretgenerator_controller_test.go
Labels: lgtm, approved

#1313 update: rename variables rhods to rhoai
  components/codeflare/codeflare.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/kueue/kueue.go
  components/modelmeshserving/modelmeshserving.go
  components/modelregistry/modelregistry.go
  components/ray/ray.go
  components/trainingoperator/trainingoperator.go
  components/trustyai/trustyai.go
  components/workbenches/workbenches.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/utils.go
  main.go
  pkg/cluster/cluster_config.go
  pkg/cluster/const.go
  pkg/upgrade/uninstallation.go
  pkg/upgrade/upgrade.go
Labels: lgtm, approved

#1307 logger: add logLevel to DSCI devFlags
  README.md
  apis/dscinitialization/v1/dscinitialization_types.go
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  docs/api-overview.md
  main.go
  pkg/logger/logger.go
Labels: lgtm, approved

#1314 fix: missing rbac on dashbaord component to start Operator from CSV
  bundle/manifests/components.opendatahub.io_codeflares.yaml
  bundle/manifests/components.opendatahub.io_dashboards.yaml
  bundle/manifests/components.opendatahub.io_datasciencepipelines.yaml
  bundle/manifests/components.opendatahub.io_kserves.yaml
  bundle/manifests/components.opendatahub.io_kueues.yaml
  bundle/manifests/components.opendatahub.io_modelmeshservings.yaml
  bundle/manifests/components.opendatahub.io_modelregistries.yaml
  bundle/manifests/components.opendatahub.io_rays.yaml
  bundle/manifests/components.opendatahub.io_trainingoperators.yaml
  bundle/manifests/components.opendatahub.io_trustyais.yaml
  bundle/manifests/components.opendatahub.io_workbenches.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/components/dashboard/dashboard_controller.go
  controllers/datasciencecluster/kubebuilder_rbac.go
Labels: lgtm, approved

#1312 secret-generator controller: avoid reporting 'Secret not found' error in reconcile
  controllers/secretgenerator/secretgenerator_controller.go
  controllers/secretgenerator/secretgenerator_controller_test.go
Labels: lgtm, approved

#1316 Avoid storing management state n the component CR as it is not needed
  apis/components/component.go
  apis/components/v1/dashboard_types.go
  apis/components/v1/zz_generated.deepcopy.go
  apis/components/zz_generated.deepcopy.go
  config/crd/bases/components.opendatahub.io_dashboards.yaml
  controllers/components/dashboard/dashboard_controller.go
  controllers/webhook/webhook_suite_test.go
  docs/api-overview.md
  pkg/upgrade/upgrade.go
  tests/e2e/dashboard_test.go
  tests/e2e/helper_test.go
Labels: lgtm, approved

#1281 update: remove dsp with v1(tekton)backend related code
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  components/datasciencepipelines/datasciencepipelines.go
  config/manifests/description-patch.yml
  config/rbac/role.yaml
  controllers/datasciencecluster/kubebuilder_rbac.go
  docs/api-overview.md
Labels: odh-2.20, rhoai-2.16

#1254 update: remove two SA which does not seem valid
  components/modelmeshserving/modelmeshserving.go
Labels: lgtm, needs-review, odh-2.20

#1315 feat: add support for Ray
  .golangci.yml
  apis/components/v1/dashboard_types.go
  apis/components/v1/ray_types.go
  apis/components/v1/zz_generated.deepcopy.go
  apis/datasciencecluster/v1/datasciencecluster_types.go
  bundle/manifests/components.opendatahub.io_dashboards.yaml
  bundle/manifests/components.opendatahub.io_rays.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  components/dashboard/dashboard.go
  components/dashboard/zz_generated.deepcopy.go
  components/ray/ray.go
  components/ray/zz_generated.deepcopy.go
  config/crd/bases/components.opendatahub.io_rays.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  controllers/components/dashboard/dashboard.go
  controllers/components/dashboard/dashboard_controller.go
  controllers/components/ray/ray.go
  controllers/components/ray/ray_controller.go
  controllers/components/ray/ray_controller_actions.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/datasciencecluster/kubebuilder_rbac.go
  controllers/webhook/webhook_suite_test.go
  docs/api-overview.md
  main.go
  pkg/controller/handlers/handlers.go
  pkg/upgrade/upgrade.go
  tests/e2e/controller_test.go
  tests/e2e/creation_test.go
  tests/e2e/dashboard_test.go
  tests/e2e/helper_test.go
  tests/e2e/odh_manager_test.go
  tests/e2e/ray_test.go
  tests/integration/features/features_suite_int_test.go
Labels: feature-operator-refactor

#1322 fix: wrong type of ingresscontroller
  controllers/datasciencecluster/datasciencecluster_controller.go
  main.go
Labels: lgtm, approved

#1327 update golangci-lint to v1.61.0
  .github/workflows/linter.yaml
  Makefile
  controllers/dscinitialization/suite_test.go
  controllers/webhook/webhook_suite_test.go
  pkg/logger/logger.go
Labels: lgtm, approved

#1331 fix: missing comopnent init step for Ray in main
  main.go
Labels: lgtm, approved, feature-operator-refactor

#1335 chore: Join path if NOT empty string
  pkg/controller/types/types.go
Labels: lgtm, approved
