Repository opendatahub-io/opendatahub-operator, pull requests merged in 2024-04, with the labels that each got.

#837 feat(logger): for both controller level and component level
  README.md
  apis/dscinitialization/v1/dscinitialization_types.go
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  components/README.md
  components/codeflare/codeflare.go
  components/component.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/kueue/kueue.go
  components/modelmeshserving/modelmeshserving.go
  components/modelregistry/modelregistry.go
  components/ray/ray.go
  components/trustyai/trustyai.go
  components/workbenches/workbenches.go
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/manager/manager.yaml
  controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/secretgenerator/secretgenerator_controller.go
  docs/api-overview.md
  go.mod
  go.sum
  main.go
  pkg/common/common.go
  pkg/deploy/deploy.go
Labels: lgtm, approved, odh-2.10

#946 Release 2.10: Update version
  Makefile
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#951 ODH 2.10 Release
  get_all_manifests.sh
Labels: lgtm, approved

#948 fix: properly updates config map
  pkg/cluster/cluster_operations_int_test.go
  pkg/cluster/resources.go
  pkg/feature/servicemesh/resources.go
Labels: lgtm, approved

#944 Addding kfto component to odh operator
  README.md
  apis/datasciencecluster/v1/datasciencecluster_types.go
  apis/datasciencecluster/v1/zz_generated.deepcopy.go
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  components/component.go
  components/trainingoperator/trainingoperator.go
  components/trainingoperator/zz_generated.deepcopy.go
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/samples/datasciencecluster_v1_datasciencecluster.yaml
  docs/DESIGN.md
  docs/api-overview.md
  get_all_manifests.sh
  pkg/upgrade/upgrade.go
  tests/e2e/dsc_creation_test.go
  tests/e2e/dsc_deletion_test.go
  tests/e2e/helper_test.go
Labels: lgtm, approved

#954 Add visualization for Reconcile func
  components/Component Reconcile Workflow.png
  components/README.md
Labels: lgtm, approved

#949 feat(authz): conditionally enables authorization capability
  components/kserve/kserve.go
  components/kserve/servicemesh_setup.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/capabilities.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/servicemesh_setup.go
  controllers/status/reporter.go
  controllers/status/status.go
  pkg/feature/conditions.go
  pkg/feature/handler.go
Labels: lgtm, approved

#930 feat(mr): create namespace for Model Registry
  components/modelregistry/modelregistry.go
Labels: lgtm, approved

#960 Release v2.10.1: version update
  Makefile
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#963 fix(deploy): wrong logic in if when apply ownership
  pkg/deploy/deploy.go
Labels: lgtm, approved, rhoai-2.9

#958 Update(rbac): remove MCAD, Appwrapper, instascales related permission in operator
  .github/workflows/linter.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/datasciencecluster/kubebuilder_rbac.go
Labels: lgtm

#959 pkg/upgrade: remove watson-studio dashboard application
  pkg/gvk/gvk.go
  pkg/upgrade/upgrade.go
Labels: lgtm, approved

#964 fix(e2e): do not test deletion configmap is true
  tests/e2e/controller_setup_test.go
  tests/e2e/dsc_cfmap_deletion_test.go
  tests/e2e/dsc_deletion_test.go
Labels: lgtm, approved

#965 Add Ability to configure resources in Kserve
  pkg/deploy/deploy.go
Labels: lgtm, approved, rhoai-2.9

#966 Add Opendatahub-operator pod selector label
  config/manager/manager.yaml
Labels: lgtm, approved

#829 fix: CVE-2023-7104(github.com/mattn/go-sqlite3)
  go.mod
  go.sum
Labels: lgtm, approved

#955 Add check for existing Argo Workflows
  components/datasciencepipelines/datasciencepipelines.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/status/status.go
  main.go
Labels: approved

#967 fix(dspv2): label should be check on existance and value as well
  components/datasciencepipelines/datasciencepipelines.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  pkg/deploy/deploy.go
  pkg/metadata/annotations/annoations.go
Labels: lgtm, approved

#811 upgrade(go): use 1.20
  Dockerfiles/Dockerfile
  Dockerfiles/toolbox.Dockerfile
  Makefile
  go.mod
  pkg/cluster/cluster_operations_suite_int_test.go
  tests/integration/features/features_suite_int_test.go
Labels: lgtm, approved, incubating

#932 chore: separate templates
  components/kserve/feature_resources.go
  components/kserve/resources/servicemesh/activator-envoyfilter.tmpl.yaml
  components/kserve/resources/servicemesh/envoy-oauth-temp-fix.tmpl.yaml
  components/kserve/resources/servicemesh/grpc-envoyfilter-temp-fix.tmpl.yaml
  components/kserve/resources/servicemesh/kserve-predictor-authorizationpolicy.tmpl.yaml
  components/kserve/resources/servicemesh/routing/istio-ingress-gateway.tmpl.yaml
  components/kserve/resources/servicemesh/routing/istio-local-gateway.yaml
  components/kserve/resources/servicemesh/routing/local-gateway-svc.tmpl.yaml
  components/kserve/resources/servicemesh/z-migrations/kserve-predictor-authorizationpolicy.patch.tmpl.yaml
  components/kserve/resources/serving-install/knative-serving.tmpl.yaml
  components/kserve/resources/serving-install/service-mesh-subscription.tmpl.yaml
  components/kserve/resources/serving-net-istio-secret-filtering.patch.tmpl.yaml
  components/kserve/serverless_setup.go
  components/kserve/servicemesh_setup.go
  controllers/dscinitialization/feature_resources.go
  controllers/dscinitialization/resources/authorino/auth-smm.tmpl.yaml
  controllers/dscinitialization/resources/authorino/base/operator-cluster-wide-no-tls.tmpl.yaml
  controllers/dscinitialization/resources/authorino/deployment.injection.patch.tmpl.yaml
  controllers/dscinitialization/resources/authorino/mesh-authz-ext-provider.patch.tmpl.yaml
  controllers/dscinitialization/resources/metrics-collection/envoy-metrics-collection.tmpl.yaml
  controllers/dscinitialization/resources/metrics-collection/pilot-metrics-collection.tmpl.yaml
  controllers/dscinitialization/resources/servicemesh/create-smcp.tmpl.yaml
  controllers/dscinitialization/servicemesh_setup.go
  pkg/feature/builder.go
  pkg/feature/feature.go
  pkg/feature/manifest.go
  tests/integration/features/fixtures/const.go
  tests/integration/features/fixtures/templates/local-gateway-svc.tmpl.yaml
  tests/integration/features/fixtures/templates/mesh-authz-ext-provider.patch.tmpl.yaml
  tests/integration/features/manifests_int_test.go
  tests/integration/features/servicemesh_feature_test.go
Labels: lgtm, approved

#971 fix(DSC): when DSC is in Error because of missing DSCI CR
  controllers/datasciencecluster/datasciencecluster_controller.go
Labels: lgtm, approved

#969 fix: reworks FeatureTracker status handling
  apis/features/v1/features_types.go
  apis/features/v1/zz_generated.deepcopy.go
  config/crd/bases/features.opendatahub.io_featuretrackers.yaml
  controllers/status/doc.go
  controllers/status/reporter.go
  pkg/feature/feature.go
  pkg/feature/feature_tracker_handler.go
  tests/integration/features/tracker_int_test.go
Labels: lgtm, approved

#849 Add upgrade bundle commands
  Makefile
Labels: approved

#972 fix(cfgmap): simplifies create/update (again!)
  pkg/cluster/cluster_operations_int_test.go
  pkg/cluster/meta.go
  pkg/cluster/resources.go
  pkg/feature/servicemesh/resources.go
Labels: lgtm, approved

#973 chore: removes dead code and adds godoc
  pkg/cluster/resources.go
  tests/integration/features/fixtures/cluster_test_fixtures.go
Labels: lgtm, approved

#976 chore: simplifies CreateNamespace logic
  pkg/cluster/resources.go
Labels: lgtm, approved

#975 tests: e2e: use loop to iterate over components
  tests/e2e/dsc_creation_test.go
  tests/e2e/dsc_deletion_test.go
Labels: lgtm, approved

#980 chore(cleanup): remove sample for featuretracker
  bundle/manifests/features.opendatahub.io_featuretrackers.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/samples/featuretracker_v1_features.yaml
  config/samples/kustomization.yaml
Labels: lgtm, approved, odh-2.11

#979 fix(status): do not set Unknown back to component for every loop on reconcile
  controllers/datasciencecluster/datasciencecluster_controller.go
Labels: lgtm, approved, odh-2.11

#982 [backport] ray: Cleanup opendatahub Namespace
  pkg/upgrade/upgrade.go
Labels: lgtm, approved, odh-2.11

#983 Version update for odh 2.11
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#985 Odh 2.11.0 release
  Makefile
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/description-patch.yml
  get_all_manifests.sh
Labels: approved

#981 chore: cleanup duplicated functions packages and add more for godoc
  apis/features/v1/groupversion_info.go
  components/codeflare/codeflare.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/kueue/kueue.go
  components/modelmeshserving/modelmeshserving.go
  components/modelregistry/modelregistry.go
  components/ray/ray.go
  components/trainingoperator/trainingoperator.go
  components/trustyai/trustyai.go
  components/workbenches/workbenches.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/monitoring.go
  controllers/dscinitialization/utils.go
  docs/api-overview.md
  main.go
  pkg/cluster/cluster_config.go
  pkg/cluster/const.go
  pkg/cluster/doc.go
  pkg/cluster/gvk/gvk.go
  pkg/cluster/resources.go
  pkg/common/common.go
  pkg/deploy/deploy.go
  pkg/deploy/setup.go
  pkg/feature/serverless/conditions.go
  pkg/feature/servicemesh/cleanup.go
  pkg/feature/servicemesh/conditions.go
  pkg/gvk/gvk.go
  pkg/monitoring/monitoring.go
  pkg/trustedcabundle/trustedcabundle.go
  pkg/upgrade/uninstallation.go
  pkg/upgrade/upgrade.go
  tests/integration/features/servicemesh_feature_test.go
Labels: lgtm, approved

#986 chore: better debug info + a clear check on env variable DISABLE_DSC_CONFIG
  main.go
Labels: lgtm, approved

#974 feat: provide option to control reconciliation when creating resources
  pkg/feature/builder.go
  pkg/feature/feature.go
  pkg/feature/manifest.go
  pkg/feature/raw_resources.go
  pkg/metadata/annotations/annotations.go
  tests/integration/features/fixtures/cluster_test_fixtures.go
  tests/integration/features/fixtures/templates/managed-svc.yaml
  tests/integration/features/manifests_int_test.go
  tests/integration/features/resources_int_test.go
Labels: lgtm, approved

#990 chore: passing down ctx in the chain than placeholder TODO()
  components/dashboard/dashboard.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/monitoring.go
  controllers/secretgenerator/secretgenerator_controller.go
  main.go
  pkg/upgrade/upgrade.go
Labels: lgtm, approved
