Repository opendatahub-io/opendatahub-operator, pull requests merged in 2024-11, with the labels that each got.

#1336 chore: remove duplicated image in modelmesh
  components/modelmeshserving/modelmeshserving.go
Labels: lgtm, approved

#1332 chore: rbac cleanup + lint fix
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/components/codeflare/codeflare_controller.go
  controllers/components/datasciencepipelines/datasciencepipelines_controller.go
  controllers/components/kserve/kserve_controller.go
  controllers/components/kueue/kueue_controller.go
  controllers/components/modelmeshserving/modelmeshserving_controller.go
  controllers/components/modelregistry/modelregistry_controller.go
  controllers/components/ray/ray.go
  controllers/components/ray/ray_controller.go
  controllers/components/trainingoperator/trainingoperator_controller.go
  controllers/components/trustyai/trustyai_controller.go
  controllers/components/workbenches/workbenches_controller.go
  controllers/datasciencecluster/kubebuilder_rbac.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/kubebuilder_rbac.go
  controllers/dscinitialization/monitoring.go
  pkg/cluster/cluster_config.go
  tests/e2e/helper_test.go
Labels: lgtm, approved, feature-operator-refactor

#1345 Remove generics for ComponentReconciler and ComponentReconcilerBuilder
  controllers/components/dashboard/dashboard_controller.go
  controllers/components/modelregistry/modelregistry_controller.go
  controllers/components/ray/ray_controller.go
  pkg/controller/reconciler/component_reconciler.go
  pkg/controller/reconciler/component_reconciler_support.go
Labels: lgtm, approved

#1343 Replace components.opendatahub.io/managed-by with components.opendatahub.io/part-of
  controllers/components/dashboard/dashboard_controller.go
  controllers/components/dashboard/dashboard_controller_actions.go
  controllers/components/modelregistry/modelregistry_controller.go
  controllers/components/ray/ray_controller.go
  pkg/controller/actions/render/action_render_manifests_test.go
  pkg/controller/handlers/handlers.go
  pkg/controller/reconciler/component_reconciler_support.go
  pkg/metadata/labels/types.go
  tests/e2e/dashboard_test.go
  tests/e2e/modelregistry_test.go
  tests/e2e/ray_test.go
Labels: lgtm, approved

#1348 chore: cleanup
  components/kserve/kserve.go
  config/rbac/role_binding.yaml
  docs/api-overview.md
  tests/e2e/odh_manager_test.go
Labels: lgtm, approved, rhoai

#1350 fix: auto-sync with conflict
  .github/workflows/linter.yaml
  .github/workflows/unit-tests.yaml
  .gitignore
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  components/kserve/kserve.go
  config/rbac/role_binding.yaml
  controllers/dscinitialization/suite_test.go
  controllers/webhook/webhook_suite_test.go
  tests/e2e/odh_manager_test.go
Labels: lgtm, approved, rhoai

#1339 fix: ensure input CAbundle always end with a newline
  pkg/trustedcabundle/trustedcabundle.go
Labels: lgtm, approved, odh-2.21

#1351 Allow to run the e2e test suite locally, against an out of the cluster operator
  Makefile
  README.md
  tests/e2e/controller_test.go
  tests/e2e/creation_test.go
  tests/e2e/dashboard_test.go
  tests/e2e/modelregistry_test.go
  tests/e2e/ray_test.go
Labels: lgtm, approved, feature-operator-refactor

#1341 fix: add check to remove old kube-rbac-proxy container in modelregistry operator, fixes RHOAIENG-15328
  pkg/upgrade/upgrade.go
Labels: priority/high, odh-2.21

#1354 Add a reusable update-pod-security-action
  controllers/components/dashboard/dashboard_controller.go
  controllers/components/dashboard/dashboard_controller_actions.go
  controllers/components/dashboard/dashboard_support.go
  pkg/cluster/gvk/gvk.go
  pkg/cluster/resources.go
  pkg/controller/actions/security/actions.go
  pkg/controller/actions/security/actions_test.go
  pkg/utils/test/fakeclient/fakeclient.go
Labels: lgtm, approved

#1353 Cleanup kustomize manifests rendering action
  controllers/components/dashboard/dashboard_controller.go
  controllers/components/modelregistry/modelregistry_controller.go
  controllers/components/ray/ray_controller.go
  pkg/controller/actions/render/kustomize/action_render_manifests.go
  pkg/controller/actions/render/kustomize/action_render_manifests_support.go
  pkg/controller/actions/render/kustomize/action_render_manifests_test.go
  pkg/controller/actions/render/render_metrics.go
  pkg/metadata/annotations/annotations.go
Labels: lgtm, approved

#1358 chore: support NewUpdatePodSecurityRoleBindingAction with multiple serviceaccounts
  controllers/components/dashboard/dashboard_support.go
  pkg/controller/actions/security/actions.go
  pkg/controller/actions/security/actions_test.go
Labels: lgtm, approved, feature-operator-refactor

#1360 Fix deployment cache action
  pkg/controller/actions/deploy/action_deploy.go
Labels: lgtm, approved, feature-operator-refactor

#1357 [sync]: change from incubation to rhoai + dummy change
  config/manager/kustomization.yaml.in
  pkg/trustedcabundle/trustedcabundle.go
  pkg/upgrade/upgrade.go
Labels: lgtm, approved, rhoai-2.16, rhoai

#1356 feat: add TrustyAI as component
  README.md
  apis/components/v1/trustyai_types.go
  apis/components/v1/zz_generated.deepcopy.go
  apis/datasciencecluster/v1/datasciencecluster_types.go
  bundle/manifests/components.opendatahub.io_trustyais.yaml
  components/trustyai/trustyai.go
  components/trustyai/zz_generated.deepcopy.go
  config/crd/bases/components.opendatahub.io_trustyais.yaml
  controllers/components/trustyai/trustyai.go
  controllers/components/trustyai/trustyai_controller.go
  controllers/components/trustyai/trustyai_controller_actions.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/datasciencecluster/kubebuilder_rbac.go
  controllers/webhook/webhook_suite_test.go
  docs/api-overview.md
  main.go
  pkg/upgrade/upgrade.go
  tests/e2e/controller_test.go
  tests/e2e/helper_test.go
  tests/e2e/odh_manager_test.go
  tests/e2e/trustyai_test.go
Labels: lgtm, approved, feature-operator-refactor

#1362 fix: wrong name of variable and func lead to always return self-managed
  pkg/cluster/cluster_config.go
Labels: lgtm, approved

#1363 fix: wrong name of variable and func lead to always return self-managed
  pkg/cluster/cluster_config.go
Labels: lgtm, approved, rhoai-2.16, rhoai

#1366 Enable deployment cache on the TrustyAI component
  controllers/components/trustyai/trustyai_controller.go
Labels: lgtm, approved

#1359 fix: add extra check on servicemesh CRD and svc before proceeding create SMCP CR
  pkg/cluster/operator.go
  pkg/feature/servicemesh/conditions.go
  tests/integration/features/fixtures/cluster_test_fixtures.go
  tests/integration/features/servicemesh_feature_test.go
Labels: lgtm, approved

#1342 feat: add support for trainingoperator to component
  apis/components/v1/trainingoperator_types.go
  apis/components/v1/zz_generated.deepcopy.go
  apis/datasciencecluster/v1/datasciencecluster_types.go
  bundle/manifests/components.opendatahub.io_trainingoperators.yaml
  components/trainingoperator/trainingoperator.go
  components/trainingoperator/zz_generated.deepcopy.go
  config/crd/bases/components.opendatahub.io_trainingoperators.yaml
  controllers/components/trainingoperator/trainingoperator.go
  controllers/components/trainingoperator/trainingoperator_controller.go
  controllers/components/trainingoperator/trainingoperator_controller_actions.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/datasciencecluster/kubebuilder_rbac.go
  docs/api-overview.md
  main.go
  pkg/upgrade/upgrade.go
  tests/e2e/controller_test.go
  tests/e2e/helper_test.go
  tests/e2e/odh_manager_test.go
  tests/e2e/trainingoperator_test.go
Labels: lgtm, approved, feature-operator-refactor

#1344 logger: set loglevel from ZAP_LOG_LEVEL environment variable
  README.md
  pkg/logger/logger.go
Labels: lgtm, approved

#1334 fix: added a filter to evicted pods when checking for ready status
  pkg/feature/conditions.go
Labels: lgtm, approved, component/kserve, odh-2.21

#1369 Task/NVPE-32: Cleanup NIM integration tech preview resources
  pkg/upgrade/upgrade.go
Labels: approved, ok-to-test

#1372 [sync]: Cleanup NIM integration tech preview resources
  pkg/upgrade/upgrade.go
Labels: lgtm, approved, rhoai-2.16

#1367 [sync] fix: add extra check on servicemesh CRD and svc before proceeding create SMCP CR (#1359)
  pkg/cluster/operator.go
  pkg/feature/servicemesh/conditions.go
  tests/integration/features/fixtures/cluster_test_fixtures.go
  tests/integration/features/servicemesh_feature_test.go
Labels: lgtm, approved, rhoai-2.16, rhoai

#1376 update: owners
  OWNERS_ALIASES
Labels: lgtm, approved

#1378 Updated codecov version to 4.6.0
  .github/workflows/unit-tests.yaml
Labels: lgtm, approved

#1382 Dockerfile, Makefile: make CGO_ENABLED configurable
  Dockerfiles/Dockerfile
  Makefile
Labels: lgtm, approved

#1383 fix: missing watch on prometheusrules and verb watch
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/datasciencecluster/kubebuilder_rbac.go
  main.go
Labels: lgtm, approved, feature-operator-refactor

#1340 datasciencepipelines component refactor
  apis/components/v1/datasciencepipelines_types.go
  apis/components/v1/zz_generated.deepcopy.go
  apis/datasciencecluster/v1/datasciencecluster_types.go
  bundle/manifests/components.opendatahub.io_datasciencepipelines.yaml
  components/datasciencepipelines/datasciencepipelines.go
  components/datasciencepipelines/zz_generated.deepcopy.go
  config/crd/bases/components.opendatahub.io_datasciencepipelines.yaml
  controllers/components/datasciencepipelines/datasciencepipelines.go
  controllers/components/datasciencepipelines/datasciencepipelines_controller.go
  controllers/components/datasciencepipelines/datasciencepipelines_controller_actions.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/datasciencecluster/kubebuilder_rbac.go
  controllers/status/status.go
  controllers/webhook/webhook_suite_test.go
  docs/api-overview.md
  main.go
  pkg/upgrade/upgrade.go
  tests/e2e/controller_test.go
  tests/e2e/dashboard_test.go
  tests/e2e/datasciencepipelines_test.go
  tests/e2e/helper_test.go
  tests/e2e/odh_manager_test.go
Labels: lgtm, approved, feature-operator-refactor

#1384 Makefile: make USE_LOCAL overridable
  Makefile
  README.md
Labels: lgtm, approved

#1386 Backport changes on unit-tests.yaml to rhoai branch
  .github/workflows/unit-tests.yaml
Labels: lgtm, approved

#1381 Dockerfile: merges manifests builder stages to one
  Dockerfiles/Dockerfile
Labels: lgtm, approved

#1385 Support to watch/own object not known when the operator starts, but only after a component has been enabled.
  .golangci.yml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/components/dashboard/dashboard.go
  controllers/components/dashboard/dashboard_controller.go
  controllers/components/datasciencepipelines/datasciencepipelines.go
  controllers/components/datasciencepipelines/datasciencepipelines_controller.go
  controllers/components/kueue/kueue.go
  controllers/components/kueue/kueue_controller.go
  controllers/components/modelregistry/modelregistry.go
  controllers/components/modelregistry/modelregistry_controller.go
  controllers/components/ray/ray.go
  controllers/components/ray/ray_controller.go
  controllers/components/trainingoperator/trainingoperator.go
  controllers/components/trainingoperator/trainingoperator_controller.go
  controllers/components/trustyai/trustyai.go
  controllers/components/trustyai/trustyai_controller.go
  controllers/datasciencecluster/kubebuilder_rbac.go
  pkg/cluster/gvk/gvk.go
  pkg/controller/handlers/handlers.go
  pkg/controller/predicates/resources/resources.go
  pkg/controller/reconciler/component_reconciler.go
  pkg/controller/reconciler/component_reconciler_actions.go
  pkg/controller/reconciler/component_reconciler_metrics.go
  pkg/controller/reconciler/component_reconciler_support.go
  pkg/resources/resources.go
  tests/e2e/controller_test.go
  tests/e2e/dashboard_test.go
  tests/e2e/modelregistry_test.go
Labels: lgtm, approved, feature-operator-refactor

#1374 Implement garbage collection action
  .golangci.yml
  controllers/components/dashboard/dashboard_controller.go
  controllers/components/datasciencepipelines/datasciencepipelines_controller.go
  controllers/components/kueue/kueue_controller.go
  controllers/components/modelregistry/modelregistry_controller.go
  controllers/components/modelregistry/modelregistry_controller_actions.go
  controllers/components/ray/ray_controller.go
  controllers/components/trainingoperator/trainingoperator_controller.go
  controllers/components/trustyai/trustyai_controller.go
  controllers/dscinitialization/suite_test.go
  main.go
  pkg/cluster/gvk/gvk.go
  pkg/controller/actions/deleteresource/action_delete_resources_test.go
  pkg/controller/actions/deploy/action_deploy.go
  pkg/controller/actions/deploy/action_deploy_cache_test.go
  pkg/controller/actions/deploy/action_deploy_test.go
  pkg/controller/actions/gc/action_gc.go
  pkg/controller/actions/gc/action_gc_metrics.go
  pkg/controller/actions/gc/action_gc_support.go
  pkg/controller/actions/gc/action_gc_test.go
  pkg/controller/actions/render/kustomize/action_render_manifests.go
  pkg/controller/actions/render/kustomize/action_render_manifests_test.go
  pkg/controller/actions/render/render_support.go
  pkg/controller/actions/render/template/action_render_templates.go
  pkg/controller/actions/render/template/action_render_templates_test.go
  pkg/controller/actions/security/actions_test.go
  pkg/controller/actions/updatestatus/action_update_status_test.go
  pkg/controller/client/client.go
  pkg/controller/reconciler/component_reconciler.go
  pkg/controller/reconciler/component_reconciler_support.go
  pkg/controller/types/types.go
  pkg/metadata/annotations/annotations.go
  pkg/resources/resources.go
  pkg/services/gc/gc.go
  pkg/services/gc/gc_support.go
  pkg/services/gc/gc_test.go
  pkg/utils/test/fakeclient/fakeclient.go
Labels: lgtm, approved, feature-operator-refactor

#1392 Reduce log verbosity for the gc service
  pkg/services/gc/gc.go
Labels: lgtm, approved, feature-operator-refactor

#1388 Reduce component reconciler's action verbosity
  controllers/components/dashboard/dashboard_controller.go
  controllers/components/dashboard/dashboard_controller_actions.go
  controllers/components/datasciencepipelines/datasciencepipelines_controller.go
  controllers/components/kueue/kueue_controller.go
  controllers/components/modelregistry/modelregistry_controller.go
  controllers/components/ray/ray_controller.go
  controllers/components/trainingoperator/trainingoperator_controller.go
  controllers/components/trustyai/trustyai_controller.go
  pkg/controller/actions/deploy/action_deploy.go
  pkg/controller/actions/deploy/action_deploy_cache_test.go
  pkg/controller/actions/deploy/action_deploy_test.go
  pkg/controller/actions/gc/action_gc.go
  pkg/controller/actions/gc/action_gc_support.go
  pkg/controller/actions/gc/action_gc_test.go
  pkg/controller/actions/updatestatus/action_update_status.go
  pkg/controller/actions/updatestatus/action_update_status_test.go
  pkg/controller/handlers/handlers.go
  pkg/controller/predicates/component/component.go
  pkg/controller/reconciler/component_reconciler.go
  pkg/controller/reconciler/component_reconciler_support.go
  pkg/metadata/annotations/annotations.go
  pkg/resources/resources.go
  pkg/utils/test/fakeclient/fakeclient.go
  tests/e2e/dashboard_test.go
  tests/e2e/datasciencepipelines_test.go
  tests/e2e/kueue_test.go
  tests/e2e/modelregistry_test.go
  tests/e2e/ray_test.go
  tests/e2e/trainingoperator_test.go
  tests/e2e/trustyai_test.go
Labels: lgtm, approved, feature-operator-refactor

#1398 fix: Renaming rhods-dashboard-alerting.unit-tests file
  tests/prometheus_unit_tests/rhods-dashboard-alerting.unit-tests.yaml
Labels: lgtm, approved

#1330 add enablement flag for nim
  README.md
  apis/infrastructure/v1/nim_types.go
  apis/infrastructure/v1/zz_generated.deepcopy.go
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  components/kserve/kserve.go
  components/kserve/zz_generated.deepcopy.go
  components/modelmeshserving/modelmeshserving.go
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/samples/datasciencecluster_v1_datasciencecluster.yaml
  docs/api-overview.md
Labels: lgtm, approved, ok-to-test, do-not-merge/hold

#1387 feat: codeflare component
  apis/components/v1/codeflare_types.go
  apis/components/v1/zz_generated.deepcopy.go
  apis/datasciencecluster/v1/datasciencecluster_types.go
  components/codeflare/codeflare.go
  components/codeflare/zz_generated.deepcopy.go
  config/crd/bases/components.opendatahub.io_codeflares.yaml
  controllers/components/codeflare/codeflare.go
  controllers/components/codeflare/codeflare_controller.go
  controllers/components/codeflare/codeflare_controller_actions.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/datasciencecluster/kubebuilder_rbac.go
  controllers/webhook/webhook_suite_test.go
  docs/api-overview.md
  main.go
  pkg/upgrade/upgrade.go
  tests/e2e/codeflare_test.go
  tests/e2e/controller_test.go
  tests/e2e/helper_test.go
Labels: lgtm, feature-operator-refactor, odh-2.22

#1349 feat: add support for Workbenches component
  apis/components/v1/workbenches_types.go
  apis/components/v1/zz_generated.deepcopy.go
  apis/datasciencecluster/v1/datasciencecluster_types.go
  bundle/manifests/components.opendatahub.io_workbenches.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  components/workbenches/workbenches.go
  components/workbenches/zz_generated.deepcopy.go
  config/crd/bases/components.opendatahub.io_workbenches.yaml
  controllers/components/workbenches/workbenches.go
  controllers/components/workbenches/workbenches_controller.go
  controllers/components/workbenches/workbenches_controller_actions.go
  controllers/components/workbenches/workbenches_support.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/webhook/webhook_suite_test.go
  docs/api-overview.md
  main.go
  pkg/upgrade/upgrade.go
  tests/e2e/controller_test.go
  tests/e2e/helper_test.go
  tests/e2e/odh_manager_test.go
  tests/e2e/workbenches_test.go
Labels: lgtm, approved, feature-operator-refactor, odh-2.22

#1397 Unique alert names
  config/monitoring/prometheus/apps/prometheus-configs.yaml
  tests/prometheus_unit_tests/codeflare-alerting.unit-tests.yaml
  tests/prometheus_unit_tests/data-science-pipelines-operator-alerting.unit-tests.yaml
  tests/prometheus_unit_tests/kserve-alerting.unit-tests.yaml
  tests/prometheus_unit_tests/model-mesh-alerting.unit-tests.yaml
  tests/prometheus_unit_tests/odh-model-controller-alerting.unit-tests.yaml
  tests/prometheus_unit_tests/rhods-dashboard-alerting.unit-tests.yaml
  tests/prometheus_unit_tests/trustyai-alerting.unit-tests.yaml
  tests/prometheus_unit_tests/workbenches-alerting.unit-tests.yaml
Labels: lgtm, approved

#1404 fix: codeflare missing bundle
  bundle/manifests/components.opendatahub.io_codeflares.yaml
Labels: lgtm, approved, feature-operator-refactor

#1347 feat: initial move of kserve to new structure
  apis/components/v1/kserve_types.go
  apis/components/v1/zz_generated.deepcopy.go
  apis/datasciencecluster/v1/datasciencecluster_types.go
  bundle/manifests/components.opendatahub.io_kserves.yaml
  components/kserve/kserve.go
  components/kserve/kserve_config_handler.go
  components/kserve/resources/servicemesh/z-migrations/kserve-predictor-authorizationpolicy.patch.tmpl.yaml
  components/kserve/serverless_setup.go
  components/kserve/servicemesh_setup.go
  components/kserve/zz_generated.deepcopy.go
  config/crd/bases/components.opendatahub.io_kserves.yaml
  controllers/components/kserve/feature_resources.go
  controllers/components/kserve/kserve.go
  controllers/components/kserve/kserve_controller.go
  controllers/components/kserve/kserve_controller_actions.go
  controllers/components/kserve/kserve_support.go
  controllers/components/kserve/resources/servicemesh/activator-envoyfilter.tmpl.yaml
  controllers/components/kserve/resources/servicemesh/envoy-oauth-temp-fix.tmpl.yaml
  controllers/components/kserve/resources/servicemesh/kserve-predictor-authorizationpolicy.tmpl.yaml
  controllers/components/kserve/resources/servicemesh/routing/istio-ingress-gateway.tmpl.yaml
  controllers/components/kserve/resources/servicemesh/routing/istio-kserve-local-gateway.tmpl.yaml
  controllers/components/kserve/resources/servicemesh/routing/istio-local-gateway.yaml
  controllers/components/kserve/resources/servicemesh/routing/kserve-local-gateway-svc.tmpl.yaml
  controllers/components/kserve/resources/servicemesh/routing/local-gateway-svc.tmpl.yaml
  controllers/components/kserve/resources/serving-install/knative-serving.tmpl.yaml
  controllers/components/kserve/resources/serving-install/service-mesh-subscription.tmpl.yaml
  controllers/components/kserve/resources/serving-net-istio-secret-filtering.patch.tmpl.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/datasciencecluster/kubebuilder_rbac.go
  controllers/status/status.go
  controllers/webhook/webhook_suite_test.go
  docs/api-overview.md
  go.mod
  main.go
  pkg/cluster/gvk/gvk.go
  pkg/controller/client/client.go
  pkg/controller/predicates/clusterrole/clusterrole.go
  pkg/controller/predicates/hash/hash.go
  pkg/controller/reconciler/component_reconciler_support.go
  pkg/upgrade/upgrade.go
  tests/e2e/controller_test.go
  tests/e2e/creation_test.go
  tests/e2e/helper_test.go
  tests/e2e/kserve_test.go
  tests/e2e/odh_manager_test.go
  tests/e2e/ray_test.go
  tests/integration/features/serverless_feature_test.go
Labels: lgtm, approved, feature-operator-refactor, odh-2.22

#1402 Remove adelton from the platform owners list.
  OWNERS_ALIASES
Labels: lgtm, approved, needs-ok-to-test

#1401 Add reusable functions to add/remove/update ReconciliationRequest.Resources
  controllers/components/dashboard/dashboard_controller_actions.go
  controllers/components/modelregistry/modelregistry_controller_actions.go
  controllers/components/workbenches/workbenches_controller_actions.go
  pkg/controller/types/types.go
  pkg/controller/types/types_test.go
  pkg/resources/resources.go
Labels: lgtm, approved, feature-operator-refactor

#1409 Typo fixes "manifests"
  components/kueue/kueue.go
  components/ray/ray.go
  components/workbenches/workbenches.go
Labels: lgtm, approved
