Repository opendatahub-io/opendatahub-operator, pull requests merged in 2024-05, with the labels that each got.

#992 feat(status): change Degraded status from False to True if no DSCI CR
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/status/status.go
Labels: lgtm, approved

#994 ODH Release v2.11.1
  Makefile
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  get_all_manifests.sh
  go.mod
  go.sum
Labels: approved

#996 chore(cleanup): remove checkDependentOperators as duplicated logic
  components/kserve/kserve_config_handler.go
Labels: lgtm, approved

#997 chore: remove CFO name check for downstream
  components/codeflare/codeflare.go
  main.go
Labels: lgtm, approved

#998 chore(logger): pass log-mode to each controller and move function to
  README.md
  components/component.go
  controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go
  main.go
  pkg/common/common.go
  pkg/logger/logger.go
Labels: lgtm, approved

#999 chore(docs): fix comments
  controllers/dscinitialization/feature_resources.go
Labels: lgtm

#1001 feat(fips): enable GO_ENABLED in build
  Dockerfiles/Dockerfile
Labels: lgtm, approved

#993 fix(uninstallation): do not delete subscription on Managed offering
  pkg/upgrade/uninstallation.go
Labels: lgtm, approved, odh-2.12

#1003 chore: add auth namespace to auth cfgmap
  pkg/feature/servicemesh/resources.go
Labels: lgtm, approved

#1005 chore: Update dashboard branch for manifest location
  get_all_manifests.sh
Labels: lgtm, approved

#1006 Doc change: Add flag to operator sdk run bundle to use quay io registry for busyb…
  README.md
Labels: lgtm, approved

#1002 [backport]: modelserving skip reconcile on deployment resources
  pkg/deploy/deploy.go
Labels: lgtm, approved, odh-2.12

#989 chore(cleanup): remove cleanup functions for upgrade from v1 to v2
  main.go
  pkg/upgrade/upgrade.go
Labels: lgtm, approved, odh-2.12

#1007 Update version to v2.12.0
  Makefile
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#1008 upgrade: retry if default DSCI creation fails
  pkg/cluster/resources.go
  pkg/upgrade/upgrade.go
Labels: lgtm, approved

#1013 chore: adds godoc to Feature builder
  pkg/feature/builder.go
Labels: lgtm, approved

#1015 Update version to v2.12.1
  Makefile
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#1021 Fix CSV name for RHOAI
  pkg/cluster/const.go
Labels: lgtm, approved

#988 ODH release automation
  .github/actions/update-manifest-branches/action.yaml
  .github/scripts/get-component-release-notes.js
  .github/scripts/get-release-branches.js
  .github/scripts/update-manifests-tags.sh
  .github/scripts/update-versions.sh
  .github/scripts/validate-semver.sh
  .github/scripts/wait-for-checks.sh
  .github/workflows/pre-release.yaml
  .github/workflows/release.yaml
  Makefile
Labels: lgtm, approved

#1010 tests: e2e: run components deletion as separate parallel tests
  tests/e2e/dsc_deletion_test.go
Labels: lgtm, approved

#1020 chore: Update model serving incubation branches (manifests)
  get_all_manifests.sh
Labels: lgtm, approved

#1019 kserve: configure servicemesh before deploying manifests
  components/kserve/kserve.go
Labels: lgtm, approved

#1024 fix: wrong path when use devFlag + wrong default value + special name in TrustyAI
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  components/component.go
  components/kueue/kueue.go
  components/trainingoperator/trainingoperator.go
  components/trustyai/trustyai.go
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  docs/api-overview.md
Labels: lgtm, approved

#1018 Fix metadata.managedFields must be nil error in DSC
  pkg/deploy/deploy.go
Labels: lgtm, approved, rhoai-2.10

#1027 chore: moves operator/subscriptions funcs to pkg/cluster
  components/codeflare/codeflare.go
  components/kserve/servicemesh_setup.go
  controllers/dscinitialization/servicemesh_setup.go
  pkg/cluster/operator.go
  pkg/deploy/deploy.go
  pkg/feature/conditions.go
  pkg/upgrade/uninstallation.go
Labels: lgtm, approved

#1023 Add release version to status
  apis/datasciencecluster/v1/datasciencecluster_types.go
  apis/datasciencecluster/v1/zz_generated.deepcopy.go
  apis/dscinitialization/v1/dscinitialization_types.go
  apis/dscinitialization/v1/zz_generated.deepcopy.go
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  docs/api-overview.md
  pkg/cluster/cluster_config.go
  pkg/cluster/zz_generated.deepcopy.go
Labels: lgtm, approved, rhoai-2.10

#1029 feat: remove modelserving from dashboard manifests
  components/dashboard/dashboard.go
Labels: lgtm, approved

#1028 cluster_config: make GetClusterServiceVersion return NotFound error
  pkg/cluster/cluster_config.go
  pkg/cluster/gvk/gvk.go
  pkg/upgrade/uninstallation.go
Labels: lgtm, approved
