Repository opendatahub-io/opendatahub-operator, pull requests merged in 2024-07, with the labels that each got.

#1090 chore: update owner list
  OWNERS
  OWNERS_ALIASES
Labels: lgtm

#1057 feat: adds EnabledWhen to the feature builder
  pkg/feature/builder.go
  pkg/feature/feature.go
  tests/integration/features/cleanup_int_test.go
Labels: lgtm, approved

#1065 refactor: dashboard with new manifests structure
  components/README.md
  components/codeflare/codeflare.go
  components/component.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/kueue/kueue.go
  components/modelmeshserving/modelmeshserving.go
  components/modelregistry/modelregistry.go
  components/ray/ray.go
  components/trainingoperator/trainingoperator.go
  components/trustyai/trustyai.go
  components/workbenches/workbenches.go
  pkg/deploy/deploy.go
  pkg/plugins/addLabelsplugin.go
Labels: lgtm, approved, do-not-merge/hold

#1093 Update release.name from DSC and DSCI
  pkg/cluster/const.go
Labels: lgtm, approved

#1092 chore(feature-tracker): simplifies struct handling
  pkg/feature/feature.go
  pkg/feature/feature_tracker_handler.go
Labels: lgtm, approved

#1097 chore: reworks authorino istio proxy injection patch
  controllers/dscinitialization/servicemesh_setup.go
  pkg/feature/feature.go
Labels: lgtm, approved

#1094 RHOAIENG-2974: Restrict DSCI deletion before DSC
  config/webhook/manifests.yaml
  controllers/webhook/webhook.go
  controllers/webhook/webhook_suite_test.go
  pkg/cluster/gvk/gvk.go
Labels: lgtm, approved

#1096 test: fix wrong test case for the cert type
  tests/e2e/dsc_creation_test.go
Labels: lgtm, approved

#1101 chore(tests): isolates resource reconcile tests
  tests/integration/features/fixtures/templates/managed-svc.tmpl.yaml
  tests/integration/features/fixtures/templates/unmanaged-svc.tmpl.yaml
  tests/integration/features/resources_int_test.go
Labels: lgtm, approved

#1104 chore(feature): adds context to manifest errors
  pkg/feature/manifest.go
Labels: lgtm, approved

#1105 chore(feature): removes unused tmpl func
  pkg/feature/manifest.go
  pkg/feature/types.go
Labels: lgtm, approved

#1102 Improve regex to accept white spaces before delimiters(release-automation)
  .github/scripts/get-component-release-notes.js
  .github/scripts/get-release-branches.js
Labels: lgtm, approved

#1106 backport: fix of annotation on kserve
  pkg/deploy/deploy.go
Labels: lgtm

#1107 Revert "chore: remove duplicated logic by function call (#1080)"
  components/kserve/kserve.go
  components/kserve/kserve_config_handler.go
Labels: approved

#1108 fix(envoy-filter): properly removes headers
  components/kserve/resources/servicemesh/envoy-oauth-temp-fix.tmpl.yaml
  components/kserve/servicemesh_setup.go
  pkg/feature/builder.go
  tests/integration/features/fixtures/templates/local-gateway-svc.tmpl.yaml
Labels: lgtm, approved

#1100 chore: cleanup remove kfdef during uninstallation
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/datasciencecluster/kubebuilder_rbac.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/suite_test.go
  main.go
  pkg/upgrade/uninstallation.go
  pkg/upgrade/upgrade.go
Labels: lgtm, approved

#1112 docs: removes not working styling
  pkg/feature/README.md
Labels: lgtm, approved

#1109 chore: removes obsolete attribution
  pkg/feature/raw_resources.go
Labels: lgtm, approved

#1110 chore(lint): skips true|false for goconst
  .golangci.yml
Labels: lgtm, approved

#1111 chore: fixes typos
  controllers/datasciencecluster/datasciencecluster_controller.go
Labels: lgtm, approved

#1113 refactor: moves conversion to unstr to dedicated package
  pkg/conversion/conversion.go
  pkg/deploy/deploy.go
  pkg/feature/manifest.go
  pkg/feature/raw_resources.go
Labels: lgtm, approved

#1116 Fix: Return if DSC already exists
  pkg/cluster/resources.go
Labels: lgtm, approved

#1115 feat(cluster): add roles and role bindings management
  pkg/cluster/roles.go
Labels: lgtm, approved

#1099 feat: add chunksize for List operation with pagination
  pkg/cluster/cluster_config.go
  pkg/cluster/resources.go
  pkg/trustedcabundle/trustedcabundle.go
Labels: odh-2.15

#1118 fix: ensures SMCP is created before any other features
  controllers/dscinitialization/servicemesh_setup.go
Labels: lgtm, approved

#1114 refactor: simplifies Feature Manifests
  components/kserve/serverless_setup.go
  components/kserve/servicemesh_setup.go
  controllers/dscinitialization/servicemesh_setup.go
  pkg/feature/builder.go
  pkg/feature/feature.go
  pkg/feature/manifest.go
  pkg/feature/manifest/builder.go
  pkg/feature/manifest/manifest_suite_test.go
  pkg/feature/manifest/manifest_test.go
  pkg/feature/manifest/types.go
  pkg/feature/resource/operations.go
  pkg/feature/resource/types.go
  tests/integration/features/fixtures/cluster_test_fixtures.go
  tests/integration/features/manifests_int_test.go
  tests/integration/features/resources_int_test.go
  tests/integration/features/servicemesh_feature_test.go
Labels: approved

#1117 update: check return of create dsci if failed because of existing
  pkg/upgrade/upgrade.go
Labels: lgtm, approved

#1128 Update version to 2.15
  Makefile
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#1131 fix: auto creation DSCI during startup
  pkg/cluster/resources.go
  pkg/upgrade/upgrade.go
Labels: lgtm, approved

#1121 chore: refactor on some logic for component manifests resources
  pkg/deploy/deploy.go
  pkg/deploy/envParams.go
  pkg/deploy/utils.go
Labels: lgtm, approved

#1133 RHOAIENG-9751: Update release.name from DSC and DSCI in ODH
  pkg/cluster/const.go
Labels: lgtm, approved

#1135 fix: authz patch injection feature precondition uses correct namespace value
  controllers/dscinitialization/servicemesh_setup.go
Labels: lgtm, approved

#1139 chore: get operator namespace from deployment as env variable
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  pkg/cluster/cluster_config.go
Labels: lgtm, approved

#1142 fix: when delete DSCI CR get stuck because the current instance updated and not preperly remove finalizer on it
  controllers/dscinitialization/dscinitialization_controller.go
Labels: lgtm, approved

#1143 chore: change local "manifests" folder to match in-image path
  .gitignore
  CONTRIBUTING.md
  Dockerfiles/Dockerfile
  Makefile
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  get_all_manifests.sh
  opt/manifests/.gitkeep
  pkg/deploy/deploy.go
Labels: lgtm, approved

#1132 (chore): Fix the token expiry and move release version update code to a composite action.
  .github/actions/update-release-version/action.yaml
  .github/workflows/pre-release.yaml
  .github/workflows/release.yaml
Labels: lgtm, approved

#1138 chore: update min k8s version to match min ocp version: 1.25 for 4.12
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Labels: lgtm, approved, odh-2.16

#1136 fix: devFlags for dashboard did not set correct values
  components/dashboard/dashboard.go
Labels: lgtm, odh-2.16

#1146 fix: for Managed cluster, we need another namespace or it will be deteced as self-managed
  pkg/cluster/cluster_config.go
Labels: lgtm, approved

#1147 chore: rename variable/function name
  pkg/deploy/deploy.go
  pkg/plugins/removerplugin.go
  tests/e2e/dsc_creation_test.go
Labels: lgtm, approved
