Repository opendatahub-io/opendatahub-operator, pull requests merged in 2024-09, with the labels that each got.

#1214 tests: enabled modelserving as Managed
  tests/e2e/helper_test.go
Labels: lgtm, approved

#1215 tests: e2e: testApplicationCreation cleanup
  tests/e2e/creation_test.go
Labels: lgtm, approved

#1190 feat: improve Operator performance by using caching to reduce api call and network impact
  controllers/webhook/webhook_suite_test.go
  main.go
Labels: lgtm, approved

#1218 feat: enable trustyai to use different manifests path
  components/trustyai/trustyai.go
Labels: lgtm, approved

#1199 chore: Rework release automation - ||
  .github/scripts/get-component-release-notes.js
  .github/scripts/get-release-branches.js
  .github/workflows/pre-release.yaml
Labels: lgtm, approved

#1216 tests: performance and time tuning for e2e
  tests/e2e/controller_test.go
  tests/e2e/creation_test.go
  tests/e2e/deletion_test.go
  tests/e2e/helper_test.go
  tests/e2e/odh_manager_test.go
Labels: lgtm, approved

#1223 fix(cache): since we add new secret from modelreg with cache, we need to lose the cache for istio-system ns
  main.go
Labels: lgtm, approved

#1224 fix: dashboard image not get set in downstream due to devFlags config
  components/dashboard/dashboard.go
Labels: lgtm, approved

#1225 add StevenTobin to owners
  OWNERS_ALIASES
Labels: lgtm, approved

#1200 Webhook config cleanup
  bundle/manifests/opendatahub-operator-webhook-service_v1_service.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/service.yaml
Labels: lgtm, approved

#1226 fix: nbc not use correct image for downstream + cleanup downstream path
  components/workbenches/workbenches.go
  pkg/cluster/const.go
Labels: lgtm, approved, odh-2.18

#1229 chore: update release keywords
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Labels: lgtm, approved, odh-2.18

#1220 feat: enable Trusty's Bias Feature Flag
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  main.go
  pkg/cluster/cluster_config.go
  pkg/upgrade/upgrade.go
Labels: lgtm, approved

#1228 feat(tracker): allows to define ownerReferences for FeatureTrackers
  components/component.go
  components/kserve/kserve.go
  components/kserve/kserve_config_handler.go
  components/kserve/servicemesh_setup.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/servicemesh_setup.go
  controllers/status/reporter.go
  pkg/cluster/gvk/gvk.go
  pkg/cluster/meta.go
  pkg/feature/builder.go
  pkg/feature/feature.go
  pkg/feature/feature_tracker_handler.go
  pkg/feature/handler.go
  pkg/feature/servicemesh/cleanup.go
  tests/integration/features/cleanup_int_test.go
  tests/integration/features/features_suite_int_test.go
  tests/integration/features/fixtures/cluster_test_fixtures.go
  tests/integration/features/manifests_int_test.go
  tests/integration/features/preconditions_int_test.go
  tests/integration/features/resources_int_test.go
  tests/integration/features/serverless_feature_test.go
  tests/integration/features/servicemesh_feature_test.go
  tests/integration/features/tracker_int_test.go
Labels: lgtm, approved

#1232 Rename GetPlatform functions to not reflect implementation
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  main.go
  pkg/cluster/cluster_config.go
  pkg/upgrade/upgrade.go
Labels: lgtm, approved, odh-2.18

#1221 feat: added shared registries namespace property in model registry dsc component, fixes RHOAIENG-12335
  PROJECT
  README.md
  apis/datasciencecluster/v1/datasciencecluster_types.go
  apis/datasciencecluster/v1/zz_generated.deepcopy.go
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  components/modelregistry/modelregistry.go
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/samples/datasciencecluster_v1_datasciencecluster.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/status/status.go
  controllers/webhook/webhook.go
  controllers/webhook/webhook_suite_test.go
  docs/DESIGN.md
  docs/api-overview.md
  docs/upgrade-testing.md
  main.go
  tests/e2e/creation_test.go
  tests/e2e/helper_test.go
Labels: lgtm, approved, rhoai-2.14, odh-2.18

#1222 feat: set DSCI application namespace to be immutable
  apis/dscinitialization/v1/dscinitialization_types.go
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
Labels: lgtm, approved

#1233 chore: simplifies generateCertSecret func
  pkg/cluster/cert.go
Labels: lgtm, approved

#1235 fix(test): makes DSCI-dependent tests self-contained
  tests/envtestutil/name_gen.go
  tests/integration/features/cleanup_int_test.go
  tests/integration/features/fixtures/cluster_test_fixtures.go
  tests/integration/features/manifests_int_test.go
  tests/integration/features/preconditions_int_test.go
  tests/integration/features/resources_int_test.go
  tests/integration/features/serverless_feature_test.go
  tests/integration/features/servicemesh_feature_test.go
  tests/integration/features/tracker_int_test.go
Labels: lgtm, approved, odh-2.18

#1234 refactor(feature): decouples Feature from the client
  components/kserve/kserve_config_handler.go
  components/kserve/servicemesh_setup.go
  controllers/dscinitialization/servicemesh_setup.go
  pkg/feature/builder.go
  pkg/feature/conditions.go
  pkg/feature/feature.go
  pkg/feature/feature_data.go
  pkg/feature/feature_tracker_handler.go
  pkg/feature/handler.go
  pkg/feature/resources.go
  pkg/feature/serverless/conditions.go
  pkg/feature/serverless/resources.go
  pkg/feature/servicemesh/conditions.go
  pkg/feature/servicemesh/resources.go
  tests/integration/features/cleanup_int_test.go
  tests/integration/features/fixtures/cluster_test_fixtures.go
  tests/integration/features/manifests_int_test.go
  tests/integration/features/preconditions_int_test.go
  tests/integration/features/resources_int_test.go
  tests/integration/features/serverless_feature_test.go
  tests/integration/features/servicemesh_feature_test.go
  tests/integration/features/tracker_int_test.go
Labels: lgtm, approved

#1238 chore: cleanup code
  pkg/cluster/cert.go
Labels: lgtm, approved

#1242 test: disable KFTO in e2e
  tests/e2e/helper_test.go
Labels: lgtm, approved

#1248 fix: update DSC/DSCI .status.release not depend on other's reconcile
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
Labels: lgtm, approved

#1249 fix: only replace/set default model reg namespace by webhook if comnent is enabled
  controllers/webhook/webhook.go
Labels: lgtm, approved

#1250 chore: cleanup unnecessary permisison
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/datasciencecluster/kubebuilder_rbac.go
Labels: lgtm, approved

#1241 refactor(webhook): change for mutating webhook to use Default to set ModelReg namespace
  controllers/webhook/webhook.go
  controllers/webhook/webhook_suite_test.go
  main.go
Labels: lgtm, approved

#1236 ci: ensures tests are run on push
  .github/workflows/unit-tests.yaml
Labels: lgtm, approved

#1251 refactor: get platform calls
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/utils.go
  main.go
  pkg/cluster/cluster_operations_int_test.go
  pkg/cluster/cluster_operations_suite_int_test.go
  pkg/upgrade/uninstallation.go
Labels: lgtm, approved, do-not-merge/hold

#1255 chore: reduce more call to get platform
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
Labels: lgtm, approved

#1256 cluster: remove GetPlatform api
  main.go
  pkg/cluster/cluster_config.go
  pkg/cluster/cluster_operations_int_test.go
  pkg/cluster/cluster_operations_suite_int_test.go
Labels: lgtm, approved

#1257 chore: Minor fixes and split pre-release workflow into 2 separate workflows.
  .github/actions/update-release-version/action.yaml
  .github/scripts/get-component-release-notes.js
  .github/scripts/wait-for-checks.sh
  .github/workflows/pre-release.yaml
  .github/workflows/release-e2e-dry-run.yaml
Labels: lgtm, approved

#1261 fix(crd): adds validation pattern and max length for ns fields
  apis/infrastructure/v1/servicemesh_types.go
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  docs/api-overview.md
Labels: lgtm, approved

#1264 components: move logger creation to pkg/logger
  components/README.md
  components/codeflare/codeflare.go
  components/component.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/kueue/kueue.go
  components/modelmeshserving/modelmeshserving.go
  components/modelregistry/modelregistry.go
  components/ray/ray.go
  components/trainingoperator/trainingoperator.go
  components/trustyai/trustyai.go
  components/workbenches/workbenches.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  main.go
  pkg/logger/logger.go
Labels: lgtm, approved

#1265 (fix): ODH release automation: Release notes generation
  .github/scripts/get-component-release-notes.js
  .github/workflows/pre-release.yaml
  .github/workflows/release.yaml
Labels: lgtm, approved

#1266 docs: Update Contribution Guidelines
  CONTRIBUTING.md
  README.md
  docs/troubleshooting.md
Labels: lgtm, approved

#1267 fix: add downstream operator namespace into cache for secret
  main.go
Labels: approved, rhoai-2.14
