Repository opendatahub-io/opendatahub-operator, pull requests merged in 2024-02, with the labels that each got.

#827 feat(kueue): add logic to enable new component
  README.md
  apis/datasciencecluster/v1/datasciencecluster_types.go
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/features.opendatahub.io_featuretrackers.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  components/README.md
  components/component.go
  components/kueue/kueue.go
  components/kueue/zz_generated.deepcopy.go
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/manifests/description-patch.yml
  config/rbac/role.yaml
  config/samples/datasciencecluster_v1_datasciencecluster.yaml
  controllers/datasciencecluster/kubebuilder_rbac.go
  get_all_manifests.sh
  pkg/upgrade/upgrade.go
  tests/e2e/dsc_creation_test.go
  tests/e2e/dsc_deletion_test.go
  tests/e2e/helper_test.go
Labels: lgtm, approved, incubating, component/kueue

#794 Changed variable name for cfo operator image
  components/codeflare/codeflare.go
Labels: lgtm, approved, incubating

#835 fix(kueue): missing deepcopyinto for kueue by re-generate code
  apis/datasciencecluster/v1/zz_generated.deepcopy.go
  components/modelregistry/zz_generated.deepcopy.go
Labels: bug, lgtm, component/kueue

#831 feat: simplifies Feature API
  apis/features/v1/features_types.go
  components/kserve/kserve.go
  components/kserve/serverless_setup.go
  controllers/dscinitialization/servicemesh_setup.go
  pkg/feature/builder.go
  pkg/feature/feature_tracker_handler.go
  pkg/feature/handler.go
  pkg/feature/initializer.go
  pkg/feature/manifest.go
  tests/envtestutil/utils.go
  tests/integration/features/features_int_test.go
  tests/integration/features/features_suite_int_test.go
  tests/integration/features/serverless_feature_test.go
  tests/integration/features/servicemesh_feature_test.go
Labels: lgtm

#839 chore: fixes typos in code and comments
  components/codeflare/codeflare.go
  components/component.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/kserve/serverless_setup.go
  components/kueue/kueue.go
  components/modelmeshserving/modelmeshserving.go
  components/ray/ray.go
  components/workbenches/workbenches.go
  controllers/dscinitialization/servicemesh_setup.go
  controllers/secretgenerator/secretgenerator_controller.go
  pkg/deploy/deploy.go
  pkg/feature/builder.go
  pkg/upgrade/upgrade.go
  tests/envtestutil/cleaner.go
Labels: lgtm

#841 chore(test): simplifies name generations
  tests/envtestutil/name_gen.go
Labels: lgtm

#842 fix(manifests): return walkErr immediately
  pkg/feature/manifest.go
Labels: lgtm

#843 fix: checks value instead of err when updating configmap
  pkg/feature/feature.go
Labels: lgtm

#845 fix(crd): updates docs in crd
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
Labels: lgtm

#846 fix(make): ensures manifests are generated as part of default target
  Makefile
Labels: lgtm

#847 fix(kueue): match var name from build system
  components/kueue/kueue.go
Labels: lgtm, approved, rhoai-2.7

#851 Update manifests for odh 2.7
  Makefile
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Labels: lgtm

#852 Bump Serving components to v0.11.1
  get_all_manifests.sh
Labels: lgtm

#854 Release: ODH 2.7
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  get_all_manifests.sh
Labels: lgtm

#796 Fix: uninstallation for operator
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/datasciencecluster/kubebuilder_rbac.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/suite_test.go
  pkg/deploy/deploy.go
  pkg/upgrade/upgrade.go
  tests/e2e/dsc_cfmap_deletion_test.go
Labels: lgtm, approved, rhoai-2.7

#850 add logic to ensure deprecated model monitoring stack is deleted
  main.go
  pkg/upgrade/upgrade.go
Labels: lgtm, approved, rhoai-2.7, odh-2.8

#855 update: remove duplicated createOdhNamespace call in DSCI
  controllers/dscinitialization/dscinitialization_controller.go
Labels: lgtm

#859 chore: move featuretracker out of feature.spec
  pkg/feature/feature.go
  pkg/feature/feature_tracker_handler.go
  pkg/feature/types.go
Labels: lgtm

#865 update(GH): enabled PR comments by linter bot
  .github/workflows/linter.yaml
Labels: lgtm

#848 Add Trusted Bundle Configmap to all namespaces
  apis/dscinitialization/v1/dscinitialization_types.go
  apis/dscinitialization/v1/zz_generated.deepcopy.go
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  config/samples/dscinitialization_v1_dscinitialization.yaml
  controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/dscinitialization_test.go
  main.go
  pkg/trustedcabundle/trustedcabundle.go
  pkg/upgrade/upgrade.go
  tests/e2e/helper_test.go
Labels: lgtm, approved, odh-2.8

#711 DSC, DSCI: add validating webhook
  Makefile
  PROJECT
  bundle/manifests/opendatahub-operator-webhook-service_v1_service.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/default/kustomization.yaml
  config/default/manager_webhook_patch.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
  controllers/webhook/webhook.go
  controllers/webhook/webhook_suite_test.go
  main.go
  tests/e2e/controller_setup_test.go
  tests/e2e/dsc_creation_test.go
  tests/e2e/helper_test.go
Labels: lgtm, approved, odh-2.8

#868 chore: simplifies k8s client usage in Features
  pkg/cluster/const.go
  pkg/feature/builder.go
  pkg/feature/cert.go
  pkg/feature/conditions.go
  pkg/feature/feature.go
  pkg/feature/raw_resources.go
  pkg/feature/serverless/conditions.go
  pkg/feature/serverless/loaders.go
  pkg/feature/serverless/resources.go
  pkg/feature/servicemesh/conditions.go
  pkg/gvr/gvr.go
  tests/integration/features/features_int_test.go
  tests/integration/features/serverless_feature_test.go
  tests/integration/features/servicemesh_feature_test.go
Labels: lgtm, refactoring

#844 Add Makefile support for add variables overrides to a .env file
  .gitignore
  CONTRIBUTING.md
  Makefile
Labels: lgtm, approved, odh-2.8

#863 feat(nwp): add ingress from cluster-monitoring to applicationnamespace
  controllers/dscinitialization/utils.go
Labels: lgtm, approved, odh-2.8, rhoai-2.8

#784 feat(authz): Authorino for Service Mesh
  apis/dscinitialization/v1/zz_generated.deepcopy.go
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  components/kserve/kserve.go
  components/kserve/servicemesh_setup.go
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/rbac/role.yaml
  controllers/datasciencecluster/kubebuilder_rbac.go
  controllers/dscinitialization/servicemesh_setup.go
  infrastructure/v1/servicemesh_types.go
  infrastructure/v1/zz_generated.deepcopy.go
  pkg/cluster/cluster_config.go
  pkg/feature/builder.go
  pkg/feature/feature.go
  pkg/feature/manifest.go
  pkg/feature/serverless/loaders.go
  pkg/feature/serverless/resources.go
  pkg/feature/servicemesh/cleanup.go
  pkg/feature/servicemesh/conditions.go
  pkg/feature/servicemesh/loaders.go
  pkg/feature/servicemesh/resources.go
  pkg/feature/templates/servicemesh/authorino/auth-smm.tmpl
  pkg/feature/templates/servicemesh/authorino/base/operator-cluster-wide-no-tls.tmpl
  pkg/feature/templates/servicemesh/authorino/deployment.injection.patch.tmpl
  pkg/feature/templates/servicemesh/authorino/mesh-authz-ext-provider.patch.tmpl
  pkg/feature/templates/servicemesh/kserve/activator-envoyfilter.tmpl
  pkg/feature/templates/servicemesh/kserve/envoy-oauth-temp-fix.tmpl
  pkg/feature/templates/servicemesh/kserve/kserve-predictor-authorizationpolicy.tmpl
  pkg/feature/types.go
Labels: approved, odh-2.8

#860 Fix Kserve Unmanaged Installation
  components/kserve/kserve.go
  tests/e2e/dsc_creation_test.go
  tests/e2e/helper_test.go
Labels: rhoai-2.7, odh-2.8

#877 update(modelregistry): rename image name
  components/modelregistry/modelregistry.go
Labels: lgtm, incubating, component/modelregistry

#875 ODH Release 2.8 Version Update
  Makefile
  bundle/manifests/opendatahub-operator-webhook-service_v1_service.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Labels: lgtm

#861 update: add cleanup for rhods-monitor-federation2
  pkg/upgrade/upgrade.go
Labels: lgtm, approved, rhoai-2.8

#869 Update Owners and Owners-aliases
  OWNERS
  OWNERS_ALIASES
Labels: lgtm

#879 fix(DSC): do not reconcile resource if it has a special annotation
  controllers/datasciencecluster/datasciencecluster_controller.go
  pkg/deploy/deploy.go
Labels: lgtm, approved, rhoai-2.8

#882 fix(feature): use correct error variable name
  pkg/feature/feature.go
Labels: lgtm, approved, ok-to-test

#872 feat(dashboard): use new manifests structure from ODH
  components/dashboard/dashboard.go
Labels: lgtm, approved, rhoai-2.8

#864 allow setting default deployment mode for Kserve in DSC
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  components/kserve/kserve.go
  components/kserve/kserve_config_handler.go
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  controllers/datasciencecluster/kubebuilder_rbac.go
  docs/Dev-Preview.md
Labels: lgtm, approved, rhoai-2.8

#881 Revert "RHOAIENG-965: Fix ODH Upgrade after label updates"
  pkg/upgrade/upgrade.go
Labels: lgtm, approved
