Repository opendatahub-io/opendatahub-operator, pull requests merged in 2024-01, with the labels that each got.

#791 Remove LaVLaS from the OWNERS file
  OWNERS
Labels: lgtm, approved

#770 update(dsci): do not create default DSCI CR if it is running in ODH
  README.md
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  controllers/datasciencecluster/datasciencecluster_controller.go
  tests/e2e/controller_setup_test.go
  tests/e2e/dsc_creation_test.go
  tests/e2e/helper_test.go
Labels: lgtm, approved, rhods-2.6

#798 fix(mesh): disables default network policy management
  controllers/dscinitialization/servicemesh_setup.go
  pkg/feature/cert.go
  pkg/feature/feature.go
  pkg/feature/raw_resources.go
  pkg/feature/serverless/conditions.go
  pkg/feature/templates/servicemesh/base/control-plane-disable-networkpolicies.patch.tmpl
  pkg/feature/templates/servicemesh/base/create-smcp.tmpl
  pkg/gvr/gvr.go
  tests/integration/features/crd/openshift-ingresses.crd.yaml
  tests/integration/features/crd/test-resource.crd.yaml
  tests/integration/features/servicemesh_feature_test.go
Labels: lgtm, rhods-2.6

#799 Fix [Snyk][CVE-2022-3064] [High] github.com/go-yaml/yaml - DOS vulnerability
  go.mod
Labels: lgtm

#803 fix: ensures Wait function waits for pods to appear in a given namespace
  pkg/feature/conditions.go
Labels: lgtm

#805 fix(service-mesh): ensures SMCP is available before patching network policy
  controllers/dscinitialization/servicemesh_setup.go
  pkg/feature/builder.go
  pkg/feature/conditions.go
  pkg/feature/feature.go
  pkg/feature/initializer.go
  pkg/feature/manifest.go
  pkg/feature/raw_resources.go
  pkg/feature/servicemesh/conditions.go
  tests/integration/features/servicemesh_feature_test.go
Labels: lgtm

#797 feat(templates): process Feature templates in memory
  components/kserve/serverless_setup.go
  controllers/dscinitialization/servicemesh_setup.go
  pkg/feature/builder.go
  pkg/feature/feature.go
  pkg/feature/manifest.go
  pkg/feature/raw_resources.go
  pkg/feature/template_loader.go
  pkg/feature/templates/serverless/serving-istio-gateways/istio-local-gateway.yaml
  tests/integration/features/crd/istio-gateway.crd.yaml
  tests/integration/features/features_int_test.go
  tests/integration/features/servicemesh_feature_test.go
  tests/integration/features/templates/namespace.yaml
Labels: lgtm, incubating

#801 feat: add status/conditions to FeatureTrackers
  .golangci.yml
  apis/features/v1/features_types.go
  apis/features/v1/zz_generated.deepcopy.go
  config/crd/bases/features.opendatahub.io_featuretrackers.yaml
  controllers/dscinitialization/dscinitialization_controller.go
  pkg/feature/feature.go
  pkg/feature/feature_tracker_handler.go
  pkg/gvr/gvr.go
  tests/e2e/dsc_creation_test.go
  tests/integration/features/features_int_test.go
Labels: lgtm, incubating

#817 fix: fix e2e test error handling for RHOAIENG-2219
  tests/e2e/dsc_creation_test.go
Labels: lgtm, approved

#814 fix(serverless): Patch to enable Secret filtering in KNative Serving
  components/kserve/serverless_setup.go
  pkg/feature/serverless/conditions.go
  pkg/feature/templates/serverless/serving-install/knative-serving.tmpl
  pkg/feature/templates/serverless/serving-net-istio-secret-filtering.patch.tmpl
Labels: lgtm, rhoai-2.7

#823 update(trusty): Change TrustyAI `apiGroup`
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/datasciencecluster/kubebuilder_rbac.go
Labels: lgtm, odh-2.7

#828 revert go mod
  go.mod
Labels: lgtm

#824 [backport]trustyai: monitoring
  components/component.go
  components/trustyai/trustyai.go
  controllers/dscinitialization/monitoring.go
Labels: lgtm, approved, odh-2.7

#822 RHOAIENG-965: Fix ODH Upgrade after label updates
  pkg/upgrade/upgrade.go
Labels: odh-2.7

#816 fix(devFlags): missing overwrite for the devFlag on component level
  components/trustyai/trustyai.go
Labels: lgtm, approved, incubating

#810 [backport](trusty): set to GA
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/samples/datasciencecluster_v1_datasciencecluster.yaml
  docs/DESIGN.md
  docs/Dev-Preview.md
  pkg/upgrade/upgrade.go
Labels: lgtm, approved, odh-2.7

#825 Add openshift ci build root image configuration
  .ci-operator.yaml
Labels: lgtm, approved

#728 Makefile: generate config/manager/kustomization.yaml
  Makefile
  config/manager/kustomization.yaml.in
Labels: lgtm, approved

#730 Makefile: generate default image name based on current user
  Makefile
Labels: lgtm, approved

#735 Makefile: run linter and unit tests from default target
  Makefile
Labels: lgtm, approved
