Repository opendatahub-io/opendatahub-operator, pull requests merged in 2024-08, with the labels that each got.

#1144 chore: renames IngressGatewaySpec type to GatewaySpec
  apis/infrastructure/v1/serverless_types.go
  apis/infrastructure/v1/servicemesh_types.go
  apis/infrastructure/v1/zz_generated.deepcopy.go
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  docs/api-overview.md
  tests/e2e/dsc_creation_test.go
  tests/integration/features/serverless_feature_test.go
Labels: lgtm, approved

#1148 fix(feature): preserves original target namespace
  pkg/feature/builder.go
Labels: lgtm, approved

#1149 chore(service-mesh): exports configmap names to const
  pkg/feature/servicemesh/const.go
  pkg/feature/servicemesh/resources.go
Labels: lgtm, approved

#1150 feat: add managed model registry prometheus config handling logic, fixes RHOAIENG-4273
  components/component.go
  components/modelregistry/modelregistry.go
Labels: lgtm, approved, odh-2.16

#1134 chore: remove UPDATE from webhook operation list
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/webhook/manifests.yaml
  controllers/webhook/webhook.go
Labels: lgtm, approved

#1151 chore: cleanup Warning for unused packages
  go.mod
  go.sum
Labels: lgtm, approved

#1145 upgrade: cleanup CreateWithRetry usage
  pkg/cluster/resources.go
  pkg/upgrade/upgrade.go
Labels: lgtm, approved

#1120 chore: tuning resource usage for operator pod
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: lgtm, approved

#1153 Revert "feat: remove leader election for operator (#1000)"
  bundle/manifests/opendatahub-operator-manager-config_v1_configmap.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/controller_manager_config.yaml
  config/manager/kustomization.yaml.in
  config/manager/manager.yaml
  main.go
Labels: lgtm, approved

#1159 fix(feature): ensures all new resources are created in one reconcile
  pkg/feature/resource/operations.go
  tests/integration/features/fixtures/templates/namespace.yaml
  tests/integration/features/fixtures/templates/namespaces.yaml
  tests/integration/features/manifests_int_test.go
Labels: lgtm, approved

#1162 (chore): Increase timeout for the wait-for-checks.sh script
  .github/scripts/wait-for-checks.sh
Labels: lgtm, approved

#1164 (chore): Comment the 'push version tag to quay.io' step in gh action
  .github/workflows/pre-release.yaml
Labels: lgtm, approved

#1158 chore: uplift kustomize version for match the one from kyaml
  Makefile
Labels: lgtm, approved

#1166 chore(meta): removes map size declaration
  pkg/cluster/meta.go
Labels: lgtm, approved

#1152 doc: correct godoc
  pkg/upgrade/upgrade.go
Labels: lgtm, approved

#1171 set devel log mode when running the operator locally
  Makefile
Labels: lgtm, approved

#1154 [RHOAIENG-10647] - Configure Knative PVC support as default
  components/kserve/resources/serving-install/knative-serving.tmpl.yaml
Labels: lgtm

#1176 feat(make): adds generate to default targets
  Makefile
Labels: lgtm, approved

#1179 kserve: do not call ApplyParams for the empty list
  components/kserve/kserve.go
Labels: lgtm, approved

#1180 update: remove unnecessary param from ApplyParams()
  components/codeflare/codeflare.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/kueue/kueue.go
  components/modelmeshserving/modelmeshserving.go
  components/modelregistry/modelregistry.go
  components/ray/ray.go
  components/trainingoperator/trainingoperator.go
  components/trustyai/trustyai.go
  components/workbenches/workbenches.go
  pkg/deploy/envParams.go
Labels: lgtm, approved

#1182 update: open root group to the same permission as owner
  Dockerfiles/Dockerfile
Labels: lgtm, approved

#1183 fix(serverless): checks if Service Mesh is defined
  components/kserve/kserve_config_handler.go
Labels: lgtm, approved

#1178 deploy: ApplyParams: rewrite with tempfile
  pkg/deploy/envParams.go
Labels: lgtm, approved

#1184 fix(feature): cleanup funcs should not rely on feature's data
  controllers/dscinitialization/servicemesh_setup.go
  pkg/feature/builder.go
  pkg/feature/feature.go
  pkg/feature/feature_tracker_handler.go
  pkg/feature/servicemesh/cleanup.go
  tests/integration/features/servicemesh_feature_test.go
Labels: lgtm, approved

#1187 chore : use grep -E than egrep in make and set min k8s version
  Makefile
  crd-ref-docs.config.yaml
  docs/api-overview.md
Labels: lgtm, approved

#1195 chore: update golangci-lint to v1.60.2, fix misleading test
  .github/workflows/linter.yaml
  Makefile
  tests/e2e/dsc_creation_test.go
Labels: lgtm, approved

#1197 chore: use /usr/bin/env to locate the bash interpreter based on the user's PATH settings.
  get_all_manifests.sh
Labels: lgtm, approved

#1189 upgrade: controller-runtime and code change accordingly
  components/kserve/kserve_config_handler.go
  config/crd/kustomization.yaml
  config/rbac/role.yaml
  controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/datasciencecluster/kubebuilder_rbac.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/suite_test.go
  controllers/secretgenerator/secretgenerator_controller.go
  controllers/webhook/webhook.go
  controllers/webhook/webhook_suite_test.go
  go.mod
  go.sum
  main.go
  pkg/cluster/gvk/gvk.go
  pkg/cluster/operator.go
  pkg/upgrade/upgrade.go
  tests/e2e/controller_setup_test.go
Labels: lgtm, approved

#1193 chore: update alias across code base and set in golint
  .golangci.yml
  controllers/dscinitialization/suite_test.go
  main.go
Labels: lgtm, approved

#1204 test: add operator namespace variable for unit-test
  Makefile
Labels: lgtm, approved

#1165 feat: add default cert for model registry, fixes RHOAIENG-9909
  components/modelregistry/modelregistry.go
  tests/e2e/dsc_creation_test.go
Labels: lgtm, approved, priority/high

#1202 feat: add servicemeshmember for model registry namespace, fixes RHOAIENG-11831
  components/modelregistry/modelregistry.go
  components/modelregistry/resources/servicemesh-member.tmpl.yaml
  tests/e2e/dsc_creation_test.go
Labels: lgtm, approved

#1172 feat: add predicates on deployment
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  pkg/deploy/deploy.go
Labels: lgtm, approved

#1206 deps: uplift crd-ref-docs to 0.1.0
  Makefile
  docs/api-overview.md
Labels: lgtm, approved

#1188 docs: update old docs
  README.md
  docs/DESIGN.md
  docs/troubleshooting.md
  docs/upgrade-testing.md
Labels: lgtm, approved

#1205 fix: add check for all platform offering on components
  Makefile
  components/codeflare/codeflare.go
  components/dashboard/dashboard.go
  components/datasciencepipelines/datasciencepipelines.go
  components/kserve/kserve.go
  components/kueue/kueue.go
  components/modelmeshserving/modelmeshserving.go
  components/modelregistry/modelregistry.go
  components/ray/ray.go
  components/trainingoperator/trainingoperator.go
  components/trustyai/trustyai.go
  components/workbenches/workbenches.go
  pkg/cluster/resources.go
  tests/e2e/controller_setup_test.go
  tests/e2e/dsc_creation_test.go
Labels: lgtm, approved

#1207 feat: set ModelReg and KFTO default to Managed in ODH
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/samples/datasciencecluster_v1_datasciencecluster.yaml
  pkg/upgrade/upgrade.go
Labels: lgtm, approved

#1170 Don't restrict the nbc image update to downstream only
  components/workbenches/workbenches.go
Labels: lgtm, approved

#1186 deploy: ApplyParams: do not write params.env if there are no updates
  pkg/deploy/envParams.go
Labels: lgtm, approved

#1203 chore: remove dead code
  controllers/dscinitialization/dscinitialization_controller.go
Labels: lgtm, approved

#1208 test: update e2e testcases
  tests/e2e/cfmap_deletion_test.go
  tests/e2e/controller_test.go
  tests/e2e/creation_test.go
  tests/e2e/deletion_test.go
  tests/e2e/helper_test.go
  tests/e2e/odh_manager_test.go
Labels: lgtm, approved
