Repository opendatahub-io/opendatahub-operator, pull requests merged in 2025-10, with the labels that each got.

#2573 fix: add llmisvc kueue test case
  internal/webhook/hardwareprofile/integration_test.go
Labels: lgtm, approved, team-crucible

#2581 ODH Release 2.35.0: Update release branch
  Dockerfiles/bundle.Dockerfile
  Makefile
  PROJECT
  api/components/v1alpha1/modelregistry_types.go
  api/components/v1alpha1/workbenches_types.go
  api/dscinitialization/v1/dscinitialization_types.go
  api/services/v1alpha1/monitoring_types.go
  bundle/manifests/components.platform.opendatahub.io_modelregistries.yaml
  bundle/manifests/components.platform.opendatahub.io_workbenches.yaml
  bundle/manifests/controller-manager-metrics-service_v1_service.yaml
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  bundle/manifests/services.platform.opendatahub.io_monitorings.yaml
  bundle/manifests/webhook-service_v1_service.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/components.platform.opendatahub.io_modelregistries.yaml
  config/crd/bases/components.platform.opendatahub.io_workbenches.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/crd/bases/services.platform.opendatahub.io_monitorings.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_webhook_patch.yaml
  config/manager/manager.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/rhods-operator.clusterserviceversion.yaml
  config/manifests/kustomization.yaml
  config/monitoring/networkpolicy/monitoring/monitoring.yaml
  config/monitoring/networkpolicy/operator/operator.yaml
  config/monitoring/prometheus/apps/prometheus-configs.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/datasciencecluster_datasciencecluster_editor_role.yaml
  config/rbac/datasciencecluster_datasciencecluster_viewer_role.yaml
  config/rbac/dscinitialization_dscinitialization_editor_role.yaml
  config/rbac/dscinitialization_dscinitialization_viewer_role.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  config/samples/datasciencecluster_v1_datasciencecluster.yaml
  config/samples/dscinitialization_v1_dscinitialization.yaml
  config/webhook/kustomization.yaml
  config/webhook/service.yaml
  docs/api-overview.md
  get_all_manifests.sh
  internal/controller/components/modelregistry/modelregistry_support.go
  tests/e2e/controller_test.go
Labels: lgtm, approved

#2576 cleanup unused referencegrant gvk code
  pkg/cluster/gvk/gvk.go
Labels: lgtm, approved

#2592 [Rhoai] All Gateway cherry picks
  api/services/v1alpha1/gateway_types.go
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  bundle/manifests/services.platform.opendatahub.io_gatewayconfigs.yaml
  config/crd/bases/services.platform.opendatahub.io_gatewayconfigs.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  docs/api-overview.md
  internal/controller/components/dashboard/dashboard_controller_actions.go
  internal/controller/components/dashboard/dashboard_support.go
  internal/controller/components/dashboard/dashboard_test.go
  internal/controller/components/datasciencepipelines/datasciencepipelines_support.go
  internal/controller/components/kserve/kserve_support.go
  internal/controller/components/modelregistry/modelregistry_support.go
  internal/controller/components/trustyai/trustyai_support.go
  internal/controller/components/workbenches/workbenches.go
  internal/controller/dscinitialization/kubebuilder_rbac.go
  internal/controller/services/gateway/gateway_auth_actions.go
  internal/controller/services/gateway/gateway_controller.go
  internal/controller/services/gateway/gateway_controller_actions.go
  internal/controller/services/gateway/gateway_controller_actions_test.go
  internal/controller/services/gateway/gateway_controller_test.go
  internal/controller/services/gateway/gateway_support.go
  internal/controller/services/gateway/gateway_support_test.go
  internal/controller/services/gateway/resources/destinationrule-tls.yaml
  internal/controller/services/gateway/resources/envoyfilter-authn.yaml
  pkg/cluster/gvk/gvk.go
Labels: lgtm, approved

#2582 Update golangci-lint to v2.5.0
  .golangci.yml
  Makefile
  internal/controller/components/dashboard/dashboard_controller_actions.go
  internal/webhook/envtestutil/envtestutil.go
  internal/webhook/notebook/mutating_test.go
  pkg/cluster/cluster_config_test.go
  pkg/controller/actions/cacher/cacher_test.go
  pkg/controller/actions/gc/action_gc_test.go
  pkg/controller/actions/resourcecacher/resourcecacher.go
  pkg/controller/actions/resourcecacher/resourcecacher_test.go
  pkg/controller/predicates/dependent/dependent.go
  pkg/controller/predicates/partial/partial.go
  pkg/utils/test/envt/envt.go
  pkg/utils/test/testf/testf_witht.go
  tests/e2e/cfmap_deletion_test.go
  tests/e2e/components_test.go
Labels: lgtm, approved

#2594 chore: fix api version
  PROJECT
  pkg/upgrade/upgrade.go
Labels: lgtm, approved

#2600 Update golangci-lint to v2.5.0
  .golangci.yml
  Makefile
  internal/controller/components/dashboard/dashboard_controller_actions.go
  internal/webhook/envtestutil/envtestutil.go
  internal/webhook/notebook/mutating_test.go
  pkg/cluster/cluster_config_test.go
  pkg/controller/actions/cacher/cacher_test.go
  pkg/controller/actions/gc/action_gc_test.go
  pkg/controller/actions/resourcecacher/resourcecacher.go
  pkg/controller/actions/resourcecacher/resourcecacher_test.go
  pkg/controller/predicates/dependent/dependent.go
  pkg/controller/predicates/partial/partial.go
  pkg/utils/test/envt/envt.go
  pkg/utils/test/testf/testf_witht.go
  tests/e2e/authcontroller_test.go
  tests/e2e/cfmap_deletion_test.go
  tests/e2e/components_test.go
Labels: lgtm, approved

#2602 RHOAIENG-33891: DSC v1 should not be created or updated with Kueue component state set to Managed
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  config/webhook/manifests.yaml
  internal/webhook/datasciencecluster/v1/defaulting.go
  internal/webhook/datasciencecluster/v1/register.go
  internal/webhook/datasciencecluster/v1/validating.go
  internal/webhook/datasciencecluster/v1/validating_test.go
  internal/webhook/datasciencecluster/v2/defaulting.go
  internal/webhook/datasciencecluster/v2/validating.go
  internal/webhook/dscinitialization/v1/validating.go
  internal/webhook/dscinitialization/v2/validating.go
  pkg/webhook/utils.go
  tests/e2e/v2tov3upgrade_test.go
Labels: lgtm, approved

#2605 Add kube-linter to checks Kubernetes manifests against various best practices, with a focus on production readiness and security
  .github/workflows/linter.yaml
  .kube-linter.yaml
  Makefile
Labels: lgtm, approved

#2607 chore: Update GitHub workflows and issue labels and fix bug
  .github/issue_label_bot.yaml
  .github/workflows/ci-build-push-e2e-tests.yaml
  .github/workflows/ci-build-push-images-on-pr.yaml
  .github/workflows/pr-comment-on-e2e-check.yaml
  .github/workflows/pr-comment-test-trigger.yaml
  .github/workflows/pr-comment.yaml
  .github/workflows/release-process-fbc-fragment.yaml
  .github/workflows/test-e2e-requirement-check.yaml
  .github/workflows/test-integration.yaml
  .github/workflows/test-linter.yaml
  .github/workflows/test-prometheus-unit.yaml
  .github/workflows/test-required-files-updated.yaml
  .github/workflows/test-unit.yaml
  CONTRIBUTING.md
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  crd-ref-docs.config.yaml
  docs/api-overview.md
Labels: lgtm, approved

#2596 RHOAIENG-34045: cleanup codeflare manifests, remove codeflare from DSC v2
  PROJECT
  README.md
  api/components/v1alpha1/codeflare_types.go
  api/components/v1alpha1/zz_generated.deepcopy.go
  api/datasciencecluster/v1/datasciencecluster_conversion.go
  api/datasciencecluster/v2/datasciencecluster_types.go
  api/datasciencecluster/v2/zz_generated.deepcopy.go
  bundle/manifests/components.platform.opendatahub.io_codeflares.yaml
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/crd/bases/components.platform.opendatahub.io_codeflares.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/kustomization.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/description-patch.yml
  config/monitoring/prometheus/apps/prometheus-configs.yaml
  config/rbac/components_codeflare_editor_role.yaml
  config/rbac/components_codeflare_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/datasciencecluster_v1_datasciencecluster.yaml
  config/samples/datasciencecluster_v2_datasciencecluster.yaml
  crd-ref-docs.config.yaml
  docs/DESIGN.md
  docs/api-overview.md
  docs/upgrade-testing.md
  internal/controller/datasciencecluster/kubebuilder_rbac.go
  pkg/upgrade/upgrade.go
  tests/e2e/creation_test.go
  tests/e2e/helper_test.go
  tests/e2e/resilience_test.go
  tests/e2e/v2tov3upgrade_test.go
Labels: lgtm, approved, team-forge

#2609 chore: remove placeholder CRD and skip kubebuilder for dashboard actions
  config/crd/bases/_.yaml
  internal/controller/components/dashboard/dashboard_controller_actions.go
Labels: lgtm, approved

#2540 Use commit sha in manifest file
  .github/scripts/update-manifests-commit-sha.js
  .github/workflows/ci-build-push-images-on-pr.yaml
  .github/workflows/release-process-fbc-fragment.yaml
  .github/workflows/release-staging.yaml
  .github/workflows/test-e2e-requirement-check.yaml
  .github/workflows/test-integration.yaml
  .github/workflows/test-linter.yaml
  .github/workflows/test-prometheus-unit.yaml
  .github/workflows/test-required-files-updated.yaml
  .github/workflows/test-unit.yaml
  .github/workflows/update-manifest-shas.yml
  docs/AUTOMATED_MANIFEST_UPDATES.md
  get_all_manifests.sh
Labels: lgtm, approved

#2621 [sync] feat(e2e): improve test framework resilience and fix monitoring controller cleanup
  internal/controller/services/monitoring/monitoring_controller.go
  internal/controller/services/monitoring/monitoring_controller_actions.go
  pkg/utils/test/testf/testf_witht.go
  pkg/utils/test/testf/testf_witht_test.go
  tests/e2e/authcontroller_test.go
  tests/e2e/cfmap_deletion_test.go
  tests/e2e/components_test.go
  tests/e2e/controller_test.go
  tests/e2e/creation_test.go
  tests/e2e/dashboard_test.go
  tests/e2e/datasciencepipelines_test.go
  tests/e2e/helper_test.go
  tests/e2e/kserve_test.go
  tests/e2e/kueue_test.go
  tests/e2e/modelcontroller_test.go
  tests/e2e/monitoring_test.go
  tests/e2e/resilience_test.go
  tests/e2e/resource_fetcher_test.go
  tests/e2e/resource_options_test.go
  tests/e2e/test_context_test.go
  tests/e2e/trustyai_test.go
  tests/e2e/v2tov3upgrade_test.go
Labels: lgtm, approved

#2364 RHOAIENG-27707: e2e for reconciliation resilience
  pkg/resources/resources.go
  tests/e2e/resilience_test.go
  tests/e2e/resource_applier_test.go
Labels: lgtm, approved
