Repository opendatahub-io/opendatahub-operator, pull requests merged in 2025-03, with the labels that each got.

#1707 [sync] feat(mc): add model registry controller feature gate in model controller (#1682)
  apis/components/v1alpha1/modelcontroller_types.go
  apis/components/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/components.platform.opendatahub.io_modelcontrollers.yaml
  config/crd/bases/components.platform.opendatahub.io_modelcontrollers.yaml
  controllers/components/modelcontroller/modelcontroller.go
  controllers/components/modelcontroller/modelcontroller_actions.go
  docs/api-overview.md
  tests/e2e/modelcontroller_test.go
Labels: lgtm, approved, rhoai

#1700 fix auth tests for RHOAI
  tests/e2e/authcontroller_test.go
Labels: lgtm, approved, testing

#1684 Report reconciliation errors as part of the component' status
  Makefile
  controllers/components/codeflare/codeflare_controller.go
  controllers/components/codeflare/codeflare_support.go
  controllers/components/dashboard/dashboard_controller.go
  controllers/components/dashboard/dashboard_support.go
  controllers/components/datasciencepipelines/datasciencepipelines_controller.go
  controllers/components/datasciencepipelines/datasciencepipelines_controller_actions.go
  controllers/components/datasciencepipelines/datasciencepipelines_support.go
  controllers/components/feastoperator/feastoperator_controller.go
  controllers/components/feastoperator/feastoperator_support.go
  controllers/components/kserve/kserve.go
  controllers/components/kserve/kserve_controller.go
  controllers/components/kserve/kserve_controller_actions.go
  controllers/components/kserve/kserve_support.go
  controllers/components/kueue/kueue_controller.go
  controllers/components/kueue/kueue_controller_actions.go
  controllers/components/kueue/kueue_support.go
  controllers/components/modelcontroller/modelcontroller_controller.go
  controllers/components/modelcontroller/modelcontroller_support.go
  controllers/components/modelmeshserving/modelmeshserving_controller.go
  controllers/components/modelmeshserving/modelmeshserving_support.go
  controllers/components/modelregistry/modelregistry_controller.go
  controllers/components/modelregistry/modelregistry_controller_actions.go
  controllers/components/modelregistry/modelregistry_support.go
  controllers/components/ray/ray_controller.go
  controllers/components/ray/ray_support.go
  controllers/components/trainingoperator/trainingoperator_controller.go
  controllers/components/trainingoperator/trainingoperator_support.go
  controllers/components/trustyai/trustyai_controller.go
  controllers/components/trustyai/trustyai_controller_actions.go
  controllers/components/trustyai/trustyai_support.go
  controllers/components/workbenches/workbenches_controller.go
  controllers/components/workbenches/workbenches_support.go
  controllers/services/auth/auth_controller.go
  controllers/services/auth/auth_controller_actions.go
  controllers/services/monitoring/monitoring.go
  controllers/services/monitoring/monitoring_controller.go
  controllers/services/monitoring/monitoring_controller_actions.go
  controllers/status/status.go
  pkg/controller/actions/actions.go
  pkg/controller/actions/deploy/action_deploy.go
  pkg/controller/actions/deploy/action_deploy_support.go
  pkg/controller/actions/status/deployments/action_deployments_available.go
  pkg/controller/actions/status/deployments/action_deployments_available_test.go
  pkg/controller/conditions/conditions.go
  pkg/controller/conditions/conditions_support.go
  pkg/controller/conditions/conditions_support_test.go
  pkg/controller/conditions/conditions_test.go
  pkg/controller/predicates/dependent/dependent.go
  pkg/controller/reconciler/reconciler.go
  pkg/controller/reconciler/reconciler_support.go
  pkg/controller/reconciler/reconciler_test.go
  pkg/controller/types/types.go
  pkg/services/gc/gc.go
  tests/e2e/components_test.go
  tests/e2e/datasciencepipelines_test.go
  tests/e2e/kserve_test.go
  tests/e2e/modelregistry_test.go
  tests/e2e/trustyai_test.go
Labels: lgtm, approved

#1674 [sync] Fix auth CR creation & RHOAI metrics
  config/monitoring/prometheus/apps/prometheus-configs.yaml
  controllers/dscinitialization/auth.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/services/auth/auth_controller.go
  controllers/services/auth/auth_controller_actions.go
  tests/e2e/authcontroller_test.go
Labels: lgtm, approved

#1708 (chore): update currently integrated component list
  docs/COMPONENT_INTEGRATION.md
Labels: lgtm, approved

#1705 Added prometheus config for feast operator component
  config/monitoring/prometheus/apps/prometheus-configs.yaml
  controllers/services/monitoring/monitoring.go
  controllers/services/monitoring/monitoring_controller_actions.go
  tests/prometheus_unit_tests/feast-operator-alerting.unit-tests.yaml
Labels: lgtm, rhoai-2.19

#1712 Refactor feature manifests test and remove dependdency on the afero lib
  go.mod
  go.sum
  pkg/feature/manifest/manifest_suite_test.go
  pkg/feature/manifest/manifest_test.go
  pkg/feature/manifest/resources/raw/my-configmap.yaml
  pkg/feature/manifest/resources/template/my-configmap.tmpl.yaml
Labels: lgtm, approved, dependencies

#1713 chore(deps): remove dependency on kube-aggregator as the related types are not used
  go.mod
  go.sum
  main.go
Labels: lgtm, approved, dependencies

#1715 chore(deps): remove dependency on github.com/pkg/errors and swith to go recommended error wrapping functions
  controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go
  go.mod
  pkg/cluster/cert.go
  pkg/controller/client/client.go
  pkg/feature/servicemesh/conditions.go
Labels: lgtm, approved, dependencies

#1714 chore(deps): remove dependency on addon-operator APIs as the related types are not used
  go.mod
  go.sum
  main.go
Labels: lgtm, approved, dependencies

#1717 chore(tools): use go 1.22 for component-codegen
  cmd/component-codegen/go.mod
Labels: lgtm, approved

#1716 chore(deps): remove dependency on gopkg.in/yaml.v2 and use gopkg.in/yaml.v3
  controllers/services/monitoring/monitoring.go
  go.mod
Labels: lgtm, approved, dependencies

#1605 Improve conditions reporting
  apis/datasciencecluster/v1/datasciencecluster_types.go
  apis/datasciencecluster/v1/zz_generated.deepcopy.go
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  controllers/components/codeflare/codeflare.go
  controllers/components/dashboard/dashboard.go
  controllers/components/datasciencepipelines/datasciencepipelines.go
  controllers/components/feastoperator/feastoperator.go
  controllers/components/kserve/kserve.go
  controllers/components/kueue/kueue.go
  controllers/components/modelcontroller/modelcontroller.go
  controllers/components/modelmeshserving/modelmeshserving.go
  controllers/components/modelregistry/modelregistry.go
  controllers/components/ray/ray.go
  controllers/components/trainingoperator/trainingoperator.go
  controllers/components/trustyai/trustyai.go
  controllers/components/workbenches/workbenches.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/datasciencecluster/datasciencecluster_controller_actions.go
  controllers/datasciencecluster/datasciencecluster_controller_support.go
  docs/api-overview.md
  main.go
  pkg/componentsregistry/componentsregistry.go
  pkg/controller/conditions/conditions_support.go
  tests/e2e/components_test.go
  tests/e2e/workbenches_test.go
Labels: lgtm, approved

#1711 [sync] update: monitoring config (#1676)
  apis/dscinitialization/v1/dscinitialization_types.go
  apis/services/v1alpha1/monitoring_types.go
  apis/services/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/services.platform.opendatahub.io_monitorings.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/crd/bases/services.platform.opendatahub.io_monitorings.yaml
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/dscinitialization_test.go
  controllers/dscinitialization/utils.go
  controllers/webhook/webhook_suite_test.go
  docs/api-overview.md
  main.go
  pkg/upgrade/upgrade.go
  tests/e2e/helper_test.go
Labels: approved, rhoai

#1710 [sync] Add feast operator component + Promethus config
  README.md
  apis/components/v1alpha1/feastoperator_types.go
  apis/components/v1alpha1/zz_generated.deepcopy.go
  apis/datasciencecluster/v1/datasciencecluster_types.go
  apis/datasciencecluster/v1/zz_generated.deepcopy.go
  bundle/manifests/components.platform.opendatahub.io_feastoperators.yaml
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  config/crd/bases/components.platform.opendatahub.io_feastoperators.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/kustomization.yaml
  config/monitoring/prometheus/apps/prometheus-configs.yaml
  config/rbac/role.yaml
  config/samples/datasciencecluster_v1_datasciencecluster.yaml
  controllers/components/feastoperator/feastoperator.go
  controllers/components/feastoperator/feastoperator_controller.go
  controllers/components/feastoperator/feastoperator_controller_actions.go
  controllers/components/feastoperator/feastoperator_support.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/datasciencecluster/kubebuilder_rbac.go
  controllers/services/monitoring/monitoring.go
  controllers/services/monitoring/monitoring_controller_actions.go
  controllers/webhook/webhook_suite_test.go
  docs/DESIGN.md
  docs/api-overview.md
  docs/upgrade-testing.md
  get_all_manifests.sh
  main.go
  pkg/cluster/gvk/gvk.go
  pkg/upgrade/upgrade.go
  tests/e2e/controller_test.go
  tests/e2e/feastoperator_test.go
  tests/e2e/helper_test.go
  tests/e2e/odh_manager_test.go
  tests/prometheus_unit_tests/feast-operator-alerting.unit-tests.yaml
Labels: approved, rhoai-2.19

#1706 [sync] update: change ossm sidecar as labels on authornio deployment (#1702)
  controllers/dscinitialization/resources/authorino/deployment.injection.patch.tmpl.yaml
  controllers/dscinitialization/servicemesh_setup.go
Labels: lgtm, approved, rhoai

#1718 Improve controller-runtime cache configuration
  controllers/dscinitialization/utils.go
  main.go
Labels: lgtm, approved

#1720 [rhoai] Improve test framework
  pkg/utils/test/envt/envt.go
  pkg/utils/test/fakeclient/fakeclient.go
  pkg/utils/test/mocks/types.go
  pkg/utils/test/scheme/scheme.go
  pkg/utils/test/testf/testf.go
Labels: lgtm, approved, rhoai

#1699 chore: cleanup old patch on envoyfilter
  controllers/components/kserve/kserve_support.go
  controllers/components/kserve/resources/servicemesh/envoy-oauth-temp-fix.tmpl.yaml
Labels: lgtm

#1726 chore: hide feast from UI
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  config/manifests/bases/rhods-operator.clusterserviceversion.yaml
Labels: lgtm, approved, rhoai-2.19

#1729 [sync] chore: add FeastOperator to PROJECT file
  PROJECT
Labels: lgtm, approved

#1727 fix: add back CM odh-segment-key-config for Self-Managed cluster
  controllers/dscinitialization/dscinitialization_controller.go
Labels: lgtm, approved

#1722 [rhoai] Improve controller-runtime cache configuration
  controllers/dscinitialization/utils.go
  main.go
Labels: lgtm, approved, rhoai

#1725 chore(gc): prevent redundant deletion of resources already marked for termination
  pkg/controller/actions/gc/action_gc_test.go
  pkg/services/gc/gc.go
Labels: lgtm, approved

#1696 test: enable install authorino-operator in e2e
  tests/e2e/helper_test.go
Labels: approved

#1730 [rhoai] Improve gc service/action
  pkg/controller/actions/gc/action_gc.go
  pkg/controller/actions/gc/action_gc_support.go
  pkg/controller/actions/gc/action_gc_test.go
  pkg/resources/resources.go
  pkg/services/gc/gc.go
Labels: lgtm, approved, rhoai

#1721 Add github.com/openshift/api/oauth/v1 to the default schema list
  pkg/utils/test/scheme/scheme.go
Labels: lgtm, approved

#1724 [sync] chore: cleanup old patch on envoyfilter (#1699)
  controllers/components/kserve/kserve_support.go
  controllers/components/kserve/resources/servicemesh/envoy-oauth-temp-fix.tmpl.yaml
Labels: lgtm, approved, rhoai

#1737 [rhoai] ensure components are turned off at the end of the related test suite
  tests/e2e/codeflare_test.go
  tests/e2e/datasciencepipelines_test.go
  tests/e2e/kueue_test.go
  tests/e2e/modelregistry_test.go
  tests/e2e/ray_test.go
  tests/e2e/trainingoperator_test.go
  tests/e2e/trustyai_test.go
Labels: lgtm, approved, rhoai

#1736 fix: set DSC.status.release
  controllers/datasciencecluster/datasciencecluster_controller_actions.go
Labels: lgtm, approved

#1735 [rhoai] enable release component info for feast
  apis/components/v1alpha1/feastoperator_types.go
  apis/components/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/components.platform.opendatahub.io_feastoperators.yaml
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/bases/components.platform.opendatahub.io_feastoperators.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  controllers/components/feastoperator/feastoperator_controller.go
  docs/api-overview.md
  tests/e2e/feastoperator_test.go
Labels: lgtm, approved, rhoai

#1739 DSC not showing all the negative MissingOperator conditions for kserve
  controllers/components/kserve/kserve_controller.go
  controllers/components/kserve/kserve_controller_actions.go
  controllers/components/kserve/kserve_controller_actions_test.go
  controllers/components/kserve/kserve_support.go
  pkg/cluster/gvk/gvk.go
  pkg/utils/test/scheme/scheme.go
Labels: lgtm, approved

#1734 [rhoai] componentsregistry: use structure to store handlers
  controllers/datasciencecluster/datasciencecluster_controller.go
  pkg/componentsregistry/componentsregistry.go
Labels: lgtm, approved, rhoai

#1741 [rhoai] added finalizer logic
  pkg/controller/reconciler/reconciler.go
  pkg/controller/reconciler/reconciler_finalizer_test.go
Labels: lgtm, approved, rhoai

#1733 [sync] test: add dependent operator namespace when install them + install authorino-operator in e2e
  tests/e2e/controller_test.go
  tests/e2e/helper_test.go
Labels: approved, testing, rhoai

#1743 fix: add missing port in the podmonitor
  controllers/dscinitialization/resources/metrics-collection/envoy-metrics-collection.tmpl.yaml
Labels: lgtm

#1745 [sync]fix: add missing port in the podmointor (#1743)
  controllers/dscinitialization/resources/metrics-collection/envoy-metrics-collection.tmpl.yaml
Labels: lgtm, rhoai

#1747 Refactor the gc action/service
  controllers/datasciencecluster/datasciencecluster_controller_actions.go
  main.go
  pkg/controller/actions/actions_support.go
  pkg/controller/actions/gc/action_gc.go
  pkg/controller/actions/gc/action_gc_test.go
  pkg/controller/actions/gc/engine/gc_engine.go
  pkg/controller/actions/gc/engine/gc_engine_support.go
  pkg/controller/actions/gc/engine/gc_engine_test.go
  pkg/controller/actions/status/deployments/action_deployments_available.go
Labels: lgtm, approved

#1744 feat: add REGISTRIES_NAMESPACE param for model registry, fixes RHOAIENG-21660
  controllers/components/modelregistry/modelregistry_controller.go
  controllers/components/modelregistry/modelregistry_controller_actions.go
Labels: lgtm, approved

#1759 update: variable name from cpaas is set to RELATED_IMAGE_ODH_FEAST_SERVER_IMAGE
  controllers/components/feastoperator/feastoperator_support.go
Labels: lgtm, approved, rhoai-2.19

#1763 [sync] update: variable name from cpaas is set to RELATED_IMAGE_ODH_FEATURE_SERVER_IMAGE(#1759)
  controllers/components/feastoperator/feastoperator_support.go
Labels: lgtm, approved

#1762 ODH/RHOAI Operator does not retry when DSCI fails to create operator resources
  controllers/dscinitialization/dscinitialization_controller.go
Labels: lgtm, approved

#1760 chore: remove Ginkgo v1 and retain only Ginkgo v2
  controllers/components/suite_test.go
  controllers/services/suite_test.go
  go.mod
  go.sum
Labels: lgtm, approved

#1766 RHOAI-21888 - DSCi errors with 'unable to get: opendatahub/redhat-ods…
  main.go
Labels: lgtm, approved

#1752 Ensure testf methods respect the configured timeout/polling settings
  pkg/utils/test/testf/testf_assertions.go
  pkg/utils/test/testf/testf_witht.go
  pkg/utils/test/testf/testf_witht_test.go
Labels: lgtm, approved

#1521 Remove FeatureTracker code from Kserve reconciler
  controllers/components/kserve/feature_resources.go
  controllers/components/kserve/kserve_controller.go
  controllers/components/kserve/kserve_controller_actions.go
  controllers/components/kserve/kserve_support.go
  controllers/components/kserve/resources/servicemesh/activator-envoyfilter.tmpl.yaml
  controllers/components/kserve/resources/servicemesh/kserve-inferencegraph-authorizationpolicy.tmpl.yaml
  controllers/components/kserve/resources/servicemesh/kserve-inferencegraph-envoyfilter.tmpl.yaml
  controllers/components/kserve/resources/servicemesh/kserve-predictor-authorizationpolicy.tmpl.yaml
  controllers/components/kserve/resources/servicemesh/routing/istio-ingress-gateway.tmpl.yaml
  controllers/components/kserve/resources/servicemesh/routing/istio-kserve-local-gateway.tmpl.yaml
  controllers/components/kserve/resources/servicemesh/routing/istio-local-gateway.yaml
  controllers/components/kserve/resources/servicemesh/routing/kserve-local-gateway-svc.tmpl.yaml
  controllers/components/kserve/resources/servicemesh/routing/local-gateway-svc.tmpl.yaml
  controllers/components/kserve/resources/serving-install/knative-serving.tmpl.yaml
  controllers/components/kserve/resources/serving-install/service-mesh-subscription.tmpl.yaml
  controllers/components/kserve/resources/serving-net-istio-secret-filtering.patch.tmpl.yaml
  pkg/cluster/gvk/gvk.go
  pkg/controller/actions/deploy/action_deploy_support.go
  pkg/metadata/labels/types.go
  tests/e2e/kserve_test.go
Labels: lgtm, approved

#1750 chore: Remove/replace deprecated linters
  .golangci.yml
  Makefile
  pkg/utils/test/testf/testf.go
  pkg/utils/test/testf/testf_assertions.go
Labels: lgtm, approved

#1775 Add kahowell to platform team in OWNERS_ALIASES
  OWNERS_ALIASES
Labels: lgtm

#1769 [sync] chore: remove Ginkgo v1 and retain only Ginkgo v2
  controllers/components/suite_test.go
  controllers/services/suite_test.go
  go.mod
  go.sum
Labels: lgtm, approved

#1772 [sync] Remove FeatureTracker code from Kserve reconciler
  controllers/components/kserve/feature_resources.go
  controllers/components/kserve/kserve_controller.go
  controllers/components/kserve/kserve_controller_actions.go
  controllers/components/kserve/kserve_support.go
  controllers/components/kserve/resources/servicemesh/activator-envoyfilter.tmpl.yaml
  controllers/components/kserve/resources/servicemesh/kserve-inferencegraph-authorizationpolicy.tmpl.yaml
  controllers/components/kserve/resources/servicemesh/kserve-inferencegraph-envoyfilter.tmpl.yaml
  controllers/components/kserve/resources/servicemesh/kserve-predictor-authorizationpolicy.tmpl.yaml
  controllers/components/kserve/resources/servicemesh/routing/istio-ingress-gateway.tmpl.yaml
  controllers/components/kserve/resources/servicemesh/routing/istio-kserve-local-gateway.tmpl.yaml
  controllers/components/kserve/resources/servicemesh/routing/istio-local-gateway.yaml
  controllers/components/kserve/resources/servicemesh/routing/kserve-local-gateway-svc.tmpl.yaml
  controllers/components/kserve/resources/servicemesh/routing/local-gateway-svc.tmpl.yaml
  controllers/components/kserve/resources/serving-install/knative-serving.tmpl.yaml
  controllers/components/kserve/resources/serving-install/service-mesh-subscription.tmpl.yaml
  controllers/components/kserve/resources/serving-net-istio-secret-filtering.patch.tmpl.yaml
  controllers/datasciencecluster/datasciencecluster_controller_actions.go
  main.go
  pkg/cluster/gvk/gvk.go
  pkg/controller/actions/actions_support.go
  pkg/controller/actions/deploy/action_deploy_support.go
  pkg/controller/actions/gc/action_gc.go
  pkg/controller/actions/gc/action_gc_test.go
  pkg/controller/actions/gc/engine/gc_engine.go
  pkg/controller/actions/gc/engine/gc_engine_support.go
  pkg/controller/actions/gc/engine/gc_engine_test.go
  pkg/controller/actions/status/deployments/action_deployments_available.go
  pkg/metadata/labels/types.go
  pkg/utils/test/matchers/jq/jq_support.go
  pkg/utils/test/matchers/jq/jq_support_test.go
  pkg/utils/test/testf/testf_witht_test.go
  tests/e2e/kserve_test.go
Labels: lgtm, approved

#1754 [sync]feat: add REGISTRIES_NAMESPACE param for model registry, fixes RHOAIENG-21660 (#1744)
  controllers/components/modelregistry/modelregistry_controller.go
  controllers/components/modelregistry/modelregistry_controller_actions.go
Labels: lgtm, rhoai-2.19

#1757 feat(actions): support globs in template rendering; add labels and annotations
  pkg/controller/actions/render/template/action_render_templates.go
  pkg/controller/actions/render/template/action_render_templates_test.go
  pkg/controller/actions/render/template/resources/g/sm-01.yaml
  pkg/controller/actions/render/template/resources/g/sm-02.yaml
  pkg/controller/types/types.go
Labels: lgtm, approved

#1709 (feat): Add migration logic for odhdashboardconfig
  main.go
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_test.go
Labels: lgtm, approved

#1777 chore: Fix markdown in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: lgtm, approved

#1782 [rhoai] Revert feast in RHOAI
  README.md
  apis/components/v1alpha1/feastoperator_types.go
  apis/components/v1alpha1/zz_generated.deepcopy.go
  apis/datasciencecluster/v1/datasciencecluster_types.go
  apis/datasciencecluster/v1/zz_generated.deepcopy.go
  bundle/manifests/components.platform.opendatahub.io_feastoperators.yaml
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  config/crd/bases/components.platform.opendatahub.io_feastoperators.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/kustomization.yaml
  config/manifests/bases/rhods-operator.clusterserviceversion.yaml
  config/monitoring/prometheus/apps/prometheus-configs.yaml
  config/rbac/role.yaml
  config/samples/datasciencecluster_v1_datasciencecluster.yaml
  controllers/components/feastoperator/feastoperator.go
  controllers/components/feastoperator/feastoperator_controller.go
  controllers/components/feastoperator/feastoperator_controller_actions.go
  controllers/components/feastoperator/feastoperator_support.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/datasciencecluster/kubebuilder_rbac.go
  controllers/services/monitoring/monitoring.go
  controllers/services/monitoring/monitoring_controller_actions.go
  controllers/webhook/webhook_suite_test.go
  docs/DESIGN.md
  docs/api-overview.md
  docs/upgrade-testing.md
  get_all_manifests.sh
  main.go
  pkg/cluster/gvk/gvk.go
  pkg/upgrade/upgrade.go
  tests/e2e/controller_test.go
  tests/e2e/feastoperator_test.go
  tests/e2e/helper_test.go
  tests/e2e/odh_manager_test.go
  tests/prometheus_unit_tests/feast-operator-alerting.unit-tests.yaml
Labels: lgtm, approved, rhoai-2.19

#1748 Allow configuration of headed/headless services for RawDeployment in DSC
  apis/components/v1alpha1/kserve_types.go
  bundle/manifests/components.platform.opendatahub.io_kserves.yaml
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/bases/components.platform.opendatahub.io_kserves.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  controllers/components/kserve/config.go
  controllers/components/kserve/kserve_controller_actions.go
  controllers/components/kserve/kserve_controller_actions_test.go
  controllers/components/kserve/kserve_support.go
  docs/api-overview.md
Labels: lgtm, approved, rhoai-2.19

#1783 feat: add endpoint health into AuthorizationPolicy as well
  controllers/components/kserve/resources/servicemesh/kserve-inferencegraph-authorizationpolicy.tmpl.yaml
  controllers/components/kserve/resources/servicemesh/kserve-predictor-authorizationpolicy.tmpl.yaml
Labels: lgtm

#1751 fix: testcase for Auth
  tests/e2e/authcontroller_test.go
  tests/e2e/controller_test.go
Labels: lgtm, approved, testing

#1787 fix: missing wildcard for ingress domain
  internal/controller/components/kserve/kserve_support.go
Labels: lgtm, approved

#1795 chore: add CatalogSource to the list of non cached object
  cmd/main.go
Labels: lgtm, approved

#1791 chore: fix webhook unit tests
  Makefile
  README.md
  internal/webhook/webhook_suite_test.go
Labels: lgtm, approved

#1793 [sync] component integration docs & tooling
  Makefile
  cmd/component-codegen/README.md
  cmd/component-codegen/cmd/generate.go
  cmd/component-codegen/cmd/generator/files.go
  cmd/component-codegen/cmd/generator/generator.go
  cmd/component-codegen/cmd/generator/rbac.go
  cmd/component-codegen/cmd/generator/structs.go
  cmd/component-codegen/cmd/generator/utils.go
  cmd/component-codegen/cmd/root.go
  cmd/component-codegen/go.mod
  cmd/component-codegen/go.sum
  cmd/component-codegen/main.go
  cmd/component-codegen/templates/component_controller.go.tmpl
  cmd/component-codegen/templates/component_controller_actions.go.tmpl
  cmd/component-codegen/templates/component_handler.go.tmpl
  cmd/component-codegen/templates/component_support.go.tmpl
  cmd/component-codegen/templates/types.go.tmpl
  docs/COMPONENT_INTEGRATION.md
  go.mod
Labels: lgtm, approved, rhoai

#1797 update: kserve logic + small chores
  api/components/v1alpha1/kserve_types.go
  bundle/manifests/components.platform.opendatahub.io_kserves.yaml
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/crd/bases/components.platform.opendatahub.io_kserves.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  docs/api-overview.md
  internal/controller/components/kserve/kserve.go
  internal/controller/components/kserve/kserve_controller.go
  internal/controller/components/kserve/kserve_controller_actions.go
  internal/controller/components/kserve/kserve_support.go
  internal/controller/status/status.go
Labels: lgtm, approved

#1796 chore: cleanup FeatureTracker for Serverless
  internal/controller/components/kserve/kserve_support.go
  pkg/feature/serverless/conditions.go
  pkg/feature/serverless/data.go
  pkg/feature/serverless/resources.go
  tests/e2e/kserve_test.go
  tests/integration/features/serverless_feature_test.go
Labels: approved

#1761 update: remove Unknown constant from platform detection logic
  internal/controller/components/dashboard/dashboard_controller_actions.go
  internal/controller/components/dashboard/dashboard_support.go
  internal/controller/components/datasciencepipelines/datasciencepipelines_support.go
  internal/controller/components/trustyai/trustyai_support.go
  pkg/cluster/cluster_config.go
  pkg/cluster/const.go
  tests/e2e/authcontroller_test.go
Labels: lgtm, approved

#1802 chore: Add flag for pprof-bind-address
  Makefile
  cmd/main.go
  docs/troubleshooting.md
Labels: lgtm, approved

#1803 chore: cleanup gc action/engine leftover
  pkg/controller/actions/gc/action_gc.go
  pkg/controller/actions/gc/action_gc_test.go
  pkg/controller/actions/gc/engine/gc_engine.go
  pkg/controller/actions/gc/engine/gc_engine_test.go
  pkg/utils/test/scheme/scheme.go
Labels: lgtm, approved

#1806 OWNERS_ALIASES: remove ykaliuta
  OWNERS_ALIASES
Labels: lgtm, approved

#1809 [Sync] fix: kserve error on no CRD + add check on replica before it is ready
  controllers/components/kserve/kserve_controller_actions.go
  controllers/components/kserve/kserve_support.go
  pkg/controller/actions/status/deployments/action_deployments_available.go
  pkg/feature/serverless/conditions.go
  pkg/feature/serverless/data.go
  pkg/feature/serverless/resources.go
  tests/e2e/kserve_test.go
  tests/integration/features/serverless_feature_test.go
Labels: rhoai
