Repository opendatahub-io/opendatahub-operator, pull requests merged in 2025-08, with the labels that each got.

#2240 Setting Kueue to unmanaged state throws an error and blocks DSC
  pkg/rules/rules.go
  pkg/rules/rules_test.go
Labels: lgtm, approved

#2213 RHOAIENG-29275: Migrate auth validation from webhook to CEL validation
  api/services/v1alpha1/auth_cel_integration_test.go
  api/services/v1alpha1/auth_types.go
  api/services/v1alpha1/auth_types_test.go
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  bundle/manifests/services.platform.opendatahub.io_auths.yaml
  config/crd/bases/services.platform.opendatahub.io_auths.yaml
  config/webhook/manifests.yaml
  docs/api-overview.md
  internal/controller/dscinitialization/auth.go
  internal/controller/dscinitialization/auth_test.go
  internal/controller/dscinitialization/dscinitialization_controller.go
  internal/controller/services/auth/auth.go
  internal/controller/services/auth/auth_controller.go
  internal/controller/services/auth/auth_controller_actions.go
  internal/controller/services/auth/auth_controller_actions_test.go
  internal/controller/services/auth/auth_controller_test.go
  internal/webhook/auth/integration_test.go
  internal/webhook/auth/register.go
  internal/webhook/auth/validating.go
  internal/webhook/auth/validating_test.go
  internal/webhook/webhook.go
  tests/e2e/authcontroller_test.go
Labels: lgtm, approved

#2232 [sync] fix: monitoring service wrong tempo endpoint in otel-collector and owns + testcase (#2222)
  api/services/v1alpha1/monitoring_types.go
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/services.platform.opendatahub.io_monitorings.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/crd/bases/services.platform.opendatahub.io_monitorings.yaml
  internal/controller/services/monitoring/monitoring_controller.go
  internal/controller/services/monitoring/monitoring_controller_actions.go
  internal/controller/services/monitoring/monitoring_controller_support.go
  internal/controller/services/monitoring/resources/collector-rbac.tmpl.yaml
  internal/controller/services/monitoring/resources/collector-servicemonitors.tmpl.yaml
  internal/controller/services/monitoring/resources/instrumentation.tmpl.yaml
  internal/controller/services/monitoring/resources/monitoring-stack.tmpl.yaml
  internal/controller/services/monitoring/resources/opentelemetry-collector.tmpl.yaml
  internal/controller/services/monitoring/resources/prometheus-route.tmpl.yaml
  internal/controller/services/monitoring/resources/tempo-monolithic.tmpl.yaml
  internal/controller/status/status.go
  pkg/cluster/gvk/gvk.go
  tests/e2e/monitoring_test.go
Labels: lgtm, approved

#2256 RHOAIENG-31536 - OpenTelemetry and Cluster Observability operators are required to be installed despite no observability configured
  internal/controller/services/monitoring/monitoring_controller_actions.go
  internal/controller/services/monitoring/monitoring_controller_support.go
  internal/controller/status/status.go
Labels: lgtm, approved

#2255 chore(GH): list workflow only file changes
  .github/workflows/build-push-images-on-pr-update.yaml
  .github/workflows/run-integration-tests.yaml
  .github/workflows/unit-tests1.yaml
  .github/workflows/unit-tests2.yaml
  internal/controller/services/servicemesh/servicemesh_support.go
Labels: lgtm, approved

#2253 update: change default retention from 1d to 90d for tracer
  README.md
  api/services/v1alpha1/monitoring_types.go
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  bundle/manifests/services.platform.opendatahub.io_monitorings.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/crd/bases/services.platform.opendatahub.io_monitorings.yaml
  docs/api-overview.md
  internal/controller/services/monitoring/monitoring_controller_support.go
  tests/e2e/monitoring_test.go
Labels: lgtm, approved

#2259 chore(deps): bumps kustomize libraries
  go.mod
  go.sum
Labels: lgtm, approved, do-not-merge/hold

#2169 RHOAIENG-27701: e2e to validate recovery after pod restart
  tests/e2e/helper_test.go
  tests/e2e/odh_manager_test.go
Labels: lgtm, approved

#2246 RHOAIENG-30973: Add Kueue test for legacy annotated managed namespaces
  tests/e2e/cleanup_test.go
  tests/e2e/kueue_test.go
Labels: lgtm, approved

#2273 update(build): kserver rhoai-2.24 is broken, set to use main in RHDS
  get_all_manifests.sh
Labels: lgtm, approved

#2254 [sync] RHOAIENG-29275: Migrate auth validation from webhook to CEL validation
  api/services/v1alpha1/auth_cel_integration_test.go
  api/services/v1alpha1/auth_types.go
  api/services/v1alpha1/auth_types_test.go
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  bundle/manifests/services.platform.opendatahub.io_auths.yaml
  config/crd/bases/services.platform.opendatahub.io_auths.yaml
  config/webhook/manifests.yaml
  docs/api-overview.md
  internal/controller/dscinitialization/auth.go
  internal/controller/dscinitialization/auth_test.go
  internal/controller/dscinitialization/dscinitialization_controller.go
  internal/controller/services/auth/auth.go
  internal/controller/services/auth/auth_controller.go
  internal/controller/services/auth/auth_controller_actions.go
  internal/controller/services/auth/auth_controller_actions_test.go
  internal/controller/services/auth/auth_controller_test.go
  internal/webhook/auth/integration_test.go
  internal/webhook/auth/register.go
  internal/webhook/auth/validating.go
  internal/webhook/auth/validating_test.go
  internal/webhook/webhook.go
  tests/e2e/authcontroller_test.go
Labels: lgtm, approved, rhoai-2.24

#2264 [Sync] feat: add support for notebook image to get images from CSV's env variable + overlay for feast
  internal/controller/components/codeflare/codeflare.go
  internal/controller/components/codeflare/codeflare_controller_actions.go
  internal/controller/components/dashboard/dashboard.go
  internal/controller/components/dashboard/dashboard_controller_actions.go
  internal/controller/components/datasciencepipelines/datasciencepipelines.go
  internal/controller/components/datasciencepipelines/datasciencepipelines_controller_actions.go
  internal/controller/components/feastoperator/feastoperator.go
  internal/controller/components/feastoperator/feastoperator_controller_actions.go
  internal/controller/components/feastoperator/feastoperator_support.go
  internal/controller/components/kserve/kserve.go
  internal/controller/components/kueue/kueue.go
  internal/controller/components/llamastackoperator/llamastackoperator.go
  internal/controller/components/modelcontroller/modelcontroller.go
  internal/controller/components/modelcontroller/modelcontroller_actions.go
  internal/controller/components/modelmeshserving/modelmeshserving.go
  internal/controller/components/modelregistry/modelregistry.go
  internal/controller/components/modelregistry/modelregistry_controller_actions.go
  internal/controller/components/ray/ray.go
  internal/controller/components/ray/ray_controller_actions.go
  internal/controller/components/trainingoperator/trainingoperator.go
  internal/controller/components/trustyai/trustyai.go
  internal/controller/components/workbenches/workbenches.go
  internal/controller/components/workbenches/workbenches_support.go
  pkg/deploy/envParams.go
Labels: lgtm, approved, rhoai-2.24

#2279 [sync]chore: update in CSV and function (#2185)
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  config/manifests/description-patch.yml
  internal/controller/components/kueue/kueue_config.go
  internal/controller/components/kueue/kueue_controller_actions.go
  internal/controller/components/kueue/kueue_controller_actions_test.go
  internal/controller/components/kueue/kueue_support.go
  internal/controller/datasciencecluster/kubebuilder_rbac.go
  internal/controller/services/auth/auth_controller_actions.go
  pkg/cluster/gvk/gvk.go
  tests/e2e/cleanup_test.go
  tests/e2e/kueue_test.go
Labels: lgtm, approved

#2263 docs: add instructions for running integration tests
  README.md
  docs/integration-testing.md
Labels: lgtm, approved

#2289 Fix Kueue webhook to support both v1 and v1alpha1 Ray resources
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/webhook/manifests.yaml
  internal/webhook/kueue/validating.go
  internal/webhook/kueue/validation_test.go
  pkg/cluster/gvk/gvk.go
Labels: lgtm, approved, run-integration-tests

#2296 update: remove duplicated RBAC
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  internal/controller/datasciencecluster/kubebuilder_rbac.go
Labels: lgtm, approved

#2236 RHOAIENG-25597 | feat: Adding GPU metrics
  config/monitoring/base/rhods-prometheusrules.yaml
  docs/ACCELERATOR_METRICS.md
  internal/controller/services/monitoring/monitoring_controller_support.go
  internal/controller/services/monitoring/monitoring_controller_support_test.go
  internal/controller/services/monitoring/resources/opentelemetry-collector.tmpl.yaml
Labels: lgtm, approved, rhoai-2.24

#2304 chore: update .gitignore
  .gitignore
Labels: lgtm, approved

#2308 build: uplift go version to 1.24
  .ci-operator.yaml
  Dockerfiles/Dockerfile
  Dockerfiles/toolbox.Dockerfile
  Makefile
  README.md
  cmd/component-codegen/go.mod
  docs/api-overview.md
  go.mod
  internal/controller/components/codeflare/codeflare_test.go
  internal/controller/components/dashboard/dashboard_controller_actions_test.go
  internal/controller/components/dashboard/dashboard_test.go
  internal/controller/components/datasciencepipelines/datasciencepipelines_controller_actions_test.go
  internal/controller/components/datasciencepipelines/datasciencepipelines_test.go
  internal/controller/components/feastoperator/feastoperator_test.go
  internal/controller/components/kserve/kserve_controller_actions_test.go
  internal/controller/components/kserve/kserve_test.go
  internal/controller/components/kueue/kueue_config_test.go
  internal/controller/components/kueue/kueue_controller_actions_test.go
  internal/controller/components/kueue/kueue_test.go
  internal/controller/components/modelcontroller/modelcontroller_test.go
  internal/controller/components/modelmeshserving/modelmeshserving_test.go
  internal/controller/components/modelregistry/modelregistry_test.go
  internal/controller/components/ray/ray_test.go
  internal/controller/components/trainingoperator/trainingoperator_test.go
  internal/controller/components/trustyai/trustyai_test.go
  internal/controller/components/workbenches/workbenches_test.go
  internal/controller/dscinitialization/auth_test.go
  internal/controller/dscinitialization/utils_test.go
  internal/controller/services/auth/auth_controller_actions_test.go
  internal/controller/services/auth/auth_controller_test.go
  internal/controller/services/certconfigmapgenerator/certconfigmapgenerator_test.go
  internal/controller/services/monitoring/monitoring_controller_actions.go
  internal/controller/services/monitoring/monitoring_controller_support_test.go
  internal/webhook/datasciencecluster/defaulting_test.go
  internal/webhook/datasciencecluster/validating_test.go
  internal/webhook/dscinitialization/validating_test.go
  internal/webhook/envtestutil/envtestutil.go
  internal/webhook/hardwareprofile/mutating_test.go
  internal/webhook/inferenceservice/mutating_test.go
  internal/webhook/kueue/validation_test.go
  internal/webhook/notebook/mutating_test.go
  pkg/cluster/cluster_config_test.go
  pkg/cluster/resources_test.go
  pkg/controller/actions/deleteresource/action_delete_resources_test.go
  pkg/controller/actions/deploy/action_deploy_cache_test.go
  pkg/controller/actions/deploy/action_deploy_test.go
  pkg/controller/actions/gc/action_gc_test.go
  pkg/controller/actions/render/kustomize/action_render_manifests_test.go
  pkg/controller/actions/render/template/action_render_templates_test.go
  pkg/controller/actions/status/deployments/action_deployments_available_test.go
  pkg/controller/actions/status/releases/action_fetch_releases_status_test.go
  pkg/controller/reconciler/reconciler_actions_test.go
  pkg/controller/reconciler/reconciler_test.go
  pkg/resources/resources_test.go
  pkg/rules/rules_test.go
  pkg/upgrade/upgrade_test.go
  tests/e2e/authcontroller_test.go
  tests/e2e/creation_test.go
Labels: lgtm, approved

#2324 [sync] RHOAIENG-29721 | feat: Adding tls to otel colletor
  config/monitoring/base/rhods-servicemonitor.yaml
  internal/controller/services/monitoring/resources/collector-servicemonitors.tmpl.yaml
  internal/controller/services/monitoring/resources/opentelemetry-collector.tmpl.yaml
Labels: lgtm, approved

#2320 [sync]build: uplift go version to 1.24 (#2308)
  .ci-operator.yaml
  Dockerfiles/Dockerfile
  Dockerfiles/toolbox.Dockerfile
  Makefile
  README.md
  cmd/component-codegen/go.mod
  docs/api-overview.md
  go.mod
  internal/controller/components/codeflare/codeflare_test.go
  internal/controller/components/dashboard/dashboard_controller_actions_test.go
  internal/controller/components/dashboard/dashboard_test.go
  internal/controller/components/datasciencepipelines/datasciencepipelines_controller_actions_test.go
  internal/controller/components/datasciencepipelines/datasciencepipelines_test.go
  internal/controller/components/feastoperator/feastoperator_test.go
  internal/controller/components/kserve/kserve_controller_actions_test.go
  internal/controller/components/kserve/kserve_test.go
  internal/controller/components/kueue/kueue_config_test.go
  internal/controller/components/kueue/kueue_controller_actions_test.go
  internal/controller/components/kueue/kueue_test.go
  internal/controller/components/modelcontroller/modelcontroller_test.go
  internal/controller/components/modelmeshserving/modelmeshserving_test.go
  internal/controller/components/modelregistry/modelregistry_test.go
  internal/controller/components/ray/ray_test.go
  internal/controller/components/trainingoperator/trainingoperator_test.go
  internal/controller/components/trustyai/trustyai_test.go
  internal/controller/components/workbenches/workbenches_test.go
  internal/controller/dscinitialization/auth_test.go
  internal/controller/dscinitialization/utils_test.go
  internal/controller/services/auth/auth_controller_actions_test.go
  internal/controller/services/auth/auth_controller_test.go
  internal/controller/services/certconfigmapgenerator/certconfigmapgenerator_test.go
  internal/controller/services/monitoring/monitoring_controller_actions.go
  internal/webhook/datasciencecluster/defaulting_test.go
  internal/webhook/datasciencecluster/validating_test.go
  internal/webhook/dscinitialization/validating_test.go
  internal/webhook/envtestutil/envtestutil.go
  internal/webhook/hardwareprofile/mutating_test.go
  internal/webhook/inferenceservice/mutating_test.go
  internal/webhook/kueue/validation_test.go
  internal/webhook/notebook/mutating_test.go
  pkg/cluster/cluster_config_test.go
  pkg/cluster/resources_test.go
  pkg/controller/actions/deleteresource/action_delete_resources_test.go
  pkg/controller/actions/deploy/action_deploy_cache_test.go
  pkg/controller/actions/deploy/action_deploy_test.go
  pkg/controller/actions/gc/action_gc_test.go
  pkg/controller/actions/render/kustomize/action_render_manifests_test.go
  pkg/controller/actions/render/template/action_render_templates_test.go
  pkg/controller/actions/status/deployments/action_deployments_available_test.go
  pkg/controller/actions/status/releases/action_fetch_releases_status_test.go
  pkg/controller/reconciler/reconciler_actions_test.go
  pkg/controller/reconciler/reconciler_test.go
  pkg/resources/resources_test.go
  pkg/rules/rules_test.go
  pkg/upgrade/upgrade_test.go
  tests/e2e/authcontroller_test.go
  tests/e2e/creation_test.go
Labels: lgtm, approved

#2330 add monitoring namespace flag in e2e test
  tests/e2e/controller_test.go
  tests/e2e/creation_test.go
  tests/e2e/helper_test.go
  tests/e2e/kserve_authorino_test.go
  tests/e2e/odh_manager_test.go
  tests/e2e/test_context_test.go
Labels: approved

#2351 fix: remove skip from deployment deletion recreation test
  tests/e2e/components_test.go
Labels: lgtm, approved

#2353 [fix] Small monitoring test fix
  tests/e2e/monitoring_test.go
Labels: lgtm, approved

#2357 revert changes to federation servicemonitor
  config/monitoring/base/rhods-servicemonitor.yaml
Labels: lgtm, approved

#2318 feat: RHOAIENG-27701: e2e to validate recovery after pod restart
  README.md
  tests/e2e/controller_test.go
  tests/e2e/helper_test.go
  tests/e2e/odh_manager_test.go
  tests/e2e/resilience_test.go
Labels: lgtm, approved

#2348 feat: add llm-d related CRDs into watch
  Makefile
  internal/controller/components/kserve/kserve_controller.go
  pkg/cluster/gvk/gvk.go
Labels: lgtm, approved

#2358 feat: handle connection API deletion case for InferenceService
  internal/webhook/inferenceservice/mutating.go
  internal/webhook/inferenceservice/mutating_test.go
  pkg/webhook/utils.go
Labels: lgtm, approved, rhoai-2.25

#2362 chore: fix typo + update comments
  internal/webhook/inferenceservice/mutating.go
  pkg/webhook/utils.go
Labels: lgtm, approved

#2365 [sync]: feat: handle connection API deletion
  internal/webhook/inferenceservice/mutating.go
  internal/webhook/inferenceservice/mutating_test.go
  pkg/webhook/utils.go
Labels: lgtm, approved

#2361 [sync]RHOAIENG-27701: e2e to validate recovery after pod restart
  README.md
  tests/e2e/controller_test.go
  tests/e2e/helper_test.go
  tests/e2e/odh_manager_test.go
  tests/e2e/resilience_test.go
Labels: lgtm, approved

#2372 Onboard Pytorch+LLMCompressor on the CSV env list
  internal/controller/components/workbenches/workbenches.go
Labels: lgtm, approved, component/workbenches, rhoai-2.25

#2370 Increase timeout for the deletion to avoid failures in HCP
  tests/e2e/kserve_test.go
  tests/e2e/test_context_test.go
Labels: lgtm, approved
