Repository opendatahub-io/opendatahub-operator, pull requests merged in 2025-09, with the labels that each got.

#2381 fix: missing RBAC for llm-d resources
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controller/datasciencecluster/kubebuilder_rbac.go
Labels: lgtm, odh-2.34

#2389 fix alerting validation rule
  api/services/v1alpha1/monitoring_types.go
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  bundle/manifests/services.platform.opendatahub.io_monitorings.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/crd/bases/services.platform.opendatahub.io_monitorings.yaml
Labels: lgtm, approved

#2395 alerting validation should block unless storage or resources are set
  api/services/v1alpha1/monitoring_types.go
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/services.platform.opendatahub.io_monitorings.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/crd/bases/services.platform.opendatahub.io_monitorings.yaml
Labels: lgtm, approved

#2376 update: add ServiceAccount creation and biding for Inferenceservice Connection API
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/webhook/manifests.yaml
  internal/webhook/envtestutil/webhook_registration.go
  internal/webhook/inferenceservice/mutating.go
  internal/webhook/inferenceservice/mutating_test.go
  internal/webhook/inferenceservice/register.go
  pkg/webhook/utils.go
Labels: lgtm, approved, rhoai-2.25, rhoai-3.0

#2294 set_default_replicas_to_2_for_collector
  api/services/v1alpha1/monitoring_types.go
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/services.platform.opendatahub.io_monitorings.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/crd/bases/services.platform.opendatahub.io_monitorings.yaml
  docs/api-overview.md
  internal/controller/dscinitialization/dscinitialization_controller.go
  internal/controller/services/monitoring/monitoring_controller_support.go
  internal/controller/services/monitoring/resources/opentelemetry-collector.tmpl.yaml
  tests/e2e/monitoring_test.go
Labels: lgtm, approved, rhoai-2.25

#2411 fix: set model registry to Managed by default for new DSC instances, fixes RHOAIENG-33266
  pkg/upgrade/upgrade.go
Labels: lgtm, approved, rhoai-2.25

#2428 fix: HWProfile webhook on wrong path for ISVC
  internal/webhook/envtestutil/envtestutil.go
  internal/webhook/hardwareprofile/integration_test.go
  internal/webhook/hardwareprofile/mutating.go
  internal/webhook/hardwareprofile/mutating_test.go
  internal/webhook/inferenceservice/mutating_test.go
Labels: lgtm, approved, rhoai-2.25

#2404 [RHOAIENG-33135] minimal gatewayclass/gateway implementation
  PROJECT
  api/services/v1alpha1/auth_types_test.go
  api/services/v1alpha1/gateway_types.go
  api/services/v1alpha1/types_test.go
  api/services/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  bundle/manifests/services.platform.opendatahub.io_gatewayconfigs.yaml
  cmd/main.go
  config/crd/bases/services.platform.opendatahub.io_gatewayconfigs.yaml
  config/crd/kustomization.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  docs/api-overview.md
  go.mod
  go.sum
  internal/controller/datasciencecluster/kubebuilder_rbac.go
  internal/controller/services/gateway/gateway.go
  internal/controller/services/gateway/gateway_controller.go
  internal/controller/services/gateway/gateway_controller_actions.go
  internal/controller/services/gateway/gateway_controller_actions_test.go
  tests/e2e/controller_test.go
  tests/e2e/gateway_test.go
Labels: approved

#2429 feat: add catalog data image for model catalog service
  internal/controller/components/modelregistry/modelregistry_support.go
Labels: lgtm, approved, component/modelregistry, rhoai-2.25

#2441 fix: when servicemesh is set to Removed in DSCI, should not continue check
  internal/controller/services/servicemesh/servicemesh_controller_actions.go
Labels: lgtm, approved

#2414 [stable-2.x] Add ClusterQueue resource aware configuration and generate ResourceFlavor
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controller/components/kueue/kueue_controller.go
  internal/controller/components/kueue/kueue_controller_actions.go
  internal/controller/components/kueue/kueue_controller_actions_test.go
  internal/controller/components/kueue/kueue_support.go
  internal/controller/datasciencecluster/kubebuilder_rbac.go
  pkg/cluster/gvk/gvk.go
  tests/e2e/kueue_test.go
Labels: lgtm, approved

#2443 Remove servicemesh not installed check.
  tests/e2e/servicemesh_test.go
Labels: lgtm, approved

#2470 chore: skip HWP migration if dashboard HWP CRD missing
  internal/controller/components/dashboard/dashboard_controller.go
  internal/controller/components/dashboard/dashboard_controller_actions.go
  internal/controller/components/dashboard/dashboard_controller_actions_test.go
Labels: lgtm, approved, team-crucible

#2466 feat: add support to pass Oauth proxy image for downstream
  internal/controller/components/workbenches/workbenches.go
Labels: lgtm, approved, component/workbenches

#2465 add override for new workbenches
  internal/controller/components/workbenches/workbenches.go
Labels: lgtm, approved, component/workbenches

#2453 prometheus test should check monitoring namespace not apps namespace
  tests/e2e/monitoring_test.go
Labels: lgtm, approved, rhoai-2.25, team-compass

#2469 update: remove logic set default value in odhdashboardconfig in upgrade
  cmd/main.go
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_test.go
Labels: lgtm, approved, rhoai-3.0, team-crucible

#2418 feat: optimize E2E test framework performance and error handling
  pkg/cluster/gvk/gvk.go
  pkg/utils/test/testf/testf_witht.go
  tests/e2e/authcontroller_test.go
  tests/e2e/cleanup_test.go
  tests/e2e/codeflare_test.go
  tests/e2e/components_test.go
  tests/e2e/controller_test.go
  tests/e2e/creation_test.go
  tests/e2e/dashboard_test.go
  tests/e2e/datasciencepipelines_test.go
  tests/e2e/feastoperator_test.go
  tests/e2e/gateway_test.go
  tests/e2e/helper_test.go
  tests/e2e/kserve_authorino_test.go
  tests/e2e/kserve_test.go
  tests/e2e/kueue_test.go
  tests/e2e/llamastackoperator_test.go
  tests/e2e/modelcontroller_test.go
  tests/e2e/modelmeshserving_test.go
  tests/e2e/modelregistry_test.go
  tests/e2e/monitoring_test.go
  tests/e2e/odh_manager_test.go
  tests/e2e/ray_test.go
  tests/e2e/resilience_test.go
  tests/e2e/resource_applier_test.go
  tests/e2e/resource_fetcher_test.go
  tests/e2e/resource_options_test.go
  tests/e2e/servicemesh_test.go
  tests/e2e/test_context_test.go
  tests/e2e/trainingoperator_test.go
  tests/e2e/trustyai_test.go
  tests/e2e/workbenches_test.go
Labels: lgtm, approved, testing

#2293 feat: add support for llmisvc to use kueue
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/webhook/manifests.yaml
  internal/webhook/envtestutil/envtestutil.go
  internal/webhook/envtestutil/webhook_registration.go
  internal/webhook/kueue/integration_test.go
  internal/webhook/kueue/validating.go
  internal/webhook/kueue/validation_test.go
Labels: lgtm, approved, rhoai-3.0, team-crucible

#2482 [sync] feat: add new VAP to block create/update operation on dashboard's HWProfile CR and AcceleratorProfile CR (#2378)
  Dockerfiles/Dockerfile
  config/hardwareprofiles/kustomization.yaml
  config/hardwareprofiles/vap/acceleratorprofile.yaml
  config/hardwareprofiles/vap/hardwareprofile.yaml
  config/hardwareprofiles/vap/kustomization.yaml
  config/manifests/kustomization.yaml
  get_all_manifests.sh
  internal/controller/components/dashboard/dashboard_controller.go
  internal/controller/dscinitialization/dscinitialization_controller.go
  internal/controller/dscinitialization/hardwareprofile.go
  pkg/cluster/cluster_config.go
  pkg/cluster/gvk/gvk.go
  tests/e2e/creation_test.go
  tests/e2e/dashboard_test.go
Labels: lgtm, approved, rhoai-3.0, team-crucible

#2481 [sync] update: remove logic set default value in odhdashboardconfig in upgrade (#2469)
  cmd/main.go
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_test.go
Labels: lgtm, approved, rhoai-3.0, team-crucible

#2427 Use custom manifests without devFlags
  Dockerfiles/Dockerfile
  hack/component-dev/README.md
  hack/component-dev/csv-patch.json
  hack/component-dev/pvc.yaml
Labels: lgtm, approved

#2486 feat: add comprehensive debug utilities for E2E test failures and timeouts
  tests/e2e/controller_test.go
  tests/e2e/creation_test.go
  tests/e2e/debug_utils_test.go
  tests/e2e/helper_test.go
  tests/e2e/test_context_test.go
Labels: lgtm, approved, rhoai-2.25, rhoai-3.0

#2497 fix: limit e2e update requirement check GH action only to the main branch and improve docs/error outputs
  .github/workflows/check-e2e-update-requirement.yaml
  .github/workflows/comment-on-e2e-check.yaml
  docs/e2e-update-requirement-guidelines.md
Labels: lgtm, approved

#2499 update: temp. disable e2e test on dashboard
  tests/e2e/controller_test.go
  tests/e2e/creation_test.go
  tests/e2e/dashboard_test.go
  tests/e2e/monitoring_test.go
Labels: lgtm, approved

#2500 [sync] feat: add llm-d related CRDs into watch [#2348]
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  internal/controller/components/kserve/kserve_controller.go
  pkg/cluster/gvk/gvk.go
Labels: lgtm, approved, rhoai-2.25

#2484 RHAIENG-608: Removing the Py311 Images
  internal/controller/components/workbenches/workbenches.go
Labels: lgtm, approved, component/workbenches, rhoai-2.25, rhoai-3.0

#2471 RHOAIENG-34173: prevent secret data leakage in operator error logs
  internal/controller/components/kserve/kserve_support.go
  pkg/resources/resources.go
  pkg/resources/resources_test.go
Labels: lgtm, approved, rhoai-2.25, rhoai-3.0

#2506 test: increase resource timeout and fix dsc debug
  tests/e2e/components_test.go
  tests/e2e/debug_utils_test.go
  tests/e2e/monitoring_test.go
  tests/e2e/test_context_test.go
Labels: lgtm, approved

#2468 Remove codeflare operator, monitoring and tests
  README.md
  cmd/main.go
  config/monitoring/prometheus/apps/prometheus-configs.yaml
  config/rbac/role.yaml
  docs/COMPONENT_INTEGRATION.md
  docs/DESIGN.md
  get_all_manifests.sh
  internal/controller/components/codeflare/codeflare.go
  internal/controller/components/codeflare/codeflare_controller.go
  internal/controller/components/codeflare/codeflare_controller_actions.go
  internal/controller/components/codeflare/codeflare_support.go
  internal/controller/components/codeflare/codeflare_test.go
  internal/controller/components/codeflare/monitoring/codeflare-prometheusrules.tmpl.yaml
  internal/controller/components/components.go
  internal/controller/datasciencecluster/datasciencecluster_controller.go
  internal/controller/datasciencecluster/kubebuilder_rbac.go
  internal/controller/dscinitialization/monitoring.go
  internal/controller/services/monitoring/monitoring.go
  internal/controller/services/monitoring/monitoring_controller_actions.go
  tests/e2e/codeflare_test.go
  tests/e2e/controller_test.go
  tests/e2e/odh_manager_test.go
  tests/e2e/resilience_test.go
  tests/e2e/v2tov3upgrade_test.go
  tests/prometheus_unit_tests/codeflare-alerting.unit-tests.yaml
Labels: lgtm, approved, rhoai-3.0

#2501 [sync] feat: add llm-d related CRD into watch (#2348)
  Makefile
  internal/controller/components/kserve/kserve_controller.go
  pkg/cluster/gvk/gvk.go
Labels: lgtm, approved, rhoai-3.0

#2491 chore: logging webhook for notebook with HWProfile
  internal/webhook/hardwareprofile/integration_test.go
  internal/webhook/hardwareprofile/mutating.go
  internal/webhook/hardwareprofile/mutating_test.go
  tests/e2e/test_context_test.go
Labels: lgtm, approved, team-crucible

#2517 [sync] feat: enable modelreg bff image (#2233)
  internal/controller/components/dashboard/dashboard.go
  internal/controller/components/dashboard/dashboard_support.go
Labels: lgtm, approved, component/dashboard, rhoai-2.25

#2490 feat: auto detect auth, kube auth proxy, envoy filter
  api/services/v1alpha1/gateway_types.go
  api/services/v1alpha1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/services.platform.opendatahub.io_gatewayconfigs.yaml
  config/rbac/role.yaml
  docs/api-overview.md
  internal/controller/datasciencecluster/kubebuilder_rbac.go
  internal/controller/services/gateway/gateway_auth_actions.go
  internal/controller/services/gateway/gateway_controller.go
  internal/controller/services/gateway/gateway_controller_actions.go
  internal/controller/services/gateway/resources/envoyfilter-authn.yaml
  internal/controller/status/status.go
Labels: lgtm, approved

#2521 chore: remove unused pkg/feature and related integration tests
  .github/workflows/unit-tests1.yaml
  pkg/feature/README.md
  pkg/feature/builder.go
  pkg/feature/conditions.go
  pkg/feature/feature.go
  pkg/feature/feature_data.go
  pkg/feature/feature_suite_test.go
  pkg/feature/feature_tracker_handler.go
  pkg/feature/handler.go
  pkg/feature/manifest/builder.go
  pkg/feature/manifest/manifest_test.go
  pkg/feature/manifest/resources/raw/my-configmap.yaml
  pkg/feature/manifest/resources/template/my-configmap.tmpl.yaml
  pkg/feature/manifest/types.go
  pkg/feature/provider/data_provider_test.go
  pkg/feature/provider/provider_suite_test.go
  pkg/feature/provider/types.go
  pkg/feature/resource/operations.go
  pkg/feature/resource/types.go
  pkg/feature/resources.go
  tests/integration/features/cleanup_int_test.go
  tests/integration/features/crd/subscription.crd.yaml
  tests/integration/features/features_suite_int_test.go
  tests/integration/features/fixtures/cluster_test_fixtures.go
  tests/integration/features/fixtures/const.go
  tests/integration/features/fixtures/crd/istio-gateway.crd.yaml
  tests/integration/features/fixtures/crd/openshift-ingresses.crd.yaml
  tests/integration/features/fixtures/crd/subscription.crd.yaml
  tests/integration/features/fixtures/crd/test-resource.crd.yaml
  tests/integration/features/fixtures/file_sys_fixtures.go
  tests/integration/features/fixtures/knative_resources.go
  tests/integration/features/fixtures/servicemesh_resources.go
  tests/integration/features/fixtures/templates/fake-kust-dir/kustomization.yaml
  tests/integration/features/fixtures/templates/fake-kust-dir/resource.yaml
  tests/integration/features/fixtures/templates/local-gateway-svc.tmpl.yaml
  tests/integration/features/fixtures/templates/managed-svc.tmpl.yaml
  tests/integration/features/fixtures/templates/mesh-authz-ext-provider.patch.tmpl.yaml
  tests/integration/features/fixtures/templates/namespaces.yaml
  tests/integration/features/fixtures/templates/unmanaged-svc.tmpl.yaml
  tests/integration/features/manifests_int_test.go
  tests/integration/features/postconditions_int_test.go
  tests/integration/features/preconditions_int_test.go
  tests/integration/features/resources_int_test.go
  tests/integration/features/tracker_int_test.go
Labels: lgtm, approved

#2531 [stable-2.x] Remove duplicated crd check
  internal/controller/components/kserve/kserve_controller.go
  internal/controller/services/servicemesh/servicemesh_controller.go
  pkg/controller/actions/actions_support.go
Labels: lgtm, approved

#2536 implemented destination rule for TLS to upstream services
  internal/controller/services/gateway/gateway_controller.go
  internal/controller/services/gateway/gateway_controller_actions.go
  internal/controller/services/gateway/resources/destinationrule-tls.yaml
Labels: lgtm, approved

#2461 feat: add default HWProfile CR "default-profile"
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/hardwareprofiles/hardwareprofiles.yaml
  config/hardwareprofiles/kustomization.yaml
  config/manifests/kustomization.yaml
  config/samples/kustomization.yaml
  internal/controller/dscinitialization/dscinitialization_controller.go
  internal/controller/dscinitialization/hardwareprofile.go
  internal/controller/dscinitialization/suite_test.go
  pkg/cluster/resources.go
  pkg/utils/test/envt/envt.go
  tests/e2e/creation_test.go
Labels: lgtm, approved, rhoai-3.0, team-crucible

#2532 feat: switch isvc connection annotation from type to protocol
  internal/webhook/inferenceservice/mutating.go
  internal/webhook/inferenceservice/mutating_test.go
  pkg/metadata/annotations/annotations.go
  pkg/webhook/utils.go
  tests/e2e/kserve_test.go
Labels: lgtm, approved, team-crucible

#2544 fix: version inconsistency
  Makefile
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Labels: lgtm, approved, odh-3.0.0

#2537 Add support for overriding kserve-llm-d
  internal/controller/components/kserve/kserve_support.go
Labels: lgtm, approved

#2424 feat: add support for llmisvc to use HWProfile
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/webhook/manifests.yaml
  internal/webhook/envtestutil/envtestutil.go
  internal/webhook/hardwareprofile/integration_test.go
  internal/webhook/hardwareprofile/mutating.go
  internal/webhook/hardwareprofile/mutating_test.go
  pkg/utils/test/envt/envt.go
Labels: lgtm, approved, rhoai-3.0, team-crucible

#2548 [rhoai] feat: switch isvc connection annotation from type to protocol
  internal/webhook/inferenceservice/mutating.go
  internal/webhook/inferenceservice/mutating_test.go
  pkg/metadata/annotations/annotations.go
  pkg/webhook/utils.go
  tests/e2e/kserve_test.go
Labels: lgtm, approved, team-crucible

#2525 fix(RHOAIENG-34533): resolve TrustyAI DSC validation error when patching DSC eval flags
  api/components/v1alpha1/trustyai_types.go
  bundle/manifests/components.platform.opendatahub.io_trustyais.yaml
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/bases/components.platform.opendatahub.io_trustyais.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  docs/api-overview.md
  internal/controller/components/trustyai/trustyai.go
  internal/controller/components/trustyai/trustyai_controller_actions.go
  internal/controller/components/trustyai/trustyai_test.go
Labels: lgtm, approved, rhoai-2.25, rhoai-3.0, component/trustyai

#2561 test: revert "temp. disable e2e test on dashboard" from PR2507 and fix VAP/VAPB e2e tests
  tests/e2e/controller_test.go
  tests/e2e/creation_test.go
  tests/e2e/dashboard_test.go
  tests/e2e/monitoring_test.go
Labels: lgtm, approved

#2514 RHOAIENG-34055: add ray sanity check for codeflare removal
  internal/controller/components/ray/ray_controller.go
  internal/controller/components/ray/ray_test.go
  internal/controller/status/status.go
  pkg/cluster/resources.go
  pkg/cluster/resources_test.go
  pkg/controller/actions/sanitycheck/sanitycheck.go
  pkg/controller/actions/sanitycheck/sanitycheck_test.go
  tests/e2e/cleanup_test.go
  tests/e2e/resilience_test.go
  tests/e2e/v2tov3upgrade_test.go
Labels: lgtm, approved

#2568 cherry-pick: PR 2561 only for VAP and enable dashboard
  api/infrastructure/v1/hardwareprofile_types.go
  api/infrastructure/v1/hardwareprofile_types_test.go
  api/infrastructure/v1alpha1/hardwareprofile_types_test.go
  tests/e2e/creation_test.go
  tests/e2e/dashboard_test.go
Labels: lgtm, approved

#2555 [RHOAIENG-35017] kube-rbac-proxy image normalization
  internal/controller/components/dashboard/dashboard_support.go
  internal/controller/components/datasciencepipelines/datasciencepipelines_support.go
  internal/controller/components/kserve/kserve_support.go
  internal/controller/components/modelregistry/modelregistry_support.go
  internal/controller/components/trustyai/trustyai_support.go
  internal/controller/components/workbenches/workbenches.go
Labels: lgtm, approved

#2569 RHOAIENG-33445: OCP console link to odh should match gateway address
  internal/controller/components/dashboard/dashboard_controller_actions.go
  internal/controller/components/dashboard/dashboard_support.go
  internal/controller/components/dashboard/dashboard_test.go
  internal/controller/services/gateway/gateway_auth_actions.go
  internal/controller/services/gateway/gateway_controller.go
  internal/controller/services/gateway/gateway_controller_actions.go
  internal/controller/services/gateway/gateway_controller_actions_test.go
  internal/controller/services/gateway/gateway_controller_test.go
  internal/controller/services/gateway/gateway_support.go
  internal/controller/services/gateway/gateway_support_test.go
  pkg/cluster/gvk/gvk.go
Labels: lgtm, approved
