Repository opendatahub-io/opendatahub-operator, pull requests merged in 2025-01, with the labels that each got.

#1470 [sync] chore changes from main branch
  .github/workflows/pre-release.yaml
  OWNERS_ALIASES
  README.md
Labels: lgtm, approved, rhoai

#1471 [sync] Update golang.org/x/net to v0.33.0 (#1463)
  go.mod
  go.sum
Labels: lgtm, approved, rhoai

#1469 [sync]: uplift go from 1.21 to 1.22
  .ci-operator.yaml
  Dockerfiles/Dockerfile
  Dockerfiles/toolbox.Dockerfile
  Makefile
  README.md
  components/kserve/kserve_config_handler.go
  controllers/secretgenerator/secret.go
  controllers/secretgenerator/secret_test.go
  go.mod
  pkg/upgrade/uninstallation.go
  pkg/upgrade/upgrade.go
  tests/e2e/creation_test.go
  tests/e2e/deletion_test.go
  tests/e2e/helper_test.go
  tests/envtestutil/cleaner.go
Labels: approved, rhoai

#1462 Fix parameter order in resolveTargetPath to ensure manifest overwrite
  pkg/deploy/deploy.go
Labels: lgtm

#1472 chore: cleanup static-named nim resources for switching to naming convention
  pkg/upgrade/upgrade.go
Labels: lgtm, approved, ok-to-test

#1473 Revert "chore: fixed typo in the logs"
  pkg/upgrade/upgrade.go
Labels: lgtm, approved, incubating

#1456 get_all_manifests.sh: use key (component name) as the target folder
  get_all_manifests.sh
Labels: lgtm, approved

#1465 Show KServe defaultDeploymentMode in DSC status
  apis/components/v1alpha1/kserve_types.go
  bundle/manifests/components.platform.opendatahub.io_kserves.yaml
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/crd/bases/components.platform.opendatahub.io_kserves.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  controllers/components/kserve/config.go
  controllers/components/kserve/kserve_controller.go
  controllers/components/kserve/kserve_controller_actions.go
  controllers/components/kserve/kserve_support.go
  docs/api-overview.md
  tests/e2e/helper_test.go
  tests/e2e/kserve_test.go
Labels: lgtm, approved

#1478 chore: Remove unused yq test matchers package
  go.mod
  go.sum
  pkg/utils/test/matchers/yq/yq.go
  pkg/utils/test/matchers/yq/yq_matcher.go
  pkg/utils/test/matchers/yq/yq_matcher_test.go
  pkg/utils/test/matchers/yq/yq_support.go
  pkg/utils/test/matchers/yq/yq_support_logging.go
  pkg/utils/test/matchers/yq/yq_transform.go
  pkg/utils/test/matchers/yq/yq_transform_test.go
Labels: lgtm, approved

#1468 [sync] update: remove cache for deployment in modelreg ns
  main.go
Labels: lgtm, approved, rhoai

#1475 chore: disable deprecated linters
  .golangci.yml
Labels: lgtm, approved

#1482 Update golangci-lint to v1.63.4
  .golangci.yml
  Makefile
  controllers/datasciencecluster/datasciencecluster_controller.go
  pkg/controller/actions/deploy/action_deploy_merge_deployment.go
  pkg/controller/actions/render/template/action_render_templates.go
  pkg/controller/reconciler/reconciler_support.go
  pkg/deploy/deploy.go
  pkg/feature/servicemesh/conditions.go
  pkg/manifests/kustomize/kustomize_engine.go
  pkg/resources/resources.go
  pkg/services/gc/gc_support.go
  tests/e2e/controller_test.go
  tests/e2e/helper_test.go
Labels: lgtm, approved

#1485 Improve operator's client SSA error handling
  pkg/controller/client/client.go
Labels: lgtm, approved

#1489 update codecov-actions version and add codecov config file to repo
  .github/workflows/unit-tests.yaml
  codecov.yml
Labels: lgtm, approved

#1491 feat: KServe InferenceGraph auth configurations [main]
  controllers/components/kserve/kserve_support.go
  controllers/components/kserve/resources/servicemesh/kserve-inferencegraph-authorizationpolicy.tmpl.yaml
  controllers/components/kserve/resources/servicemesh/kserve-inferencegraph-envoyfilter.tmpl.yaml
Labels: lgtm, approved

#1434 tests: e2e test for trusted-ca-bundle
  tests/e2e/creation_test.go
  tests/e2e/helper_test.go
Labels: lgtm, approved

#1492 codecov config to show code coverage numbers on every PR as informational and not blocking
  codecov.yml
Labels: lgtm, approved

#1452 Rhoaieng 14232 add auth crd
  PROJECT
  apis/services/v1alpha1/auth_types.go
  apis/services/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  bundle/manifests/services.platform.opendatahub.io_auths.yaml
  config/crd/bases/services.platform.opendatahub.io_auths.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_services_auths.yaml
  config/crd/patches/webhook_in_services_auths.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  config/rbac/services_auth_editor_role.yaml
  config/rbac/services_auth_viewer_role.yaml
  config/samples/kustomization.yaml
  config/samples/services_v1alpha1_auth.yaml
  controllers/components/dashboard/dashboard_support.go
  controllers/datasciencecluster/kubebuilder_rbac.go
  controllers/dscinitialization/auth.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/suite_test.go
  controllers/services/auth/auth_controller.go
  controllers/services/auth/auth_controller_actions.go
  controllers/services/auth/auth_controller_support.go
  controllers/services/auth/resources/admingroup-clusterrole.tmpl.yaml
  controllers/services/auth/resources/admingroup-role.tmpl.yaml
  controllers/services/auth/resources/allowedgroup-role.tmpl.yaml
  docs/api-overview.md
  main.go
  pkg/cluster/gvk/gvk.go
  pkg/common/common.go
  tests/e2e/authcontroller_test.go
  tests/e2e/controller_test.go
Labels: lgtm, approved

#1495 Revert "tests: e2e test for trusted-ca-bundle"
  tests/e2e/creation_test.go
  tests/e2e/helper_test.go
Labels: lgtm, approved

#1137 docs(api): set manifestUri as deprecated
  apis/dscinitialization/v1/dscinitialization_types.go
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  docs/api-overview.md
Labels: lgtm, approved

#1481 Migrate e2e components tests to Gomega
  .golangci.yml
  pkg/controller/client/client.go
  pkg/resources/resources.go
  pkg/resources/resources_test.go
  pkg/utils/test/matchers/jq/jq_transform.go
  pkg/utils/test/matchers/jq/jq_transform_test.go
  pkg/utils/test/testf/testf.go
  pkg/utils/test/testf/testf_assertions.go
  pkg/utils/test/testf/testf_support.go
  pkg/utils/test/testf/testf_support_test.go
  pkg/utils/test/testf/testf_witht.go
  pkg/utils/test/testf/testf_witht_test.go
  tests/e2e/codeflare_test.go
  tests/e2e/components_test.go
  tests/e2e/controller_test.go
  tests/e2e/creation_test.go
  tests/e2e/dashboard_test.go
  tests/e2e/datasciencepipelines_test.go
  tests/e2e/helper_test.go
  tests/e2e/kserve_test.go
  tests/e2e/kueue_test.go
  tests/e2e/modelcontroller_test.go
  tests/e2e/modelmeshserving_test.go
  tests/e2e/modelregistry_test.go
  tests/e2e/ray_test.go
  tests/e2e/trainingoperator_test.go
  tests/e2e/trustyai_test.go
Labels: lgtm, approved

#1493 chore: add codecoverage badge to Readme
  README.md
Labels: lgtm, approved

#1460 fix: Prevent containers from running as root by removing unnecessary anyuid SCC bindings
  controllers/components/dashboard/dashboard_controller.go
  controllers/components/dashboard/dashboard_support.go
  controllers/components/modelcontroller/modelcontroller_controller.go
  controllers/components/modelcontroller/modelcontroller_support.go
  controllers/components/modelmeshserving/modelmeshserving_controller.go
  controllers/components/modelmeshserving/modelmeshserving_support.go
  controllers/components/workbenches/workbenches_controller.go
  controllers/components/workbenches/workbenches_support.go
  pkg/controller/actions/security/actions.go
  pkg/controller/actions/security/actions_test.go
Labels: lgtm, approved

#1487 chore: add more rules in golint
  .golangci.yml
  controllers/services/auth/auth_controller.go
  controllers/webhook/webhook.go
  controllers/webhook/webhook_suite_test.go
  tests/e2e/creation_test.go
  tests/e2e/helper_test.go
  tests/e2e/modelregistry_test.go
Labels: approved

#1497 chore: cleanup kustomize config
  Makefile
  config/samples/components_v1_codeflare.yaml
  config/samples/components_v1_dashboard.yaml
  config/samples/components_v1_datasciencepipelines.yaml
  config/samples/components_v1_kserve.yaml
  config/samples/components_v1_kueue.yaml
  config/samples/components_v1_modelmeshserving.yaml
  config/samples/components_v1_modelregistry.yaml
  config/samples/components_v1_ray.yaml
  config/samples/components_v1_trainingoperator.yaml
  config/samples/components_v1_trustyai.yaml
  config/samples/components_v1_workbenches.yaml
  config/samples/kustomization.yaml
  config/samples/services_v1_monitoring.yaml
Labels: lgtm, approved

#1500 RHOAIENG-18095: Deprecation of kube-rbac-proxy
  config/monitoring/prometheus/apps/prometheus-configs.yaml
Labels: lgtm, approved

#1499 Update Auth controller tests for RHOAI
  tests/e2e/authcontroller_test.go
  tests/e2e/controller_test.go
Labels: lgtm, approved

#1488 docs: Add updated component integration guide
  docs/COMPONENT_INTEGRATION.md
Labels: lgtm, approved

#1502 componentsregistry: use structure to store handlers
  controllers/datasciencecluster/datasciencecluster_controller.go
  pkg/componentsregistry/componentsregistry.go
Labels: lgtm, approved

#1480 feat: add support for kueue to work with VAP on OCP 4.16+
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/components/kueue/kueue_controller.go
  controllers/components/kueue/kueue_controller_actions.go
  controllers/components/kueue/kueue_support.go
  controllers/datasciencecluster/kubebuilder_rbac.go
  pkg/cluster/cluster_config.go
  pkg/cluster/const.go
  pkg/cluster/gvk/gvk.go
  tests/e2e/components_test.go
  tests/e2e/kueue_test.go
Labels: lgtm, approved, component/kueue

#1505 Fix typo in file name: pkg/utils/test/matchers/matechers.go -> pkg/utils/test/matchers/matchers.go
  pkg/utils/test/matchers/matchers.go
Labels: lgtm, approved

#1508 (feat): Add roles and cluster roles for admingroups
  controllers/services/auth/resources/admingroup-clusterrole.tmpl.yaml
  controllers/services/auth/resources/admingroup-role.tmpl.yaml
Labels: lgtm, approved

#1509 e2e: improve testOwnedNamespacesAllExist by leveragin gomega's async assertions
  tests/e2e/cfmap_deletion_test.go
  tests/e2e/controller_test.go
  tests/e2e/creation_test.go
Labels: lgtm, approved

#1506 Improve unit tests for jq's toType and byteToType
  pkg/utils/test/matchers/jq/jq_support_test.go
Labels: lgtm, approved

#1512 (fix): Typo in clusterrole for admin users
  controllers/services/auth/resources/admingroup-clusterrole.tmpl.yaml
Labels: lgtm, approved

#1504 update: we do not need anaconda-ce-periodic-validator from Operator
  Dockerfiles/Dockerfile
  config/partners/anaconda/base/anaconda-ce-validator-cron.yaml
  config/partners/anaconda/base/kustomization.yaml
Labels: lgtm, approved, rhoai

#1427 feat: use label selector to pick namespace
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/dscinitialization_test.go
  controllers/dscinitialization/utils.go
  main.go
  pkg/metadata/labels/types.go
Labels: lgtm, approved

#1517 e2e: add cleanup logic to kserve tests to ensure no KnativeServing is present in the cluster
  tests/e2e/helper_test.go
Labels: lgtm, approved

#1515 [sync] add support for kueue to work with VAP on OCP 4.16+ (#1480)
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/components/kueue/kueue_controller.go
  controllers/components/kueue/kueue_controller_actions.go
  controllers/components/kueue/kueue_support.go
  controllers/datasciencecluster/kubebuilder_rbac.go
  get_all_manifests.sh
  pkg/cluster/cluster_config.go
  pkg/cluster/const.go
  pkg/cluster/gvk/gvk.go
  tests/e2e/components_test.go
  tests/e2e/kueue_test.go
Labels: approved, rhoai

#1523 e2e: add cleanup logic to kserve tests to ensure no KnativeServing instances are present in the cluster
  tests/e2e/kserve_test.go
Labels: lgtm, approved

#1516 [sync] : use label selector to pick namespace (#1427)
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/dscinitialization_test.go
  controllers/dscinitialization/utils.go
  main.go
  pkg/metadata/labels/types.go
Labels: lgtm, approved, rhoai

#1518 [backport] fix: networkpolicy
  main.go
Labels: lgtm, approved

#1522 Revert "e2e: add cleanup logic to kserve tests to ensure no KnativeServing is present in the cluster"
  tests/e2e/helper_test.go
Labels: lgtm, approved

#1527 Add support for dynamic template data computation in template rendering action
  pkg/controller/actions/render/template/action_render_templates.go
  pkg/controller/actions/render/template/action_render_templates_test.go
  pkg/controller/actions/render/template/resources/smm-data.tmpl.yaml
Labels: lgtm, approved

#1514 chore: remove generics from Reconcier and use PlatformObject as base object type
  pkg/controller/reconciler/reconciler.go
  pkg/controller/reconciler/reconciler_support.go
  pkg/controller/types/types.go
Labels: lgtm, approved

#1520 chore: address comments for monitoring component
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/services/monitoring/monitoring.go
  controllers/services/monitoring/monitoring_controller.go
  controllers/services/monitoring/monitoring_controller_actions.go
  pkg/controller/predicates/resources/resources.go
  pkg/services/monitoring/prometheus.go
Labels: lgtm, approved, do-not-merge/work-in-progress

#1532 revert: back to use 2.17 branch for kserve
  get_all_manifests.sh
Labels: lgtm, approved, rhoai

#1529 Fix kueue watch event handler for CRDs
  controllers/components/kueue/kueue_controller.go
  tests/e2e/kueue_test.go
Labels: lgtm, approved

#1534 [rhoai] Fix kueue watch event handler for CRDs (#1529)
  controllers/components/kueue/kueue_controller.go
  tests/e2e/kueue_test.go
Labels: lgtm, approved, rhoai

#1511 [rhoai] Update Component rules in Prometheus
  Dockerfiles/Dockerfile
  config/monitoring/networkpolicy/operator/operator.yaml
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/suite_test.go
  controllers/services/monitoring/monitoring.go
  controllers/services/monitoring/monitoring_controller.go
  controllers/services/monitoring/monitoring_controller_actions.go
  main.go
  pkg/cluster/gvk/gvk.go
  pkg/controller/handlers/handlers.go
  pkg/controller/predicates/component/component.go
  pkg/controller/predicates/resources/resources.go
  pkg/upgrade/upgrade.go
  tests/e2e/controller_test.go
  tests/e2e/helper_test.go
  tests/e2e/monitoring_test.go
  tests/e2e/odh_manager_test.go
  tests/prometheus_unit_tests/codeflare-alerting.rules.yaml
  tests/prometheus_unit_tests/data-science-pipelines-operator-alerting.rules.yaml
  tests/prometheus_unit_tests/kserve-alerting.rules.yaml
  tests/prometheus_unit_tests/kueue-alerting.rules.yaml
  tests/prometheus_unit_tests/model-mesh-alerting.rules.yaml
  tests/prometheus_unit_tests/odh-model-controller-alerting.rules.yaml
  tests/prometheus_unit_tests/ray-alerting.rules.yaml
  tests/prometheus_unit_tests/rhods-dashboard-alerting.rules.yaml
  tests/prometheus_unit_tests/trainingoperator-alerting.rules.yaml
  tests/prometheus_unit_tests/trustyai-alerting.rules.yaml
  tests/prometheus_unit_tests/workbenches-alerting.rules.yaml
Labels: lgtm, approved, rhoai

#1535 chore: remove unused structs and functions from controlelrs/status package
  controllers/status/status.go
Labels: lgtm, approved

#1537 fix: when app ns and monitoring ns are the same, createorupdate wont work
  controllers/dscinitialization/utils.go
Labels: lgtm, approved

#1540 fix: use Monitoring.Spec.Namespace instead of the DSCI one
  controllers/services/monitoring/monitoring_controller_actions.go
Labels: lgtm, approved

#1542 chore: cleanup Monitoring's initialize action
  controllers/services/monitoring/monitoring_controller_actions.go
Labels: lgtm, approved

#1548 [rhoai] Avoid modelmesh and Kserve loop on updating shared CRDs
  controllers/components/kserve/kserve_controller.go
  controllers/components/modelmeshserving/modelmeshserving_controller.go
Labels: lgtm, approved, rhoai

#1547 Avoid modelmesh and Kserve loop on updating shared CRDs
  controllers/components/kserve/kserve_controller.go
  controllers/components/modelmeshserving/modelmeshserving_controller.go
Labels: lgtm, approved

#1552 fix: add missing namespace for console in managed cluster
  controllers/dscinitialization/monitoring.go
  main.go
  pkg/cluster/const.go
Labels: lgtm, approved

#1556 [sync]: fix: add missing namespace for console in managed cluster (#1552)
  controllers/dscinitialization/monitoring.go
  main.go
  pkg/cluster/const.go
Labels: lgtm, approved, rhoai

#1536 update: various fix backport from RHOAI
  config/monitoring/networkpolicy/operator/operator.yaml
  controllers/dscinitialization/utils.go
  main.go
Labels: lgtm, approved

#1550 Align get_all_manifests.sh with Kubeflow main branch
  get_all_manifests.sh
Labels: lgtm, approved

#1558 fix: missing monitoring NS for NWP if user opt-in customized app NS
  main.go
Labels: lgtm, approved

#1560 [sync]fix: missing monitoring NS for NWP if user opt customized app NS (#1558)
  main.go
Labels: lgtm, approved, rhoai

#1557 update: change previous workaround for subscription and add smcp in disable list
  main.go
Labels: approved

#1561 [sync]update: change previous workaround for subscription and add smcp in the list (#1557)
  main.go
Labels: lgtm, approved

#1549 Build platform independent binary based on the target platform
  Dockerfiles/Dockerfile
Labels: lgtm, approved, needs-ok-to-test

#1567 fix: for upgrade case we will need update permission on buildconfig to remove old DSC as ownerref
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/datasciencecluster/kubebuilder_rbac.go
Labels: lgtm, approved

#1494 update: clean up old code before refactor
  controllers/dscinitialization/dscinitialization_controller.go
  main.go
  pkg/deploy/deploy.go
  pkg/upgrade/upgrade.go
Labels: lgtm, approved

#1564 It takes more than 10 minutes for kserve-controller to be created during 2.17 installation
  controllers/components/kserve/kserve_controller.go
  pkg/controller/predicates/resources/resources.go
  pkg/feature/servicemesh/conditions.go
Labels: lgtm, approved

#1569 [sync]fix: add matchlabel on NWP for customized appliation (#1566)
  README.md
  controllers/dscinitialization/utils.go
  docs/troubleshooting.md
Labels: lgtm, approved, rhoai

#1570 test: disable monitoring config in DSCI for ODH e2e test
  tests/e2e/helper_test.go
Labels: lgtm, approved, testing

#1538 Clarify and update permissions
  controllers/services/auth/resources/README.md
  controllers/services/auth/resources/admingroup-clusterrole.tmpl.yaml
  controllers/services/auth/resources/admingroup-role.tmpl.yaml
Labels: lgtm, approved

#1572 [sync]It takes more than 10 minutes for kserve-controller to be created during 2.17 installation (#1564)
  controllers/components/kserve/kserve_controller.go
  pkg/controller/predicates/resources/resources.go
  pkg/feature/servicemesh/conditions.go
Labels: lgtm, approved, rhoai

#1541 chore: use constants from the status package where possible
  controllers/services/monitoring/monitoring.go
  controllers/services/monitoring/monitoring_controller_actions.go
Labels: lgtm, approved

#1574 (fix): point to correct path for component integration doc
  README.md
Labels: lgtm, approved

#1573 Setup admin permissions for hardware profiles
  controllers/services/auth/resources/admingroup-role.tmpl.yaml
Labels: lgtm, approved

#1577 fix: fix wrong map for DSP images
  controllers/components/datasciencepipelines/datasciencepipelines_support.go
Labels: lgtm, approved, component/pipelines

#1576 fix: missing update permission on dashboard object during upgrade from old version to new refactor
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/datasciencecluster/kubebuilder_rbac.go
Labels: lgtm, approved

#1579 [sync]fix: missing update permission on dashboard object
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/datasciencecluster/kubebuilder_rbac.go
Labels: lgtm, approved

#1575 docs: remove duplicated files and update integration docs
  docs/COMPONENT_INTEGRATION.md
  docs/troubleshooting.md2
Labels: approved

#1562 Improve Kserve's FeatureTraker handing
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/components/kserve/kserve_controller.go
  controllers/components/kserve/kserve_controller_actions.go
  controllers/components/kserve/kserve_support.go
  controllers/datasciencecluster/kubebuilder_rbac.go
  controllers/dscinitialization/kubebuilder_rbac.go
  pkg/cluster/gvk/gvk.go
  pkg/cluster/meta.go
  pkg/controller/actions/deploy/action_deploy.go
  pkg/controller/actions/deploy/action_deploy_support.go
  pkg/controller/actions/deploy/action_deploy_support_test.go
  pkg/feature/builder.go
  pkg/feature/feature.go
  pkg/feature/feature_tracker_handler.go
  pkg/feature/handler.go
  pkg/resources/resources.go
  pkg/resources/resources_test.go
  tests/e2e/kserve_test.go
Labels: lgtm, approved

#1581 fix: missing permission to update prometheusrules
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/datasciencecluster/kubebuilder_rbac.go
Labels: lgtm, approved

#1584 [sync]fix: missing permission to update prometheusrules
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/datasciencecluster/kubebuilder_rbac.go
Labels: lgtm, approved, component/kueue, rhoai

#1587 [sync]fix: more permission need for dashboard for consolelink
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/datasciencecluster/kubebuilder_rbac.go
Labels: lgtm, approved, rhoai

#1586 fix: more permission need for dashboard for consolelink
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/datasciencecluster/kubebuilder_rbac.go
Labels: lgtm, approved

#1580 chore: move Release structs from pkg/cluster to apis/common
  apis/common/types.go
  apis/common/zz_generated.deepcopy.go
  apis/datasciencecluster/v1/datasciencecluster_types.go
  apis/dscinitialization/v1/dscinitialization_types.go
  controllers/components/codeflare/codeflare.go
  controllers/components/dashboard/dashboard.go
  controllers/components/dashboard/dashboard_support.go
  controllers/components/datasciencepipelines/datasciencepipelines.go
  controllers/components/datasciencepipelines/datasciencepipelines_support.go
  controllers/components/kserve/kserve.go
  controllers/components/kueue/kueue.go
  controllers/components/modelcontroller/modelcontroller.go
  controllers/components/modelmeshserving/modelmeshserving.go
  controllers/components/modelregistry/modelregistry.go
  controllers/components/ray/ray.go
  controllers/components/trainingoperator/trainingoperator.go
  controllers/components/trustyai/trustyai.go
  controllers/components/trustyai/trustyai_support.go
  controllers/components/workbenches/workbenches.go
  controllers/dscinitialization/utils.go
  main.go
  pkg/cluster/cluster_config.go
  pkg/cluster/const.go
  pkg/cluster/zz_generated.deepcopy.go
  pkg/componentsregistry/componentsregistry.go
  pkg/controller/actions/deleteresource/action_delete_resources_test.go
  pkg/controller/actions/deploy/action_deploy_cache_test.go
  pkg/controller/actions/deploy/action_deploy_test.go
  pkg/controller/actions/gc/action_gc_test.go
  pkg/controller/actions/render/kustomize/action_render_manifests_test.go
  pkg/controller/actions/render/template/action_render_templates_test.go
  pkg/controller/actions/updatestatus/action_update_status_test.go
  pkg/controller/reconciler/reconciler.go
  pkg/controller/types/types.go
  pkg/upgrade/uninstallation.go
  pkg/upgrade/upgrade.go
  tests/e2e/controller_test.go
Labels: lgtm, approved

#1585 apis: DSCInitialization: annotate ApplicationsNamespace with omitempty
  apis/dscinitialization/v1/dscinitialization_types.go
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
Labels: lgtm, approved

#1588 chore: fix DataSciencePipelines e2e test suite
  tests/e2e/datasciencepipelines_test.go
Labels: lgtm, approved

#1591 Remove legacy ModelController deployment on upgrade
  pkg/upgrade/upgrade.go
Labels: lgtm, approved

#1593 github: add branch into GHA for tests
  .github/workflows/linter.yaml
  .github/workflows/unit-tests.yaml
Labels: lgtm

#1582 docs: update workflow and how we use two branchs for ODH and downstream
  CONTRIBUTING.md
  docs/sync_code.md
Labels: documentation, lgtm, approved

#1590 [sync] fix: Prevent containers from running as root by removing unnecessary anyuid SCC bindings
  controllers/components/dashboard/dashboard_controller.go
  controllers/components/dashboard/dashboard_support.go
  controllers/components/modelcontroller/modelcontroller_controller.go
  controllers/components/modelcontroller/modelcontroller_support.go
  controllers/components/modelmeshserving/modelmeshserving_controller.go
  controllers/components/modelmeshserving/modelmeshserving_support.go
  controllers/components/workbenches/workbenches_controller.go
  controllers/components/workbenches/workbenches_support.go
  controllers/dscinitialization/dscinitialization_test.go
  controllers/dscinitialization/utils.go
  pkg/controller/actions/security/actions.go
  pkg/controller/actions/security/actions_test.go
  pkg/upgrade/upgrade.go
Labels: lgtm, approved

#1598 Remove Sara4994 from OWNER_ALIASES
  OWNERS_ALIASES
Labels: lgtm, approved

#1596 tests: e2e: increase timeout to 40m
  Makefile
Labels: lgtm, approved

#1583 update: platform team
  OWNERS_ALIASES
Labels: do-not-merge/invalid-owners-file, lgtm, approved

#1599 Add helper functions to retrieve object singletons
  controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/services/monitoring/monitoring_controller_actions.go
  pkg/cluster/resources.go
  pkg/cluster/resources_test.go
  pkg/controller/reconciler/reconciler.go
  pkg/upgrade/upgrade.go
  pkg/utils/test/fakeclient/fakeclient.go
Labels: lgtm, approved

#1498 feat: Add Feast Operator component
  README.md
  apis/components/v1alpha1/feastoperator_types.go
  apis/components/v1alpha1/zz_generated.deepcopy.go
  apis/datasciencecluster/v1/datasciencecluster_types.go
  apis/datasciencecluster/v1/zz_generated.deepcopy.go
  bundle/manifests/components.platform.opendatahub.io_feastoperators.yaml
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/crd/bases/components.platform.opendatahub.io_feastoperators.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/kustomization.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  config/samples/datasciencecluster_v1_datasciencecluster.yaml
  controllers/components/feastoperator/feastoperator.go
  controllers/components/feastoperator/feastoperator_controller.go
  controllers/components/feastoperator/feastoperator_controller_actions.go
  controllers/components/feastoperator/feastoperator_support.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/datasciencecluster/kubebuilder_rbac.go
  controllers/webhook/webhook_suite_test.go
  docs/DESIGN.md
  docs/api-overview.md
  docs/upgrade-testing.md
  get_all_manifests.sh
  main.go
  pkg/cluster/gvk/gvk.go
  pkg/upgrade/upgrade.go
  tests/e2e/controller_test.go
  tests/e2e/feastoperator_test.go
  tests/e2e/helper_test.go
  tests/e2e/odh_manager_test.go
Labels: lgtm, approved, component/feast
