Repository opendatahub-io/opendatahub-operator, pull requests merged in 2025-04, with the labels that each got.

#1801 feat: reduce operator-sdk dependency
  Dockerfiles/bundle.Dockerfile
  Makefile
  README.md
  api/common/types.go
  api/datasciencecluster/v1/datasciencecluster_types.go
  api/dscinitialization/v1/dscinitialization_types.go
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  go.mod
  go.sum
Labels: lgtm, approved

#1808 chore: add new member, remove old members
  OWNERS_ALIASES
Labels: lgtm

#1811 (fix): Change code generation templates
  cmd/component-codegen/templates/component_handler.go.tmpl
  cmd/component-codegen/templates/component_support.go.tmpl
  cmd/component-codegen/templates/types.go.tmpl
  docs/COMPONENT_INTEGRATION.md
Labels: lgtm, approved

#1813 DSCI creation got stuck in operator reconciliation in selfmanaged clusters
  pkg/cluster/resources.go
Labels: lgtm, approved

#1816 (feat): add logic to update PROJECT file
  cmd/component-codegen/cmd/generator/generator.go
  cmd/component-codegen/cmd/generator/update_project_file.go
Labels: lgtm, approved

#1738 Refactor and Optimize E2E Tests
  README.md
  docs/troubleshooting.md
  pkg/cluster/gvk/gvk.go
  pkg/controller/reconciler/reconciler_actions_test.go
  pkg/resources/resources.go
  pkg/resources/resources_test.go
  pkg/utils/test/testf/testf_support.go
  pkg/utils/test/testf/testf_witht.go
  tests/e2e/authcontroller_test.go
  tests/e2e/cfmap_deletion_test.go
  tests/e2e/cleanup_test.go
  tests/e2e/codeflare_test.go
  tests/e2e/components_test.go
  tests/e2e/controller_test.go
  tests/e2e/creation_test.go
  tests/e2e/dashboard_test.go
  tests/e2e/datasciencepipelines_test.go
  tests/e2e/deletion_test.go
  tests/e2e/feastoperator_test.go
  tests/e2e/helper_test.go
  tests/e2e/kserve_test.go
  tests/e2e/kueue_test.go
  tests/e2e/modelcontroller_test.go
  tests/e2e/modelmeshserving_test.go
  tests/e2e/modelregistry_test.go
  tests/e2e/monitoring_test.go
  tests/e2e/odh_manager_test.go
  tests/e2e/ray_test.go
  tests/e2e/resource_applier_test.go
  tests/e2e/resource_fetcher_test.go
  tests/e2e/resource_options_test.go
  tests/e2e/trainingoperator_test.go
  tests/e2e/trustyai_test.go
  tests/e2e/workbenches_test.go
Labels: lgtm, approved

#1800 [sync] update: remove Unknown constant from platform detection logic
  internal/controller/components/dashboard/dashboard_controller_actions.go
  internal/controller/components/dashboard/dashboard_support.go
  internal/controller/components/datasciencepipelines/datasciencepipelines_support.go
  internal/controller/components/trustyai/trustyai_support.go
  pkg/cluster/cluster_config.go
  pkg/cluster/const.go
  tests/e2e/authcontroller_test.go
Labels: lgtm, approved

#1815 [sync] feat: reduce operator-sdk dependency
  Dockerfiles/bundle.Dockerfile
  Makefile
  README.md
  api/common/types.go
  api/datasciencecluster/v1/datasciencecluster_types.go
  api/dscinitialization/v1/dscinitialization_types.go
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manifests/bases/rhods-operator.clusterserviceversion.yaml
  go.mod
  go.sum
Labels: lgtm, approved

#1823 update: add support for overlays in Feast
  internal/controller/components/feastoperator/feastoperator.go
  internal/controller/components/feastoperator/feastoperator_controller_actions.go
  internal/controller/components/feastoperator/feastoperator_support.go
Labels: lgtm, approved, odh-2.27, rhoai-2.20

#1834 [chore] Refactor TestContext and Apply Feedback from PR #1738
  README.md
  pkg/resources/resources.go
  pkg/utils/test/testf/testf_support.go
  tests/e2e/authcontroller_test.go
  tests/e2e/cfmap_deletion_test.go
  tests/e2e/codeflare_test.go
  tests/e2e/components_test.go
  tests/e2e/controller_test.go
  tests/e2e/creation_test.go
  tests/e2e/dashboard_test.go
  tests/e2e/datasciencepipelines_test.go
  tests/e2e/deletion_test.go
  tests/e2e/feastoperator_test.go
  tests/e2e/helper_test.go
  tests/e2e/kserve_test.go
  tests/e2e/kueue_test.go
  tests/e2e/modelcontroller_test.go
  tests/e2e/modelmeshserving_test.go
  tests/e2e/modelregistry_test.go
  tests/e2e/monitoring_test.go
  tests/e2e/odh_manager_test.go
  tests/e2e/ray_test.go
  tests/e2e/resource_applier_test.go
  tests/e2e/resource_fetcher_test.go
  tests/e2e/resource_options_test.go
  tests/e2e/test_context_test.go
  tests/e2e/trainingoperator_test.go
  tests/e2e/trustyai_test.go
  tests/e2e/workbenches_test.go
Labels: lgtm, approved

#1836 Cluster-monitoring label missing from redhat-ods-monitoring namespace
  internal/controller/dscinitialization/utils.go
  internal/controller/dscinitialization/utils_test.go
Labels: lgtm, approved

#1838 [rhoai] Cluster-monitoring label missing from redhat-ods-monitoring namespace
  internal/controller/dscinitialization/utils.go
  internal/controller/dscinitialization/utils_test.go
Labels: lgtm, approved, rhoai

#1839 Added get, list, and watch to storageclasses
  internal/controller/services/auth/resources/admingroup-clusterrole.tmpl.yaml
Labels: lgtm, approved

#1820 Remove pkg/controller/client.Client and use dedicated clients/function
  .golangci.yml
  cmd/main.go
  internal/controller/datasciencecluster/datasciencecluster_controller.go
  internal/controller/dscinitialization/dscinitialization_controller.go
  internal/controller/dscinitialization/suite_test.go
  internal/controller/services/monitoring/monitoring.go
  internal/controller/status/doc.go
  pkg/cluster/gvk/gvk.go
  pkg/cluster/resources.go
  pkg/controller/actions/deploy/action_deploy.go
  pkg/controller/actions/deploy/action_deploy_cache_test.go
  pkg/controller/actions/deploy/action_deploy_test.go
  pkg/controller/actions/gc/action_gc.go
  pkg/controller/actions/gc/action_gc_test.go
  pkg/controller/actions/gc/engine/gc_engine.go
  pkg/controller/actions/gc/engine/gc_engine_support.go
  pkg/controller/actions/gc/engine/gc_engine_test.go
  pkg/controller/client/client.go
  pkg/controller/manager/manager.go
  pkg/controller/reconciler/reconciler.go
  pkg/controller/reconciler/reconciler_finalizer_test.go
  pkg/controller/reconciler/reconciler_test.go
  pkg/controller/types/types.go
  pkg/resources/resources.go
  pkg/resources/resources_test.go
  pkg/resources/resources_types.go
  pkg/rules/rules.go
  pkg/rules/rules_test.go
  pkg/utils/test/envt/envt.go
  pkg/utils/test/fakeclient/fakeclient.go
  pkg/utils/test/mocks/types.go
  pkg/utils/test/testf/testf.go
  pkg/utils/test/testf/testf_witht.go
Labels: lgtm, approved

#1844 [rhoai] Add feast in RHOAI
  README.md
  api/components/v1alpha1/feastoperator_types.go
  api/components/v1alpha1/zz_generated.deepcopy.go
  api/datasciencecluster/v1/datasciencecluster_types.go
  api/datasciencecluster/v1/zz_generated.deepcopy.go
  bundle/manifests/components.platform.opendatahub.io_feastoperators.yaml
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  cmd/main.go
  config/crd/bases/components.platform.opendatahub.io_feastoperators.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/kustomization.yaml
  config/manifests/bases/rhods-operator.clusterserviceversion.yaml
  config/monitoring/prometheus/apps/prometheus-configs.yaml
  config/rbac/role.yaml
  config/samples/datasciencecluster_v1_datasciencecluster.yaml
  docs/DESIGN.md
  docs/api-overview.md
  docs/upgrade-testing.md
  get_all_manifests.sh
  internal/controller/components/feastoperator/feastoperator.go
  internal/controller/components/feastoperator/feastoperator_controller.go
  internal/controller/components/feastoperator/feastoperator_controller_actions.go
  internal/controller/components/feastoperator/feastoperator_support.go
  internal/controller/datasciencecluster/datasciencecluster_controller.go
  internal/controller/datasciencecluster/kubebuilder_rbac.go
  internal/controller/services/monitoring/monitoring.go
  internal/controller/services/monitoring/monitoring_controller_actions.go
  internal/webhook/webhook_suite_test.go
  pkg/cluster/gvk/gvk.go
  pkg/upgrade/upgrade.go
  tests/e2e/controller_test.go
  tests/e2e/feastoperator_test.go
  tests/e2e/helper_test.go
  tests/e2e/odh_manager_test.go
  tests/prometheus_unit_tests/feast-operator-alerting.unit-tests.yaml
Labels: lgtm, approved, rhoai-2.20

#1848 [rhoai] Introduce Service Registry alongside Components Registry
  .golangci.yml
  cmd/main.go
  internal/controller/components/codeflare/codeflare.go
  internal/controller/components/dashboard/dashboard.go
  internal/controller/components/datasciencepipelines/datasciencepipelines.go
  internal/controller/components/feastoperator/feastoperator.go
  internal/controller/components/kserve/kserve.go
  internal/controller/components/kueue/kueue.go
  internal/controller/components/modelcontroller/modelcontroller.go
  internal/controller/components/modelmeshserving/modelmeshserving.go
  internal/controller/components/modelregistry/modelregistry.go
  internal/controller/components/ray/ray.go
  internal/controller/components/registry/registry.go
  internal/controller/components/trainingoperator/trainingoperator.go
  internal/controller/components/trustyai/trustyai.go
  internal/controller/components/workbenches/workbenches.go
  internal/controller/datasciencecluster/datasciencecluster_controller_actions.go
  internal/controller/datasciencecluster/datasciencecluster_controller_support.go
  internal/controller/services/auth/auth.go
  internal/controller/services/auth/auth_controller.go
  internal/controller/services/monitoring/monitoring.go
  internal/controller/services/monitoring/monitoring_controller.go
  internal/controller/services/monitoring/monitoring_controller_actions.go
  internal/controller/services/registry/registry.go
  pkg/utils/test/testf/testf_assertions.go
Labels: lgtm, approved, rhoai

#1843 fix: remove IgnoreIfAggregationRule predicate
  internal/controller/components/kserve/kserve_controller.go
  internal/controller/components/modelmeshserving/modelmeshserving_controller.go
  pkg/controller/predicates/clusterrole/clusterrole.go
Labels: lgtm, approved

#1852 [sync] fix: remove IgnoreIfAggregationRule predicate (#1843)
  internal/controller/components/kserve/kserve_controller.go
  internal/controller/components/modelmeshserving/modelmeshserving_controller.go
  pkg/controller/predicates/clusterrole/clusterrole.go
Labels: lgtm, approved

#1851 chore: update description for feast
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/description-patch.yml
Labels: lgtm, component/feast

#1850 update: add init config for feast to show as Removed
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  config/manifests/bases/rhods-operator.clusterserviceversion.yaml
Labels: approved

#1856 chore: move services to the related internal/controller/services package
  internal/controller/certconfigmapgenerator/certconfigmapgenerator_controller.go
  internal/controller/secretgenerator/secretgenerator_controller.go
  internal/controller/services/certconfigmapgenerator/certconfigmapgenerator.go
  internal/controller/services/certconfigmapgenerator/certconfigmapgenerator_controller.go
  internal/controller/services/secretgenerator/README.md
  internal/controller/services/secretgenerator/secret.go
  internal/controller/services/secretgenerator/secret_test.go
  internal/controller/services/secretgenerator/secretgenerator.go
  internal/controller/services/secretgenerator/secretgenerator_controller.go
  internal/controller/services/setup/setup.go
  internal/controller/services/setup/setup_controller.go
  internal/controller/setupcontroller/setup_controller.go
Labels: lgtm, approved

#1853 [rhoai] chore: update feast description
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  config/manifests/bases/rhods-operator.clusterserviceversion.yaml
  config/manifests/description-patch.yml
Labels: lgtm, approved

#1770 fix/chore: replace outdated cluster.Platform references
  docs/COMPONENT_INTEGRATION.md
Labels: lgtm, approved

#1849 [rhoai] Refactor SetupController, SecretGenerator and CertConfigmapGenerator to service handler
  cmd/main.go
  internal/controller/certconfigmapgenerator/certconfigmapgenerator_controller.go
  internal/controller/secretgenerator/secretgenerator_controller.go
  internal/controller/services/certconfigmapgenerator/certconfigmapgenerator_controller.go
  internal/controller/services/secretgenerator/secretgenerator_controller.go
  internal/controller/services/setup/setup_controller.go
  internal/controller/setupcontroller/setup_controller.go
Labels: lgtm, approved, rhoai

#1854 chore: typo fix
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Labels: lgtm

#1859 chore: Refresh owners list used for reviewer assignment
  OWNERS_ALIASES
Labels: lgtm, approved

#1857 Update to Go 1.23
  Dockerfiles/Dockerfile
  Dockerfiles/toolbox.Dockerfile
  Makefile
Labels: lgtm, approved

#1866 Revert "fix: add missing new pipeline flag into default sample"
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/samples/datasciencecluster_v1_datasciencecluster.yaml
Labels: lgtm

#1869 fix DSC samples and README such that the default sample works for RawDeployment
  README.md
  config/samples/datasciencecluster_v1_datasciencecluster.yaml
Labels: lgtm, approved

#1860 RHOAIENG-21259: Make tests configurable from environment variables
  Makefile
  README.md
  go.mod
  go.sum
  tests/e2e/controller_test.go
  tests/e2e/creation_test.go
  tests/e2e/helper_test.go
  tests/e2e/kserve_test.go
  tests/e2e/modelcontroller_test.go
  tests/e2e/test_context_test.go
  tests/e2e/trustyai_test.go
Labels: lgtm, approved

#1870 RHOAIENG-24104: Only deploy kserve SM resources with Authorino
  internal/controller/components/kserve/kserve.go
  internal/controller/components/kserve/kserve_controller_actions.go
  internal/controller/components/kserve/kserve_controller_actions_test.go
Labels: lgtm, approved

#1774 configuring KnativeServing to allow zero initial scale when installed
  internal/controller/components/kserve/resources/serving-install/knative-serving.tmpl.yaml
Labels: lgtm, approved, rhoai-2.21

#1858 Update go.mod to 1.23 and fix lint issues
  .ci-operator.yaml
  README.md
  cmd/component-codegen/go.mod
  go.mod
  go.sum
  pkg/rules/rules.go
  tests/e2e/controller_test.go
Labels: lgtm, approved

#1874 added resoluteCoder GH alias to owner list
  OWNERS_ALIASES
Labels: lgtm, approved

#1875 Add sefroberg GH alias to owners list
  OWNERS_ALIASES
Labels: lgtm, approved

#1864 fix:RHOAIENG-21276 delete unused odh-common-config in DSCInitialization controller
  internal/controller/dscinitialization/dscinitialization_test.go
  internal/controller/dscinitialization/utils.go
Labels: lgtm, approved, ok-to-test

#1873 feat: migrate resource deploy logic to SSA
  pkg/cluster/cert.go
  pkg/cluster/cluster_operations_int_test.go
  pkg/cluster/resources.go
  pkg/controller/actions/deploy/action_deploy.go
  pkg/resources/resources.go
  pkg/trustedcabundle/trustedcabundle.go
Labels: lgtm, approved

#1831 chore: optimize kustomize sortOptions tests for readability
  pkg/utils/test/matchers/jq/jq_matcher_test.go
Labels: lgtm, approved

#1879 [chore] Remove DeleteResourceIfExists in favor of WithIgnoreNotFound and WithWaitForDeletion
  tests/e2e/cleanup_test.go
  tests/e2e/components_test.go
  tests/e2e/controller_test.go
  tests/e2e/kserve_test.go
  tests/e2e/kueue_test.go
  tests/e2e/resource_options_test.go
  tests/e2e/test_context_test.go
  tests/e2e/trustyai_test.go
Labels: lgtm, approved

#1882 [sync] feat: migrate resource deploy logic to SSA
  pkg/cluster/cert.go
  pkg/cluster/cluster_operations_int_test.go
  pkg/cluster/gvk/gvk.go
  pkg/cluster/resources.go
  pkg/controller/actions/deploy/action_deploy.go
  pkg/resources/resources.go
  pkg/trustedcabundle/trustedcabundle.go
Labels: lgtm, approved

#1883 Update go.mod to 1.23 and fix lint issues (#1858)
  .ci-operator.yaml
  README.md
  go.mod
  pkg/rules/rules.go
  tests/e2e/controller_test.go
Labels: lgtm, approved

#1880 Update golangci-lint to v2.x and fix findings
  .golangci.yml
  Makefile
  cmd/component-codegen/cmd/generate.go
  internal/controller/components/codeflare/codeflare.go
  internal/controller/components/dashboard/dashboard.go
  internal/controller/components/datasciencepipelines/datasciencepipelines.go
  internal/controller/components/feastoperator/feastoperator.go
  internal/controller/components/kserve/kserve.go
  internal/controller/components/kserve/kserve_controller_actions.go
  internal/controller/components/kueue/kueue.go
  internal/controller/components/modelmeshserving/modelmeshserving.go
  internal/controller/components/modelregistry/modelregistry.go
  internal/controller/components/ray/ray.go
  internal/controller/components/trainingoperator/trainingoperator.go
  internal/controller/components/trustyai/trustyai.go
  internal/controller/components/workbenches/workbenches.go
  internal/controller/dscinitialization/auth.go
  internal/controller/dscinitialization/dscinitialization_controller.go
  internal/controller/dscinitialization/utils.go
  internal/controller/services/auth/auth_controller_actions.go
  internal/controller/services/certconfigmapgenerator/certconfigmapgenerator_controller.go
  internal/controller/services/secretgenerator/secretgenerator_controller.go
  pkg/controller/actions/render/kustomize/action_render_manifests.go
  pkg/controller/actions/render/template/action_render_templates.go
  pkg/controller/types/types.go
  pkg/feature/servicemesh/resources.go
  pkg/resources/resources_types.go
  pkg/rules/rules_test.go
  pkg/upgrade/upgrade.go
  pkg/utils/test/fakeclient/fakeclient.go
  tests/e2e/monitoring_test.go
  tests/e2e/test_context_test.go
  tests/envtestutil/cleaner.go
Labels: lgtm, approved

#1862 [sync] Refactor and Optimize E2E Tests
  Makefile
  README.md
  docs/troubleshooting.md
  go.mod
  go.sum
  pkg/cluster/gvk/gvk.go
  pkg/controller/reconciler/reconciler_actions_test.go
  pkg/resources/resources.go
  pkg/resources/resources_test.go
  pkg/utils/test/testf/testf_support.go
  pkg/utils/test/testf/testf_witht.go
  tests/e2e/authcontroller_test.go
  tests/e2e/cfmap_deletion_test.go
  tests/e2e/cleanup_test.go
  tests/e2e/codeflare_test.go
  tests/e2e/components_test.go
  tests/e2e/controller_test.go
  tests/e2e/creation_test.go
  tests/e2e/dashboard_test.go
  tests/e2e/datasciencepipelines_test.go
  tests/e2e/deletion_test.go
  tests/e2e/feastoperator_test.go
  tests/e2e/helper_test.go
  tests/e2e/kserve_test.go
  tests/e2e/kueue_test.go
  tests/e2e/modelcontroller_test.go
  tests/e2e/modelmeshserving_test.go
  tests/e2e/modelregistry_test.go
  tests/e2e/monitoring_test.go
  tests/e2e/odh_manager_test.go
  tests/e2e/ray_test.go
  tests/e2e/resource_applier_test.go
  tests/e2e/resource_fetcher_test.go
  tests/e2e/resource_options_test.go
  tests/e2e/test_context_test.go
  tests/e2e/trainingoperator_test.go
  tests/e2e/trustyai_test.go
  tests/e2e/workbenches_test.go
Labels: lgtm, approved

#1884 [chore] Bump golang.org/x/net to v0.39.0
  go.mod
  go.sum
Labels: lgtm, approved

#1878 [sync]delete unused odh-common-config in DSCInitialization controller
  internal/controller/dscinitialization/dscinitialization_test.go
  internal/controller/dscinitialization/utils.go
Labels: lgtm, approved, ok-to-test

#1885 [sync][chore] Bump golang.org/x/net to v0.39.0
  go.mod
  go.sum
Labels: lgtm, approved

#1894 feat: Introduce dedicated ServiceMesh controller
  cmd/main.go
  internal/controller/dscinitialization/dscinitialization_controller.go
  internal/controller/services/servicemesh/capabilities.go
  internal/controller/services/servicemesh/servicemesh.go
  internal/controller/services/servicemesh/servicemesh_controller.go
  internal/controller/services/servicemesh/servicemesh_support.go
Labels: lgtm, approved
