Repository opendatahub-io/opendatahub-operator, pull requests merged in 2025-05, with the labels that each got.

#1896 chore: Clarify sync process in contributing docs
  CONTRIBUTING.md
  docs/sync_code.md
Labels: lgtm, approved

#1888 Upgrade controller-runtime, k8s libraries, and operator-sdk
  Makefile
  go.mod
  go.sum
  internal/webhook/webhook.go
  pkg/controller/reconciler/reconciler_finalizer_test.go
  pkg/controller/reconciler/reconciler_support.go
Labels: lgtm, approved

#1901 [sync][chore] Clarify sync process in contributing docs
  CONTRIBUTING.md
  docs/sync_code.md
Labels: lgtm, approved

#1902 [sync][update] kserve logic + small chores
  api/components/v1alpha1/kserve_types.go
  bundle/manifests/components.platform.opendatahub.io_kserves.yaml
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/bases/components.platform.opendatahub.io_kserves.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  docs/api-overview.md
  internal/controller/components/kserve/kserve.go
  internal/controller/components/kserve/kserve_controller.go
  internal/controller/components/kserve/kserve_controller_actions.go
  internal/controller/components/kserve/kserve_support.go
  internal/controller/status/status.go
Labels: lgtm, approved

#1904 [sync] chore: move services to the related internal/controller/services package
  internal/controller/certconfigmapgenerator/certconfigmapgenerator_controller.go
  internal/controller/secretgenerator/secretgenerator_controller.go
  internal/controller/secretgenerator/secretgenerator_controller_test.go
  internal/controller/services/certconfigmapgenerator/certconfigmapgenerator.go
  internal/controller/services/certconfigmapgenerator/certconfigmapgenerator_controller.go
  internal/controller/services/secretgenerator/README.md
  internal/controller/services/secretgenerator/secret.go
  internal/controller/services/secretgenerator/secret_test.go
  internal/controller/services/secretgenerator/secretgenerator.go
  internal/controller/services/secretgenerator/secretgenerator_controller.go
  internal/controller/services/setup/setup.go
  internal/controller/services/setup/setup_controller.go
  internal/controller/setupcontroller/setup_controller.go
Labels: lgtm, approved

#1905 [sync] Refactored auth group creation out of the DSCI controller
  internal/controller/dscinitialization/dscinitialization_controller.go
  internal/controller/dscinitialization/utils.go
  internal/controller/services/auth/auth.go
  internal/controller/services/auth/auth_controller.go
  internal/controller/services/auth/auth_controller_actions.go
  pkg/cluster/cluster_config.go
Labels: lgtm, approved

#1898 feat: supply FIPSENABLED value to params.env
  internal/controller/components/datasciencepipelines/datasciencepipelines.go
  internal/controller/components/datasciencepipelines/datasciencepipelines_support.go
  pkg/cluster/cluster_config.go
  pkg/cluster/cluster_config_test.go
Labels: lgtm, approved, ok-to-test

#1861 Enhance certconfigmapgenerator controller performance with dedicated cache and server-side apply
  cmd/main.go
  internal/controller/dscinitialization/dscinitialization_controller.go
  internal/controller/services/certconfigmapgenerator/certconfigmapgenerator.go
  internal/controller/services/certconfigmapgenerator/certconfigmapgenerator_controller.go
  internal/controller/services/certconfigmapgenerator/certconfigmapgenerator_support.go
  internal/controller/services/certconfigmapgenerator/certconfigmapgenerator_test.go
  pkg/cluster/cluster_config.go
  pkg/controller/handlers/handlers.go
  pkg/controller/predicates/resources/resources.go
  pkg/controller/predicates/resources/resources_test.go
  pkg/resources/resources.go
  pkg/trustedcabundle/trustedcabundle.go
  pkg/utils/test/envt/envt.go
  pkg/utils/test/testf/testf.go
Labels: lgtm, approved

#1910 [sync] chore(deps): remove dependency on kube-aggregator as the related type…
  cmd/main.go
  go.mod
  go.sum
Labels: lgtm, approved

#1899 Refactor to use custom Condition type
  api/common/types.go
  api/dscinitialization/v1/dscinitialization_types.go
  api/dscinitialization/v1/zz_generated.deepcopy.go
  api/features/v1/features_types.go
  api/features/v1/zz_generated.deepcopy.go
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/crd/bases/features.opendatahub.io_featuretrackers.yaml
  docs/api-overview.md
  go.mod
  go.sum
  internal/controller/services/servicemesh/capabilities.go
  internal/controller/services/servicemesh/servicemesh_support.go
  internal/controller/status/status.go
  tests/integration/features/tracker_int_test.go
Labels: lgtm, approved

#1911 [sync] chore(deps): remove dependency on addon-operator APIs as the related …
  cmd/main.go
  go.mod
  go.sum
Labels: lgtm, approved

#1914 [sync] chore(deps): remove dependency on github.com/pkg/errors and swith to …
  go.mod
  pkg/cluster/cert.go
  pkg/feature/servicemesh/conditions.go
Labels: lgtm, approved

#1915 [sync] Refactor feature manifests test and remove dependdency on the afero l…
  go.mod
  pkg/feature/manifest/manifest_suite_test.go
  pkg/feature/manifest/manifest_test.go
  pkg/feature/manifest/resources/raw/my-configmap.yaml
  pkg/feature/manifest/resources/template/my-configmap.tmpl.yaml
Labels: lgtm, approved

#1916 [sync] Upgrade controller-runtime, k8s libraries, and operator-sdk
  Makefile
  go.mod
  go.sum
  internal/controller/services/monitoring/monitoring.go
  internal/webhook/webhook.go
  pkg/controller/reconciler/reconciler_finalizer_test.go
  pkg/controller/reconciler/reconciler_support.go
Labels: lgtm, approved

#1918 [sync] Refactor to use custom Condition type
  api/common/types.go
  api/dscinitialization/v1/dscinitialization_types.go
  api/dscinitialization/v1/zz_generated.deepcopy.go
  api/features/v1/features_types.go
  api/features/v1/zz_generated.deepcopy.go
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/crd/bases/features.opendatahub.io_featuretrackers.yaml
  docs/api-overview.md
  go.mod
  go.sum
  internal/controller/dscinitialization/capabilities.go
  internal/controller/dscinitialization/servicemesh_setup.go
  internal/controller/status/status.go
  tests/integration/features/tracker_int_test.go
Labels: lgtm, approved

#1903 RHOAIENG-21259: Refactor configuration managment to use viper
  README.md
  cmd/main.go
  pkg/deploy/envParams.go
  pkg/logger/logger.go
  pkg/utils/flags/flags.go
Labels: lgtm, approved

#1921 Use SSA for default NetworkPolicy creation
  internal/controller/dscinitialization/dscinitialization_controller.go
  internal/controller/dscinitialization/utils.go
  pkg/cluster/gvk/gvk.go
  tests/e2e/creation_test.go
Labels: lgtm, approved

#1928 Improve fake client helper
  internal/controller/components/kserve/kserve_controller_actions_test.go
  internal/controller/dscinitialization/utils_test.go
  pkg/cluster/resources_test.go
  pkg/controller/actions/deleteresource/action_delete_resources_test.go
  pkg/controller/actions/deploy/action_deploy_test.go
  pkg/controller/actions/status/deployments/action_deployments_available_test.go
  pkg/upgrade/upgrade_test.go
  pkg/utils/test/fakeclient/fakeclient.go
  pkg/utils/test/scheme/scheme.go
  pkg/utils/test/testf/testf_witht_test.go
Labels: lgtm, approved

#1931 update: do not use skipRange for ODH release
  .github/scripts/update-versions.sh
Labels: lgtm, approved

#1930 [sync] Use SSA for default NetworkPolicy creation
  internal/controller/dscinitialization/dscinitialization_controller.go
  internal/controller/dscinitialization/utils.go
  pkg/cluster/gvk/gvk.go
  tests/e2e/creation_test.go
Labels: lgtm, approved, rhoai

#1938 fix: when servicemesh is not managed in DSCI should not have MissingOperator True
  internal/controller/services/servicemesh/servicemesh_support.go
  internal/controller/status/status.go
Labels: lgtm, approved

#1941 [sync] Enhance certconfigmapgenerator controller performance with dedicated cache and server-side apply
  cmd/main.go
  internal/controller/dscinitialization/dscinitialization_controller.go
  internal/controller/services/certconfigmapgenerator/certconfigmapgenerator.go
  internal/controller/services/certconfigmapgenerator/certconfigmapgenerator_controller.go
  internal/controller/services/certconfigmapgenerator/certconfigmapgenerator_support.go
  internal/controller/services/certconfigmapgenerator/certconfigmapgenerator_test.go
  pkg/cluster/cluster_config.go
  pkg/controller/handlers/handlers.go
  pkg/controller/predicates/resources/resources.go
  pkg/controller/predicates/resources/resources_test.go
  pkg/resources/resources.go
  pkg/trustedcabundle/trustedcabundle.go
  pkg/utils/test/envt/envt.go
  pkg/utils/test/testf/testf.go
Labels: lgtm, approved, rhoai

#1940 [sync] Improve fake client helper
  internal/controller/components/kserve/kserve_controller_actions_test.go
  internal/controller/dscinitialization/utils_test.go
  pkg/cluster/resources_test.go
  pkg/controller/actions/deleteresource/action_delete_resources_test.go
  pkg/controller/actions/deploy/action_deploy_test.go
  pkg/controller/actions/status/deployments/action_deployments_available_test.go
  pkg/upgrade/upgrade_test.go
  pkg/utils/test/fakeclient/fakeclient.go
  pkg/utils/test/scheme/scheme.go
  pkg/utils/test/testf/testf_witht_test.go
Labels: lgtm, approved, rhoai

#1932 Ensure NetworkPolicy has TypeMeta set
  internal/controller/dscinitialization/utils.go
Labels: lgtm, approved

#1927 update: namespace for workbenches
  bundle/manifests/components.platform.opendatahub.io_workbenches.yaml
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/features.opendatahub.io_featuretrackers.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  internal/controller/components/workbenches/workbenches_controller.go
  internal/controller/components/workbenches/workbenches_controller_actions.go
Labels: lgtm, approved

#1943 [sync]: Updated default workbench namespace, namespace creation logic
  bundle/manifests/components.platform.opendatahub.io_workbenches.yaml
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/features.opendatahub.io_featuretrackers.yaml
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  internal/controller/components/workbenches/workbenches_controller.go
  internal/controller/components/workbenches/workbenches_controller_actions.go
  pkg/cluster/const.go
Labels: lgtm, approved

#1945 add rh registry images vars for dsp
  internal/controller/components/datasciencepipelines/datasciencepipelines_support.go
Labels: lgtm, approved

#1948 Add third party image vars for model registry
  internal/controller/components/modelregistry/modelregistry_support.go
Labels: lgtm, approved

#1917 Add TestNewSecret unit Test Case
  internal/controller/services/secretgenerator/secret_test.go
Labels: lgtm, approved

#1942 Update image references to EL9 names
  Dockerfiles/Dockerfile
  config/monitoring/blackbox-exporter/base/blackbox-exporter-deployment.yaml
  config/monitoring/prometheus/base/prometheus-deployment.yaml
  config/partners/anaconda/base/anaconda-ce-validator-cron.yaml
Labels: lgtm, approved

#1944 chore: add cherrypick bot as owner
  OWNERS_ALIASES
Labels: lgtm

#1956 Update codecov-actions to v5.4.3
  .github/workflows/unit-tests.yaml
Labels: lgtm, approved

#1957 fix: need update config bundle to make update-release.sh work in ODH release
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#1962 Revert "chore: add cherrypick bot as owner"
  OWNERS_ALIASES
Labels: lgtm

#1967 update: change env variable name for DSP and ModelReg to match CVE
  internal/controller/components/datasciencepipelines/datasciencepipelines_support.go
  internal/controller/components/modelregistry/modelregistry_support.go
Labels: lgtm

#1946 [backport]fix: need apply application NWP for self-managed cluster
  internal/controller/dscinitialization/utils.go
Labels: lgtm, approved, rhoai-2.21

#1971 [sync] update: change env variable name for DSP and ModelReg to match CSV (#1967)
  internal/controller/components/datasciencepipelines/datasciencepipelines_support.go
Labels: lgtm, rhoai-2.21

#1842 update: remove ModelReg dependency to Servicemesh
  internal/controller/components/kserve/kserve.go
  internal/controller/components/kserve/kserve_controller_actions.go
  internal/controller/components/kserve/kserve_controller_actions_test.go
  internal/controller/components/modelregistry/modelregistry_controller.go
  internal/controller/components/modelregistry/modelregistry_controller_actions.go
  internal/controller/components/modelregistry/modelregistry_support.go
  internal/controller/components/modelregistry/resources/servicemesh-member.tmpl.yaml
  internal/controller/status/status.go
  tests/e2e/modelregistry_test.go
Labels: lgtm, approved, rhoai-2.21

#1970 If TrustedCABundle ManagementState is set to Unmanaged. controller should not remove odh-trusted-ca-bundle ConfigMap
  internal/controller/services/certconfigmapgenerator/certconfigmapgenerator_controller.go
  internal/controller/services/certconfigmapgenerator/certconfigmapgenerator_support.go
  internal/controller/services/certconfigmapgenerator/certconfigmapgenerator_test.go
Labels: lgtm, approved, rhoai-2.21

#1974 [sync]fix: need apply application NWP for self-managed cluster (#1946) + some code difference
  internal/controller/dscinitialization/utils.go
Labels: lgtm, approved, rhoai-2.21

#1399 feat: added integration tests to cover evicted pods in post conditions
  Makefile
  tests/integration/features/fixtures/cluster_test_fixtures.go
  tests/integration/features/postconditions_int_test.go
Labels: lgtm, approved, testing

#1922 chore: Add downstream process details to sync_code.md
  docs/sync_code.md
Labels: lgtm, approved

#1961 RHOAIENG-21259 and RHOAIENG-22955
  cmd/main.go
Labels: lgtm, approved

#1966 Revert changes to images made in #1942
  config/monitoring/blackbox-exporter/base/blackbox-exporter-deployment.yaml
  config/monitoring/prometheus/base/prometheus-deployment.yaml
  config/partners/anaconda/base/anaconda-ce-validator-cron.yaml
Labels: lgtm, approved

#1985 Update: various optimizations
  .dockerignore
  Dockerfiles/Dockerfile
  Makefile
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  cmd/main.go
  get_all_manifests.sh
  internal/controller/dscinitialization/monitoring.go
  pkg/common/common.go
  pkg/controller/types/types.go
  pkg/upgrade/uninstallation.go
  pkg/upgrade/upgrade.go
Labels: lgtm, approved

#1980 [sync] RHOAIENG-21259 and RHOAIENG-22955
  cmd/main.go
Labels: lgtm, approved

#1988 backport of rhoai RHOAIENG-21259: added openshift-operators namespace cache to createODHGeneralCacheConfig
  cmd/main.go
Labels: lgtm, approved

#1972 RHOAIENG-26125: Opendatahub operator release process worflow
  README.md
  docs/release-workflow-guide.md
  docs/sync_code.md
Labels: lgtm, approved

#1990 (feat):Add changes to enable FBC
  .github/scripts/update-versions.sh
  .gitignore
  Dockerfiles/bundle.Dockerfile
  Dockerfiles/catalog.Dockerfile
  Makefile
  README.md
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/catalog/fbc-basic-template.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  hack/update-catalog-template.sh
Labels: approved
