Repository opendatahub-io/opendatahub-operator, pull requests merged in 2025-06, with the labels that each got.

#2000 Adding-dmoskale-to-opendatahuboperator-owners
  OWNERS_ALIASES
Labels: do-not-merge/invalid-owners-file, lgtm, approved, ok-to-test

#1978 change kserve release branch from 0.14 to 0.15
  get_all_manifests.sh
Labels: lgtm, approved, component/kserve

#1984 feat: add support to pass Oauth proxy image for downstream
  internal/controller/components/kserve/kserve.go
  internal/controller/components/kserve/kserve_support.go
  internal/controller/components/trustyai/trustyai_support.go
Labels: lgtm, approved, odh-2.30

#1976 RHOAIENG-25367 | feat: Added scraping label to odh resources
  internal/controller/components/codeflare/codeflare_controller.go
  internal/controller/components/dashboard/dashboard_controller.go
  internal/controller/components/datasciencepipelines/datasciencepipelines_controller.go
  internal/controller/components/feastoperator/feastoperator_controller.go
  internal/controller/components/kserve/kserve_controller.go
  internal/controller/components/kueue/kueue_controller.go
  internal/controller/components/modelcontroller/modelcontroller_controller.go
  internal/controller/components/modelmeshserving/modelmeshserving_controller.go
  internal/controller/components/modelregistry/modelregistry_controller.go
  internal/controller/components/ray/ray_controller.go
  internal/controller/components/trainingoperator/trainingoperator_controller.go
  internal/controller/components/trustyai/trustyai_controller.go
  internal/controller/components/workbenches/workbenches_controller.go
  pkg/controller/actions/observability/action_monitoring.go
  pkg/controller/actions/observability/action_monitoring_test.go
  pkg/metadata/labels/types.go
Labels: lgtm, approved, ok-to-test, component/kueue

#2001 feat: move HardwareProfile CRD to odh-operator
  PROJECT
  api/infrastructure/v1alpha1/groupversion_info.go
  api/infrastructure/v1alpha1/hardwareprofile_types.go
  api/infrastructure/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/infrastructure.opendatahub.io_hardwareprofiles.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  cmd/main.go
  config/crd/bases/infrastructure.opendatahub.io_hardwareprofiles.yaml
  config/crd/kustomization.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  docs/api-overview.md
  internal/controller/datasciencecluster/kubebuilder_rbac.go
Labels: lgtm, approved, odh-2.30, glue

#1960 RHOAI-452 | feat: modified code to only use wait.ExponentialBackoffWithContext
  internal/controller/dscinitialization/utils.go
  internal/controller/services/secretgenerator/secretgenerator_controller.go
  pkg/cluster/operator.go
  pkg/cluster/resources.go
  pkg/feature/conditions.go
  pkg/feature/servicemesh/conditions.go
  pkg/upgrade/upgrade.go
  tests/integration/features/servicemesh_feature_test.go
Labels: lgtm, approved, needs-ok-to-test

#2016 fix: ensure compatibility with nowebhook builds
  cmd/main.go
  internal/webhook/nowebhook.go
  internal/webhook/webhook.go
Labels: lgtm, approved

#2004 [sync]RHOAIENG-22956 Assess and clean up tools.go
  tools.go
Labels: lgtm, approved, ok-to-test

#1997 (feat): Add FBC processor workflow
  .github/scripts/update-versions.sh
  .github/workflows/process-fbc-fragment.yaml
  Dockerfiles/bundle.Dockerfile
  Makefile
  bundle/metadata/annotations.yaml
  config/catalog/fbc-basic-template.yaml
Labels: lgtm, approved, odh-2.30

#1992 feat: Relocate kueue manifests to odh-operator
  Dockerfiles/Dockerfile
  config/kueue-configs/batch-user-rolebinding.yaml
  config/kueue-configs/binding_admin_roles.yaml
  config/kueue-configs/kustomization.yaml
  config/kueue-configs/ocp-4.17-addons/kustomization.yaml
  config/kueue-configs/ocp-4.17-addons/validating_admission_policy.yaml
  config/kueue-configs/ocp-4.17-addons/validating_admission_policy_binding.yaml
  get_all_manifests.sh
  internal/controller/components/kueue/kueue_controller.go
  internal/controller/components/kueue/kueue_controller_actions.go
  internal/controller/components/kueue/kueue_controller_actions_test.go
  internal/controller/components/kueue/kueue_support.go
  pkg/controller/predicates/resources/resources.go
Labels: lgtm, approved, component/kueue, kueue-migration

#2038 feat: add priorityClass field to HardwareProfile CRD
  api/infrastructure/v1alpha1/hardwareprofile_types.go
  bundle/manifests/infrastructure.opendatahub.io_hardwareprofiles.yaml
  config/crd/bases/infrastructure.opendatahub.io_hardwareprofiles.yaml
  docs/api-overview.md
Labels: lgtm, approved, feature/kueue

#2043 fix: removed unneeded fields from HardwareProfile
  api/infrastructure/v1alpha1/hardwareprofile_types.go
  bundle/manifests/infrastructure.opendatahub.io_hardwareprofiles.yaml
  config/crd/bases/infrastructure.opendatahub.io_hardwareprofiles.yaml
  docs/api-overview.md
Labels: lgtm

#2061 RHOAIENG-26313-enable-multi-container-probing
  internal/controller/components/kserve/resources/serving-install/knative-serving.tmpl.yaml
Labels: lgtm, component/kserve

#2062 RHOAIENG-25252: [ODH Operator] Support "Unmanaged" Kueue in OpenShift AI
  Dockerfiles/Dockerfile
  api/components/v1alpha1/kueue_types.go
  api/components/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/components.platform.opendatahub.io_kueues.yaml
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/bases/components.platform.opendatahub.io_kueues.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  docs/api-overview.md
  internal/controller/components/codeflare/codeflare.go
  internal/controller/components/codeflare/codeflare_test.go
  internal/controller/components/dashboard/dashboard.go
  internal/controller/components/dashboard/dashboard_test.go
  internal/controller/components/datasciencepipelines/datasciencepipelines.go
  internal/controller/components/datasciencepipelines/datasciencepipelines_test.go
  internal/controller/components/feastoperator/feastoperator.go
  internal/controller/components/feastoperator/feastoperator_test.go
  internal/controller/components/kserve/kserve.go
  internal/controller/components/kserve/kserve_test.go
  internal/controller/components/kueue/kueue.go
  internal/controller/components/kueue/kueue_controller.go
  internal/controller/components/kueue/kueue_controller_actions.go
  internal/controller/components/kueue/kueue_controller_actions_test.go
  internal/controller/components/kueue/kueue_test.go
  internal/controller/components/modelcontroller/modelcontroller.go
  internal/controller/components/modelcontroller/modelcontroller_test.go
  internal/controller/components/modelmeshserving/modelmeshserving.go
  internal/controller/components/modelmeshserving/modelmeshserving_test.go
  internal/controller/components/modelregistry/modelregistry.go
  internal/controller/components/modelregistry/modelregistry_test.go
  internal/controller/components/ray/ray.go
  internal/controller/components/ray/ray_test.go
  internal/controller/components/registry/registry.go
  internal/controller/components/trainingoperator/trainingoperator.go
  internal/controller/components/trainingoperator/trainingoperator_test.go
  internal/controller/components/trustyai/trustyai.go
  internal/controller/components/trustyai/trustyai_test.go
  internal/controller/components/workbenches/workbenches.go
  internal/controller/components/workbenches/workbenches_test.go
  internal/controller/datasciencecluster/datasciencecluster_controller_actions.go
  internal/controller/datasciencecluster/datasciencecluster_controller_support.go
  internal/controller/services/monitoring/monitoring_controller_actions.go
  internal/controller/status/status.go
  internal/webhook/kueue/integration_test.go
  internal/webhook/kueue/validation_test.go
  pkg/upgrade/upgrade.go
  pkg/utils/test/mocks/types.go
  tests/e2e/authcontroller_test.go
  tests/e2e/cfmap_deletion_test.go
  tests/e2e/cleanup_test.go
  tests/e2e/components_test.go
  tests/e2e/controller_test.go
  tests/e2e/creation_test.go
  tests/e2e/dashboard_test.go
  tests/e2e/helper_test.go
  tests/e2e/kserve_test.go
  tests/e2e/kueue_test.go
  tests/e2e/modelcontroller_test.go
  tests/e2e/resource_applier_test.go
  tests/e2e/test_context_test.go
  tests/e2e/trustyai_test.go
Labels: lgtm, approved

#2069 [sync]: Set controller deployment replicas to 3 for webhook HA
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  tests/e2e/odh_manager_test.go
Labels: lgtm, approved

#2070 chore: improve security of integration tests trigger action, fix catalog build
  .github/scripts/get-merge-commit.sh
  .github/scripts/verify_pr_author.py
  .github/workflows/get-merge-commit.yaml
  .github/workflows/integration-tests.yaml
Labels: lgtm, approved

#2079 feat: add podantiaffinity and nodeaffinity
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: lgtm, approved

#2081 ci: disable temporary the custom catalog gh action
  .github/workflows/integration-tests.yaml
Labels: lgtm, approved

#2085 Implement Auth validating webhook to reject invalid groups
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/webhook/manifests.yaml
  internal/webhook/auth/integration_test.go
  internal/webhook/auth/register.go
  internal/webhook/auth/validating.go
  internal/webhook/auth/validating_test.go
  internal/webhook/envtestutil/envtestutil.go
  internal/webhook/webhook.go
  pkg/utils/test/scheme/scheme.go
  tests/e2e/authcontroller_test.go
  tests/e2e/resource_options_test.go
  tests/e2e/test_context_test.go
Labels: lgtm, approved

#2064 feat: Add a management option for Argo Workflows
  api/components/v1alpha1/datasciencepipelines_types.go
  api/components/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/components.platform.opendatahub.io_datasciencepipelines.yaml
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/bases/components.platform.opendatahub.io_datasciencepipelines.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  docs/api-overview.md
  internal/controller/components/datasciencepipelines/datasciencepipelines_controller.go
  internal/controller/components/datasciencepipelines/datasciencepipelines_controller_actions.go
  internal/controller/components/datasciencepipelines/datasciencepipelines_controller_actions_test.go
  internal/controller/components/datasciencepipelines/datasciencepipelines_support.go
  internal/controller/status/status.go
  tests/e2e/datasciencepipelines_test.go
Labels: lgtm, approved, component/pipelines, rhoai-2.23

#2100 dynamic kueue admin rolebinding clean
  internal/controller/components/kueue/kueue_controller_actions.go
  internal/controller/components/kueue/kueue_support.go
  internal/controller/components/kueue/resources/kueue-admin-rolebinding.tmpl.yaml
Labels: lgtm, approved

#2099 Cherry-pick: Auth validating webhook, PodAntiAffinity, and NodeAffinity support
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/webhook/manifests.yaml
  internal/webhook/auth/integration_test.go
  internal/webhook/auth/register.go
  internal/webhook/auth/validating.go
  internal/webhook/auth/validating_test.go
  internal/webhook/envtestutil/envtestutil.go
  internal/webhook/webhook.go
  pkg/utils/test/scheme/scheme.go
  tests/e2e/authcontroller_test.go
  tests/e2e/resource_options_test.go
  tests/e2e/test_context_test.go
Labels: approved
