Repository opendatahub-io/opendatahub-operator, pull requests merged in 2025-07, with the labels that each got.

#2120 (fix): Remove cleanup in release automation
  .github/workflows/release-staging.yaml
Labels: lgtm, approved

#2122 Cherrypick 45943e4ab a2905159e
  api/components/v1alpha1/datasciencepipelines_types.go
  api/components/v1alpha1/zz_generated.deepcopy.go
  api/dscinitialization/v1/zz_generated.deepcopy.go
  api/services/v1alpha1/monitoring_types.go
  api/services/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/components.platform.opendatahub.io_datasciencepipelines.yaml
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  bundle/manifests/services.platform.opendatahub.io_monitorings.yaml
  cmd/main.go
  config/crd/bases/components.platform.opendatahub.io_datasciencepipelines.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/crd/bases/services.platform.opendatahub.io_monitorings.yaml
  config/rbac/role.yaml
  docs/api-overview.md
  internal/controller/components/datasciencepipelines/datasciencepipelines_controller.go
  internal/controller/components/datasciencepipelines/datasciencepipelines_controller_actions.go
  internal/controller/components/datasciencepipelines/datasciencepipelines_controller_actions_test.go
  internal/controller/components/datasciencepipelines/datasciencepipelines_support.go
  internal/controller/dscinitialization/dscinitialization_controller.go
  internal/controller/dscinitialization/dscinitialization_test.go
  internal/controller/dscinitialization/kubebuilder_rbac.go
  internal/controller/services/auth/auth_controller.go
  internal/controller/services/certconfigmapgenerator/certconfigmapgenerator.go
  internal/controller/services/monitoring/monitoring_controller.go
  internal/controller/services/monitoring/monitoring_controller_actions.go
  internal/controller/services/monitoring/monitoring_controller_support.go
  internal/controller/services/monitoring/resources/monitoring-stack.tmpl.yaml
  internal/controller/services/registry/registry.go
  internal/controller/services/secretgenerator/secretgenerator.go
  internal/controller/services/servicemesh/servicemesh.go
  internal/controller/services/setup/setup.go
  internal/controller/status/status.go
  pkg/cluster/gvk/gvk.go
  tests/e2e/creation_test.go
  tests/e2e/datasciencepipelines_test.go
  tests/e2e/helper_test.go
  tests/e2e/monitoring_test.go
Labels: lgtm, approved

#2126 Cherrypick 763d0a656 cfd664333
  .github/scripts/update-versions.sh
  .github/workflows/process-fbc-fragment.yaml
  Dockerfiles/bundle.Dockerfile
  Makefile
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/catalog/fbc-basic-template.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#2115 update: env variable name pass from build for lls-o image
  internal/controller/components/llamastackoperator/llamastackoperator_support.go
Labels: rhoai-2.23

#2113 Remove VAP manifests from Kueue configuration
  config/kueue-configs/ocp-4.17-addons/kustomization.yaml
  config/kueue-configs/ocp-4.17-addons/validating_admission_policy.yaml
  config/kueue-configs/ocp-4.17-addons/validating_admission_policy_binding.yaml
  internal/controller/components/kueue/kueue_controller.go
  internal/controller/components/kueue/kueue_controller_actions.go
  internal/controller/components/kueue/kueue_controller_actions_test.go
  internal/controller/components/kueue/kueue_support.go
  pkg/cluster/gvk/gvk.go
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_test.go
  tests/e2e/kueue_test.go
Labels: lgtm, approved

#2131 RHOAIENG-25253 and RHOAIENG-25404
  api/components/v1alpha1/kueue_types.go
  api/components/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/components.platform.opendatahub.io_kueues.yaml
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/crd/bases/components.platform.opendatahub.io_kueues.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/rbac/role.yaml
  docs/api-overview.md
  internal/controller/components/kueue/kueue.go
  internal/controller/components/kueue/kueue_controller.go
  internal/controller/components/kueue/kueue_controller_actions.go
  internal/controller/components/kueue/kueue_controller_actions_test.go
  internal/controller/components/kueue/kueue_support.go
  internal/controller/datasciencecluster/kubebuilder_rbac.go
  internal/controller/services/monitoring/resources/monitoring-stack.tmpl.yaml
  pkg/cluster/gvk/gvk.go
  pkg/controller/predicates/resources/resources.go
  pkg/controller/reconciler/reconciler_support.go
  pkg/utils/test/envt/envt.go
  tests/e2e/cleanup_test.go
  tests/e2e/kueue_test.go
  tests/e2e/monitoring_test.go
Labels: lgtm, approved

#2144 [sync] update Monitoring stack + github release
  .github/scripts/get-release-branches.js
  .github/scripts/update-manifests-tags.sh
  README.md
  api/services/v1alpha1/monitoring_types.go
  api/services/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/services.platform.opendatahub.io_monitorings.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/crd/bases/services.platform.opendatahub.io_monitorings.yaml
  docs/api-overview.md
  internal/controller/dscinitialization/dscinitialization_controller.go
  internal/controller/services/monitoring/monitoring_controller.go
  internal/controller/services/monitoring/monitoring_controller_actions.go
  internal/controller/services/monitoring/monitoring_controller_support.go
  internal/controller/services/monitoring/resources/monitoring-stack.tmpl.yaml
  tests/e2e/monitoring_test.go
Labels: lgtm, approved

#2146 feat: add replicas configable in DSCI.spec.monitoring
  README.md
  api/services/v1alpha1/monitoring_types.go
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/services.platform.opendatahub.io_monitorings.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/crd/bases/services.platform.opendatahub.io_monitorings.yaml
  docs/api-overview.md
  internal/controller/services/monitoring/monitoring_controller_actions.go
  internal/controller/services/monitoring/monitoring_controller_support.go
  internal/controller/services/monitoring/resources/monitoring-stack.tmpl.yaml
  tests/e2e/monitoring_test.go
Labels: lgtm, approved

#2152 update: point trustyai to ODH repo and update branch
  get_all_manifests.sh
Labels: lgtm, approved

#2151 Kueue migration fixed
  internal/controller/services/monitoring/monitoring_controller_actions.go
  internal/controller/services/monitoring/resources/monitoring-stack.tmpl.yaml
  tests/e2e/monitoring_test.go
Labels: lgtm, approved, run-integration-tests

#2155 chore: uplift version + renegerate bundle + set metrics: {} into default DSCI
  Makefile
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  bundle/manifests/services.platform.opendatahub.io_monitorings.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  config/samples/dscinitialization_v1_dscinitialization.yaml
  pkg/upgrade/upgrade.go
Labels: lgtm, approved

#2123 RHOAIENG-27559: Decouple Webhook Management from ClusterServiceVersion
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/webhook/manifests.yaml
  internal/controller/dscinitialization/dscinitialization_controller.go
  internal/controller/dscinitialization/dscinitialization_test.go
  internal/controller/dscinitialization/suite_test.go
  internal/webhook/envtestutil/envtestutil.go
  internal/webhook/kueue/integration_test.go
  internal/webhook/kueue/validating.go
  internal/webhook/kueue/validation_test.go
  internal/webhook/manager.go
  internal/webhook/manager_test.go
  internal/webhook/nomanager.go
Labels: lgtm, approved

#2153 RHOAIENG-27721 - Added e2e tests to validate resources are recreated upon deletion
  internal/controller/components/ray/ray_controller.go
  internal/controller/components/trainingoperator/trainingoperator_controller.go
  pkg/cluster/gvk/gvk.go
  tests/e2e/codeflare_test.go
  tests/e2e/components_test.go
  tests/e2e/dashboard_test.go
  tests/e2e/datasciencepipelines_test.go
  tests/e2e/feastoperator_test.go
  tests/e2e/kserve_test.go
  tests/e2e/kueue_test.go
  tests/e2e/llamastackoperator_test.go
  tests/e2e/modelcontroller_test.go
  tests/e2e/modelmeshserving_test.go
  tests/e2e/modelregistry_test.go
  tests/e2e/ray_test.go
  tests/e2e/trainingoperator_test.go
  tests/e2e/trustyai_test.go
  tests/e2e/workbenches_test.go
Labels: lgtm, approved

#2165 update: remove CRB from OCP API, to only use it from rbac.authorization.k8s.io
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/monitoring/prometheus/base/prometheus-rolebinding-scraper.yaml
  config/rbac/role.yaml
  internal/controller/datasciencecluster/kubebuilder_rbac.go
  pkg/cluster/gvk/gvk.go
Labels: lgtm, approved

#2147 feat: add support to remove monitoring and monitoringstack CR
  internal/controller/dscinitialization/dscinitialization_controller.go
  internal/controller/services/monitoring/monitoring_controller.go
  internal/controller/services/monitoring/monitoring_controller_actions.go
  internal/controller/services/monitoring/monitoring_controller_support.go
  tests/e2e/monitoring_test.go
Labels: lgtm, approved

#2170 [Sync] monitoring from main branch to rhoai
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  bundle/manifests/services.platform.opendatahub.io_monitorings.yaml
  config/samples/dscinitialization_v1_dscinitialization.yaml
  internal/controller/dscinitialization/dscinitialization_controller.go
  internal/controller/services/monitoring/monitoring_controller.go
  internal/controller/services/monitoring/monitoring_controller_actions.go
  internal/controller/services/monitoring/monitoring_controller_support.go
  pkg/upgrade/upgrade.go
  tests/e2e/monitoring_test.go
Labels: lgtm, approved

#2171 update: hide HWProfile from Operator tab from UI
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#2058 RHOAIENG-25354 | feat: Added tempo stack & monolith cr
  README.md
  api/services/v1alpha1/monitoring_types.go
  api/services/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  bundle/manifests/services.platform.opendatahub.io_monitorings.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/crd/bases/services.platform.opendatahub.io_monitorings.yaml
  config/rbac/role.yaml
  docs/api-overview.md
  internal/controller/dscinitialization/dscinitialization_controller.go
  internal/controller/dscinitialization/kubebuilder_rbac.go
  internal/controller/services/monitoring/monitoring_controller.go
  internal/controller/services/monitoring/monitoring_controller_actions.go
  internal/controller/services/monitoring/monitoring_controller_support.go
  internal/controller/services/monitoring/resources/monitoring-stack.tmpl.yaml
  internal/controller/services/monitoring/resources/tempo-monolithic.tmpl.yaml
  internal/controller/services/monitoring/resources/tempo-stack.tmpl.yaml
  internal/controller/services/servicemesh/servicemesh.go
  internal/controller/status/status.go
  pkg/cluster/gvk/gvk.go
  tests/e2e/creation_test.go
  tests/e2e/helper_test.go
  tests/e2e/monitoring_test.go
Labels: lgtm, approved

#2174 disable llama tests
  tests/e2e/controller_test.go
  tests/e2e/llamastackoperator_test.go
Labels: lgtm, approved

#2140 RHOAIENG-27732 | feat: adding authorino test
  tests/e2e/kserve_authorino_test.go
Labels: lgtm, approved

#2143 add deployment and configuration of opentelemetry collector and optional tracing functionality
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  cmd/main.go
  config/rbac/role.yaml
  internal/controller/dscinitialization/kubebuilder_rbac.go
  internal/controller/services/monitoring/monitoring_controller.go
  internal/controller/services/monitoring/monitoring_controller_actions.go
  internal/controller/services/monitoring/monitoring_controller_support.go
  internal/controller/services/monitoring/resources/collector-rbac.tmpl.yaml
  internal/controller/services/monitoring/resources/collector-servicemonitors.tmpl.yaml
  internal/controller/services/monitoring/resources/opentelemetry-collector.tmpl.yaml
  internal/controller/services/monitoring/resources/prometheus-route.tmpl.yaml
  internal/controller/status/status.go
  pkg/cluster/gvk/gvk.go
  tests/e2e/creation_test.go
  tests/e2e/helper_test.go
  tests/e2e/monitoring_test.go
Labels: lgtm, approved

#2028 RHOAIENG-25351 | feat: added missing operator monitoring checks
  api/services/v1alpha1/monitoring_types.go
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/crd/bases/services.platform.opendatahub.io_monitorings.yaml
  docs/api-overview.md
  internal/controller/dscinitialization/utils.go
  internal/controller/services/monitoring/monitoring_controller.go
  internal/controller/services/monitoring/monitoring_controller_support.go
  tests/e2e/creation_test.go
Labels: lgtm, approved, rhoai-2.23

#2180 Revert the PR for RHOAIENG-27559
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/webhook/manifests.yaml
  internal/controller/dscinitialization/dscinitialization_controller.go
  internal/controller/dscinitialization/dscinitialization_test.go
  internal/controller/dscinitialization/suite_test.go
  internal/webhook/envtestutil/envtestutil.go
  internal/webhook/hardwareprofile/integration_test.go
  internal/webhook/hardwareprofile/mutating_test.go
  internal/webhook/kueue/integration_test.go
  internal/webhook/kueue/validating.go
  internal/webhook/kueue/validation_test.go
  internal/webhook/manager.go
  internal/webhook/manager_test.go
  internal/webhook/nomanager.go
  pkg/cluster/const.go
  tests/e2e/kueue_test.go
Labels: approved, rhoai-2.23

#2187 update: add support for lls distro image
  internal/controller/components/llamastackoperator/llamastackoperator_support.go
Labels: lgtm, approved, rhoai-2.23

#2192 chore: make HWProfile CRD show in OCP console
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Labels: lgtm, approved, rhoai-2.23

#2185 chore: update in CSV and function
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/description-patch.yml
  internal/controller/components/kueue/kueue_config.go
  internal/controller/components/kueue/kueue_controller.go
  internal/controller/components/kueue/kueue_controller_actions.go
  internal/controller/components/kueue/kueue_controller_actions_test.go
  internal/controller/components/kueue/kueue_support.go
  internal/controller/datasciencecluster/kubebuilder_rbac.go
  internal/controller/services/auth/auth_controller_actions.go
  internal/controller/services/monitoring/monitoring_controller.go
  internal/controller/services/monitoring/monitoring_controller_support.go
  pkg/cluster/gvk/gvk.go
  tests/e2e/cleanup_test.go
  tests/e2e/kueue_test.go
Labels: lgtm, approved

#2198 Migrate Dockerfile symlink fixes and kueue-configs from main
  Dockerfiles/Dockerfile
  config/kueue-configs/batch-user-rolebinding.yaml
  config/kueue-configs/kustomization.yaml
  tests/e2e/kueue_test.go
Labels: lgtm, approved, rhoai-2.23

#2188 [Sync] Opentelemetry collector & Tempo operator
  README.md
  api/services/v1alpha1/monitoring_types.go
  api/services/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  bundle/manifests/services.platform.opendatahub.io_monitorings.yaml
  cmd/main.go
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/crd/bases/services.platform.opendatahub.io_monitorings.yaml
  config/rbac/role.yaml
  docs/api-overview.md
  internal/controller/dscinitialization/dscinitialization_controller.go
  internal/controller/dscinitialization/kubebuilder_rbac.go
  internal/controller/services/monitoring/monitoring_controller.go
  internal/controller/services/monitoring/monitoring_controller_actions.go
  internal/controller/services/monitoring/monitoring_controller_support.go
  internal/controller/services/monitoring/resources/collector-rbac.tmpl.yaml
  internal/controller/services/monitoring/resources/collector-servicemonitors.tmpl.yaml
  internal/controller/services/monitoring/resources/monitoring-stack.tmpl.yaml
  internal/controller/services/monitoring/resources/opentelemetry-collector.tmpl.yaml
  internal/controller/services/monitoring/resources/prometheus-route.tmpl.yaml
  internal/controller/services/monitoring/resources/tempo-monolithic.tmpl.yaml
  internal/controller/services/monitoring/resources/tempo-stack.tmpl.yaml
  internal/controller/status/status.go
  pkg/cluster/gvk/gvk.go
  tests/e2e/creation_test.go
  tests/e2e/helper_test.go
  tests/e2e/monitoring_test.go
Labels: lgtm, approved, rhoai-2.23

#2194 fix: kueue should also watch namespace has label "keueu-managed:true" + testcase
  internal/controller/components/kueue/kueue_controller.go
  tests/e2e/kueue_test.go
Labels: lgtm, approved, rhoai-2.23

#2206 Revert | RHOAIENG25367
  internal/controller/components/codeflare/codeflare_controller.go
  internal/controller/components/dashboard/dashboard_controller.go
  internal/controller/components/datasciencepipelines/datasciencepipelines_controller.go
  internal/controller/components/feastoperator/feastoperator_controller.go
  internal/controller/components/kserve/kserve_controller.go
  internal/controller/components/kueue/kueue_controller.go
  internal/controller/components/modelcontroller/modelcontroller_controller.go
  internal/controller/components/modelmeshserving/modelmeshserving_controller.go
  internal/controller/components/modelregistry/modelregistry_controller.go
  internal/controller/components/ray/ray_controller.go
  internal/controller/components/trainingoperator/trainingoperator_controller.go
  internal/controller/components/trustyai/trustyai_controller.go
  internal/controller/components/workbenches/workbenches_controller.go
  pkg/controller/actions/observability/action_monitoring.go
  pkg/controller/actions/observability/action_monitoring_test.go
  pkg/metadata/labels/types.go
Labels: lgtm, approved

#2202 update: lls disto image env variable name
  internal/controller/components/llamastackoperator/llamastackoperator_support.go
Labels: lgtm, rhoai-2.23, component/lls

#2214 added e2e test for hwprofile reconciliation
  tests/e2e/dashboard_test.go
Labels: lgtm, approved

#2215 fix: update monitoring e2e test
  tests/e2e/monitoring_test.go
Labels: lgtm, approved

#2116 RHOAIENG-25583 | feat: Added otel auto-instrumentation
  api/services/v1alpha1/monitoring_types.go
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  bundle/manifests/services.platform.opendatahub.io_monitorings.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/crd/bases/services.platform.opendatahub.io_monitorings.yaml
  config/rbac/role.yaml
  docs/api-overview.md
  internal/controller/dscinitialization/kubebuilder_rbac.go
  internal/controller/services/monitoring/monitoring_controller.go
  internal/controller/services/monitoring/monitoring_controller_actions.go
  internal/controller/services/monitoring/monitoring_controller_support.go
  internal/controller/services/monitoring/resources/instrumentation.tmpl.yaml
  internal/controller/status/status.go
  pkg/cluster/gvk/gvk.go
  tests/e2e/creation_test.go
  tests/e2e/helper_test.go
Labels: lgtm, approved, rhoai-2.23

#2217 RHOAIENG-25538 | test: Adding removed tests
  tests/e2e/monitoring_test.go
Labels: lgtm, approved, rhoai-2.23

#2228 Add support for downstream trusty-ai image overrides
  internal/controller/components/trustyai/trustyai_support.go
Labels: lgtm

#2032 Kserve Image Overrides
  internal/controller/components/kserve/kserve_support.go
Labels: rhoai-2.24

#2224 feat: add webhook for connection on isvc create/update
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/webhook/manifests.yaml
  internal/webhook/envtestutil/webhook_registration.go
  internal/webhook/hardwareprofile/integration_test.go
  internal/webhook/hardwareprofile/mutating.go
  internal/webhook/inferenceservice/mutating.go
  internal/webhook/inferenceservice/mutating_test.go
  internal/webhook/inferenceservice/register.go
  internal/webhook/kueue/integration_test.go
  internal/webhook/webhook.go
  pkg/metadata/annotations/annotations.go
  pkg/webhook/utils.go
  tests/e2e/kserve_test.go
Labels: lgtm, approved

#2231 [Sync] update: rbac for llm-d + uplift operator version
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controller/datasciencecluster/kubebuilder_rbac.go
  pkg/cluster/gvk/gvk.go
Labels: rhoai-2.24
