Repository opendatahub-io/opendatahub-operator, pull requests merged in 2025-02, with the labels that each got.

#1601 fix: do not set feast default to managed till GA
  pkg/upgrade/upgrade.go
Labels: lgtm

#1602 regen bundle
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
Labels: lgtm, approved

#1597 github: remove ODH release workflow for downstream
  .github/workflows/pre-release.yaml
  .github/workflows/release-e2e-dry-run.yaml
  .github/workflows/release.yaml
Labels: rhoai

#1565 Add Kserve Serverless availability to DSC status
  apis/components/v1alpha1/kserve_types.go
  bundle/manifests/components.platform.opendatahub.io_kserves.yaml
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/bases/components.platform.opendatahub.io_kserves.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  controllers/components/kserve/kserve_controller_actions.go
  docs/api-overview.md
Labels: lgtm, approved, rhoai-2.18

#1607 [Sync] changes from main
  controllers/services/monitoring/monitoring_controller_actions.go
Labels: lgtm, approved, rhoai

#1484 Add configuration to pipeline stanza of DSC to enable InstructLab pipeline
  README.md
  apis/components/v1alpha1/datasciencepipelines/types.go
  apis/components/v1alpha1/datasciencepipelines/zz_generated.deepcopy.go
  apis/components/v1alpha1/datasciencepipelines_types.go
  apis/components/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/components.platform.opendatahub.io_datasciencepipelines.yaml
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/bases/components.platform.opendatahub.io_datasciencepipelines.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  controllers/components/datasciencepipelines/datasciencepipelines.go
  controllers/components/datasciencepipelines/datasciencepipelines_controller_actions.go
  controllers/components/datasciencepipelines/datasciencepipelines_support.go
  controllers/components/datasciencepipelines/datasciencepipelines_support_test.go
  docs/api-overview.md
  tests/e2e/datasciencepipelines_test.go
  tests/e2e/helper_test.go
Labels: lgtm, approved, component/pipelines, rhoai-2.18

#1608 fix: hide internal API
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/manifests/bases/opendatahub-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#1609 fix: add missing new pipeline flag into default sample
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  config/samples/datasciencecluster_v1_datasciencecluster.yaml
Labels: lgtm, approved

#1610 e2e: enable kserve before running TrustyAI tests
  tests/e2e/trustyai_test.go
Labels: lgtm, approved

#1613 update: add new key-value into odh-model-controller
  controllers/components/modelcontroller/modelcontroller_actions.go
Labels: lgtm, approved

#1618 uplift: 2.17 to 2.18
  Makefile
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  config/manifests/bases/rhods-operator.clusterserviceversion.yaml
  get_all_manifests.sh
Labels: lgtm, approved, rhoai-2.18

#1616 feat: add check on 2 MultiKueue CRD if v1alpha1 version in the cluster and not in termination, error out
  bundle/manifests/opendatahub-operator.clusterserviceversion.yaml
  controllers/components/kueue/kueue_controller.go
  controllers/components/kueue/kueue_controller_actions.go
  controllers/status/status.go
  pkg/cluster/gvk/gvk.go
  pkg/cluster/operator.go
  tests/e2e/components_test.go
  tests/e2e/helper_test.go
  tests/e2e/kueue_test.go
Labels: lgtm, approved

#1571 add pipelines runtime image to dsp
  controllers/components/datasciencepipelines/datasciencepipelines_support.go
Labels: lgtm, rhoai-2.18

#1626 test: stablize test why adding post check after deletion
  tests/e2e/kueue_test.go
Labels: lgtm, approved, testing

#1627 build: enable tag to force image build with fips at runtime
  Dockerfiles/Dockerfile
Labels: lgtm, approved

#1637 [Sync]: Add configuration to pipeline stanza of DSC to enable InstructLab pipeline + new pipeline image
  README.md
  apis/components/v1alpha1/datasciencepipelines/types.go
  apis/components/v1alpha1/datasciencepipelines/zz_generated.deepcopy.go
  apis/components/v1alpha1/datasciencepipelines_types.go
  apis/components/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/components.platform.opendatahub.io_datasciencepipelines.yaml
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/bases/components.platform.opendatahub.io_datasciencepipelines.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  controllers/components/datasciencepipelines/datasciencepipelines.go
  controllers/components/datasciencepipelines/datasciencepipelines_controller_actions.go
  controllers/components/datasciencepipelines/datasciencepipelines_support.go
  controllers/components/datasciencepipelines/datasciencepipelines_support_test.go
  docs/api-overview.md
  tests/e2e/datasciencepipelines_test.go
  tests/e2e/helper_test.go
Labels: lgtm, approved, rhoai

#1636 [sync] docs: update workflow and how we use two branchs for ODH and downsteam (#1582)
  CONTRIBUTING.md
  docs/sync_code.md
Labels: lgtm, approved, rhoai

#1639 [sync] Add Kserve Serverless availability to DSC status (#1565)
  apis/components/v1alpha1/kserve_types.go
  bundle/manifests/components.platform.opendatahub.io_kserves.yaml
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/bases/components.platform.opendatahub.io_kserves.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  controllers/components/kserve/kserve_controller_actions.go
  docs/api-overview.md
Labels: approved, rhoai

#1638 [sync] update: add new key-value into odh-model-controller (#1613)
  controllers/components/modelcontroller/modelcontroller_actions.go
Labels: approved, rhoai

#1630 [sync]: mutli-arch + FIPS support
  Dockerfiles/Dockerfile
Labels: lgtm, approved, rhoai

#1635 [sync]: feat: add check on 2 MultiKueue CRD if v1alpha1 version in the cluster
  controllers/components/kueue/kueue_controller.go
  controllers/components/kueue/kueue_controller_actions.go
  controllers/status/status.go
  pkg/cluster/gvk/gvk.go
  pkg/cluster/operator.go
  tests/e2e/components_test.go
  tests/e2e/helper_test.go
  tests/e2e/kueue_test.go
Labels: approved, rhoai

#1640 Fix e2e services tests flags
  tests/e2e/controller_test.go
Labels: lgtm, approved

#1642 test: add config for gomega format and nim flag
  tests/e2e/controller_test.go
  tests/e2e/helper_test.go
Labels: lgtm, approved, testing

#1620 feat: add gate in TrustyAI if ISVC CRD is not in the cluster
  controllers/components/trustyai/trustyai_controller.go
  controllers/components/trustyai/trustyai_controller_actions.go
  controllers/status/status.go
  pkg/cluster/gvk/gvk.go
  tests/e2e/trustyai_test.go
Labels: lgtm, approved, rhoai-2.18

#1647 feat: support make to build multi-arch
  Dockerfiles/Dockerfile
  Makefile
  README.md
  docs/troubleshooting.md
Labels: approved

#1648 fix: allow dashboard to use devFlags but still get the correct values
  controllers/components/dashboard/dashboard_controller.go
  controllers/components/dashboard/dashboard_controller_actions.go
Labels: lgtm, approved

#1628 feat(test): support for Succeed and MatchError in testf framework
  pkg/utils/test/testf/testf_assertions.go
  pkg/utils/test/testf/testf_witht_test.go
  tests/e2e/components_test.go
  tests/e2e/dashboard_test.go
  tests/e2e/datasciencepipelines_test.go
  tests/e2e/kueue_test.go
  tests/e2e/modelcontroller_test.go
  tests/e2e/modelregistry_test.go
  tests/e2e/trustyai_test.go
Labels: lgtm, approved

#1646 chore(kserve): wrap error returned by FromUnstructured
  controllers/components/kserve/kserve_support.go
Labels: lgtm, approved

#1652 Revert "Add configuration to pipeline stanza of DSC to enable InstructLab pipeline (#1484)" + add support for platformVersionParamsKey
  README.md
  apis/components/v1alpha1/datasciencepipelines/types.go
  apis/components/v1alpha1/datasciencepipelines/zz_generated.deepcopy.go
  apis/components/v1alpha1/datasciencepipelines_types.go
  apis/components/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/components.platform.opendatahub.io_datasciencepipelines.yaml
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/bases/components.platform.opendatahub.io_datasciencepipelines.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  controllers/components/datasciencepipelines/datasciencepipelines.go
  controllers/components/datasciencepipelines/datasciencepipelines_controller_actions.go
  controllers/components/datasciencepipelines/datasciencepipelines_support.go
  controllers/components/datasciencepipelines/datasciencepipelines_support_test.go
  docs/api-overview.md
  tests/e2e/datasciencepipelines_test.go
  tests/e2e/helper_test.go
Labels: lgtm, approved

#1654 [Sync]feat: add gate in TrustyAI if ISVC CRD is not in the cluster
  controllers/components/trustyai/trustyai_controller.go
  controllers/components/trustyai/trustyai_controller_actions.go
  controllers/status/status.go
  pkg/cluster/gvk/gvk.go
  tests/e2e/trustyai_test.go
Labels: lgtm, approved, rhoai

#1650 Improve e2e test configurability
  tests/e2e/cfmap_deletion_test.go
  tests/e2e/controller_test.go
  tests/e2e/creation_test.go
  tests/e2e/helper_test.go
Labels: lgtm, approved

#1656 Improve gc service/action
  pkg/controller/actions/gc/action_gc.go
  pkg/controller/actions/gc/action_gc_support.go
  pkg/controller/actions/gc/action_gc_test.go
  pkg/services/gc/gc.go
  pkg/services/gc/gc_support.go
Labels: lgtm, approved

#1661 tests: e2e: disable FeastOperator
  tests/e2e/controller_test.go
  tests/e2e/feastoperator_test.go
Labels: lgtm, approved

#1621 update: remove ondelete not used for cleanup steps
  controllers/dscinitialization/servicemesh_setup.go
  pkg/feature/servicemesh/cleanup.go
  tests/integration/features/servicemesh_feature_test.go
Labels: lgtm

#1664 e2e: fix wrong validation message
  tests/e2e/controller_test.go
Labels: lgtm, approved

#1663 e2e: add compoennt/services flags support for parsing comma-separated values
  tests/e2e/controller_test.go
Labels: lgtm, approved

#1666 [Sync] changes from ODH to rhoai- improve + cleanup code + refactor
  apis/common/types.go
  apis/common/zz_generated.deepcopy.go
  apis/datasciencecluster/v1/datasciencecluster_types.go
  apis/dscinitialization/v1/dscinitialization_types.go
  controllers/components/codeflare/codeflare.go
  controllers/components/dashboard/dashboard.go
  controllers/components/dashboard/dashboard_support.go
  controllers/components/datasciencepipelines/datasciencepipelines.go
  controllers/components/datasciencepipelines/datasciencepipelines_support.go
  controllers/components/kserve/kserve.go
  controllers/components/kserve/kserve_support.go
  controllers/components/kueue/kueue.go
  controllers/components/modelcontroller/modelcontroller.go
  controllers/components/modelmeshserving/modelmeshserving.go
  controllers/components/modelregistry/modelregistry.go
  controllers/components/ray/ray.go
  controllers/components/trainingoperator/trainingoperator.go
  controllers/components/trustyai/trustyai.go
  controllers/components/trustyai/trustyai_support.go
  controllers/components/workbenches/workbenches.go
  controllers/dscinitialization/servicemesh_setup.go
  controllers/dscinitialization/utils.go
  go.mod
  main.go
  pkg/cluster/cluster_config.go
  pkg/cluster/const.go
  pkg/cluster/zz_generated.deepcopy.go
  pkg/componentsregistry/componentsregistry.go
  pkg/controller/actions/cacher/cacher.go
  pkg/controller/actions/cacher/cacher_test.go
  pkg/controller/actions/deleteresource/action_delete_resources_test.go
  pkg/controller/actions/deploy/action_deploy_cache_test.go
  pkg/controller/actions/deploy/action_deploy_test.go
  pkg/controller/actions/gc/action_gc.go
  pkg/controller/actions/gc/action_gc_support.go
  pkg/controller/actions/gc/action_gc_test.go
  pkg/controller/actions/render/kustomize/action_render_manifests.go
  pkg/controller/actions/render/kustomize/action_render_manifests_test.go
  pkg/controller/actions/render/template/action_render_templates.go
  pkg/controller/actions/render/template/action_render_templates_test.go
  pkg/controller/actions/resourcecacher/resourcecacher.go
  pkg/controller/actions/resourcecacher/resourcecacher_test.go
  pkg/controller/actions/updatestatus/action_update_status_test.go
  pkg/controller/reconciler/reconciler.go
  pkg/controller/types/types.go
  pkg/feature/servicemesh/cleanup.go
  pkg/services/gc/gc.go
  pkg/services/gc/gc_support.go
  pkg/upgrade/uninstallation.go
  pkg/upgrade/upgrade.go
  pkg/utils/test/testf/testf_assertions.go
  pkg/utils/test/testf/testf_witht_test.go
  tests/e2e/components_test.go
  tests/e2e/controller_test.go
  tests/e2e/dashboard_test.go
  tests/e2e/kueue_test.go
  tests/e2e/modelcontroller_test.go
  tests/e2e/modelregistry_test.go
  tests/e2e/trustyai_test.go
  tests/integration/features/servicemesh_feature_test.go
Labels: lgtm, approved, rhoai

#1662 [sync] prometheus-unit-tests from rhoai
  .github/workflows/prometheus-unit-tests.yaml
  .gitignore
  Makefile
  README.md
  tests/prometheus_unit_tests/.gitignore
  tests/prometheus_unit_tests/codeflare-alerting.rules.yaml
  tests/prometheus_unit_tests/codeflare-alerting.unit-tests.yaml
  tests/prometheus_unit_tests/data-science-pipelines-operator-alerting.rules.yaml
  tests/prometheus_unit_tests/data-science-pipelines-operator-alerting.unit-tests.yaml
  tests/prometheus_unit_tests/kserve-alerting.rules.yaml
  tests/prometheus_unit_tests/kserve-alerting.unit-tests.yaml
  tests/prometheus_unit_tests/kueue-alerting.rules.yaml
  tests/prometheus_unit_tests/kueue-alerting.unit-tests.yaml
  tests/prometheus_unit_tests/model-mesh-alerting.rules.yaml
  tests/prometheus_unit_tests/model-mesh-alerting.unit-tests.yaml
  tests/prometheus_unit_tests/odh-model-controller-alerting.rules.yaml
  tests/prometheus_unit_tests/odh-model-controller-alerting.unit-tests.yaml
  tests/prometheus_unit_tests/ray-alerting.rules.yaml
  tests/prometheus_unit_tests/ray-alerting.unit-tests.yaml
  tests/prometheus_unit_tests/rhods-dashboard-alerting.rules.yaml
  tests/prometheus_unit_tests/rhods-dashboard-alerting.unit-tests.yaml
  tests/prometheus_unit_tests/scripts/check_alert_tests.sh
  tests/prometheus_unit_tests/trainingoperator-alerting.rules.yaml
  tests/prometheus_unit_tests/trainingoperator-alerting.unit-tests.yaml
  tests/prometheus_unit_tests/trustyai-alerting.rules.yaml
  tests/prometheus_unit_tests/trustyai-alerting.unit-tests.yaml
  tests/prometheus_unit_tests/workbenches-alerting.rules.yaml
  tests/prometheus_unit_tests/workbenches-alerting.unit-tests.yaml
Labels: lgtm, approved

#1670 Update owners list
  .github/actions/update-release-version/action.yaml
  OWNERS_ALIASES
Labels: lgtm, approved

#1649 chore: ModelRegistry alert unit-tests
  tests/prometheus_unit_tests/model-registry-operator-alerting.unit-tests.yaml
Labels: lgtm, approved

#1669 Fix monitoring controller condition and owner reference setup
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/services/monitoring/monitoring_controller_actions.go
Labels: lgtm, approved

#1651 Move dashboardConfig checking to Auth CR creation.
  controllers/dscinitialization/auth.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/services/auth/auth_controller.go
  controllers/services/auth/auth_controller_actions.go
  tests/e2e/authcontroller_test.go
Labels: lgtm, approved

#1667 fix_label_in_RHOAI_Metrics_job
  config/monitoring/prometheus/apps/prometheus-configs.yaml
Labels: lgtm, approved

#1671 [rhoai] Fix monitoring controller condition and owner reference setup
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/services/monitoring/monitoring_controller_actions.go
Labels: lgtm, approved, rhoai

#1675 feat: Add support for finalizers
  pkg/controller/reconciler/reconciler.go
  pkg/controller/reconciler/reconciler_finalizer_test.go
Labels: lgtm, approved

#1678 Add missing predicates for Kserve dynamic watches
  controllers/components/kserve/kserve_controller.go
  controllers/components/kserve/kserve_support.go
Labels: lgtm, approved

#1679 Improve GC action
  pkg/controller/actions/gc/action_gc.go
  pkg/controller/actions/gc/action_gc_test.go
Labels: lgtm, approved

#1672 chore: prepare rhoai for 2.19 release
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  get_all_manifests.sh
Labels: lgtm, approved, rhoai-2.19

#1614 [sync] Map component versions to RHOAI status for better visibility
  apis/common/types.go
  apis/common/zz_generated.deepcopy.go
  apis/components/v1alpha1/codeflare_types.go
  apis/components/v1alpha1/datasciencepipelines_types.go
  apis/components/v1alpha1/kserve_types.go
  apis/components/v1alpha1/kueue_types.go
  apis/components/v1alpha1/modelmeshserving_types.go
  apis/components/v1alpha1/modelregistry_types.go
  apis/components/v1alpha1/ray_types.go
  apis/components/v1alpha1/trainingoperator_types.go
  apis/components/v1alpha1/trustyai_types.go
  apis/components/v1alpha1/workbenches_types.go
  apis/components/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/components.platform.opendatahub.io_codeflares.yaml
  bundle/manifests/components.platform.opendatahub.io_datasciencepipelines.yaml
  bundle/manifests/components.platform.opendatahub.io_kserves.yaml
  bundle/manifests/components.platform.opendatahub.io_kueues.yaml
  bundle/manifests/components.platform.opendatahub.io_modelmeshservings.yaml
  bundle/manifests/components.platform.opendatahub.io_modelregistries.yaml
  bundle/manifests/components.platform.opendatahub.io_rays.yaml
  bundle/manifests/components.platform.opendatahub.io_trainingoperators.yaml
  bundle/manifests/components.platform.opendatahub.io_trustyais.yaml
  bundle/manifests/components.platform.opendatahub.io_workbenches.yaml
  bundle/manifests/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  config/crd/bases/components.platform.opendatahub.io_codeflares.yaml
  config/crd/bases/components.platform.opendatahub.io_datasciencepipelines.yaml
  config/crd/bases/components.platform.opendatahub.io_kserves.yaml
  config/crd/bases/components.platform.opendatahub.io_kueues.yaml
  config/crd/bases/components.platform.opendatahub.io_modelmeshservings.yaml
  config/crd/bases/components.platform.opendatahub.io_modelregistries.yaml
  config/crd/bases/components.platform.opendatahub.io_rays.yaml
  config/crd/bases/components.platform.opendatahub.io_trainingoperators.yaml
  config/crd/bases/components.platform.opendatahub.io_trustyais.yaml
  config/crd/bases/components.platform.opendatahub.io_workbenches.yaml
  config/crd/bases/datasciencecluster.opendatahub.io_datascienceclusters.yaml
  controllers/components/codeflare/codeflare_controller.go
  controllers/components/datasciencepipelines/datasciencepipelines_controller.go
  controllers/components/kserve/kserve_controller.go
  controllers/components/kueue/kueue_controller.go
  controllers/components/modelmeshserving/modelmeshserving_controller.go
  controllers/components/modelregistry/modelregistry_controller.go
  controllers/components/ray/ray_controller.go
  controllers/components/trainingoperator/trainingoperator_controller.go
  controllers/components/trustyai/trustyai_controller.go
  controllers/components/workbenches/workbenches_controller.go
  docs/api-overview.md
  pkg/controller/actions/status/releases/action_fetch_releases_status.go
  pkg/controller/actions/status/releases/action_fetch_releases_status_test.go
  pkg/resources/resources.go
  tests/e2e/codeflare_test.go
  tests/e2e/components_test.go
  tests/e2e/datasciencepipelines_test.go
  tests/e2e/kserve_test.go
  tests/e2e/kueue_test.go
  tests/e2e/modelmeshserving_test.go
  tests/e2e/modelregistry_test.go
  tests/e2e/ray_test.go
  tests/e2e/trainingoperator_test.go
  tests/e2e/trustyai_test.go
Labels: lgtm, approved, rhoai-2.19

#1683 [sync] odh -> rhoai: predicates for Kserve dynamic watches
  controllers/certconfigmapgenerator/certconfigmapgenerator_controller.go
  controllers/components/kserve/kserve_controller.go
  controllers/components/kserve/kserve_support.go
  controllers/datasciencecluster/datasciencecluster_controller.go
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/services/monitoring/monitoring_controller_actions.go
  pkg/cluster/operator.go
  pkg/cluster/resources.go
  pkg/cluster/resources_test.go
  pkg/controller/reconciler/reconciler.go
  pkg/upgrade/upgrade.go
  pkg/utils/test/fakeclient/fakeclient.go
Labels: lgtm, approved, rhoai

#1685 model-registry: remove custom handdling of the modelregistry-editor-role and modelregistry-viewer-role cluster roles
  controllers/components/modelregistry/modelregistry_controller.go
  controllers/components/modelregistry/modelregistry_controller_actions.go
  pkg/cluster/gvk/gvk.go
Labels: lgtm, approved

#1686 [rhoai] model-registry: remove custom handdling of the modelregistry-editor-role and modelregistry-viewer-role cluster roles
  controllers/components/modelregistry/modelregistry_controller.go
  controllers/components/modelregistry/modelregistry_controller_actions.go
  pkg/cluster/gvk/gvk.go
Labels: lgtm, approved, rhoai

#1673 update: set KFTO to GA ready
  bundle/manifests/rhods-operator.clusterserviceversion.yaml
  config/manifests/bases/rhods-operator.clusterserviceversion.yaml
  config/samples/datasciencecluster_v1_datasciencecluster.yaml
  docs/DESIGN.md
  docs/upgrade-testing.md
  pkg/upgrade/upgrade.go
Labels: approved, rhoai-2.19, component/trainer

#1687 (fix): Add a hyperlink to code-gen README.md
  docs/COMPONENT_INTEGRATION.md
Labels: lgtm, approved

#1689 Improve test framework
  pkg/utils/test/envt/envt.go
  pkg/utils/test/fakeclient/fakeclient.go
  pkg/utils/test/mocks/types.go
  pkg/utils/test/scheme/scheme.go
  pkg/utils/test/testf/testf.go
Labels: lgtm, approved

#1681 chore: Allow cross-compilation in Dockerfile
  Dockerfiles/Dockerfile
Labels: lgtm, approved

#1692 e2e(components): ensure components are turned off at the end of the related test suite
  tests/e2e/codeflare_test.go
  tests/e2e/datasciencepipelines_test.go
  tests/e2e/kueue_test.go
  tests/e2e/modelregistry_test.go
  tests/e2e/ray_test.go
  tests/e2e/trainingoperator_test.go
  tests/e2e/trustyai_test.go
Labels: lgtm, approved

#1682 feat(mc): add model registry controller feature gate in model controller
  apis/components/v1alpha1/modelcontroller_types.go
  apis/components/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/components.platform.opendatahub.io_modelcontrollers.yaml
  config/crd/bases/components.platform.opendatahub.io_modelcontrollers.yaml
  controllers/components/modelcontroller/modelcontroller.go
  controllers/components/modelcontroller/modelcontroller_actions.go
  docs/api-overview.md
  tests/e2e/modelcontroller_test.go
Labels: lgtm, approved, component/modelregistry

#1676 update: monitoring config
  apis/dscinitialization/v1/dscinitialization_types.go
  apis/services/v1alpha1/monitoring_types.go
  apis/services/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/dscinitialization.opendatahub.io_dscinitializations.yaml
  bundle/manifests/services.platform.opendatahub.io_monitorings.yaml
  config/crd/bases/dscinitialization.opendatahub.io_dscinitializations.yaml
  config/crd/bases/services.platform.opendatahub.io_monitorings.yaml
  controllers/dscinitialization/dscinitialization_controller.go
  controllers/dscinitialization/dscinitialization_test.go
  controllers/dscinitialization/utils.go
  controllers/webhook/webhook_suite_test.go
  docs/api-overview.md
  main.go
  pkg/upgrade/upgrade.go
  tests/e2e/helper_test.go
Labels: lgtm, approved

#1702 update: change ossm sidecar as labels on authornio deployment
  controllers/dscinitialization/resources/authorino/deployment.injection.patch.tmpl.yaml
  controllers/dscinitialization/servicemesh_setup.go
Labels: lgtm, approved

#1697 RHOAIENG-18045: Add tests around FTs in Kserve
  tests/e2e/kserve_test.go
Labels: lgtm, approved
